### ISSUE TITLE
Request for new algorithm mode support

### ISSUE THREAD

**Issue by edison-ai** [Mbed-TLS/mbedtls#1321]
### Description
- Type: Enhancement\Feature Request
- Priority: Blocker

----------------------------------------------------------------
## Enhancement\Feature Request

**OS**
OPTEE_OS

**Enhancement\Feature Request**
We are integrate mbedTLS into OPTEE_OS(secure OS), but there are some algorithms not supported by mbedTLS:

***Do not support algorithm or mode:***
1.	DSA: include SHA1, SHA224 and SHA256 mode.
2.	Cipher(AES) CTS and XTS mode
3.	CBC_MAC: include AES_CBC_MAC_NOPAD, AES_CBC_MAC_PKCS5, DES_CBC_MAC_PKCS5, DES3_CBC_MAC_NOPAD and DES3_CBC_MAC_PKCS5 mode.

***Need enhance:***
1.	CCM: Need more interface: starts, update, finish for integrate.

After discuss with linaro, they think the CBC_MAC,  Cipher(AES) CTS and XTS mode can be replaced by the third party crypto library. But there is no around way for DSA, so the DSA must be support in mbedTLS.

Thanks,
Edison

**Comment by sbutcher-arm** [comment]
Thanks for the request @edison-ai! We'll have a look at it and see what we can do.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2083

**Comment by R030t1** [comment]
CBC-AES does not have good security characteristics[[1]] nor do many of the other modes supported. The watermarking issue with CBC-AES is especially problematic, allowing the modification of "secured" programs (e.g. firmware). CTR-AES has acceptable security, but different use cases. Please consider devoting time to supporting XTS-AES specifically:

>According to SP 800-38E, "In the absence of authentication or access control, XTS-AES provides more protection than the other approved confidentiality-only modes against unauthorized manipulation of the encrypted data."[[2]]

[1]: https://en.wikipedia.org/wiki/Disk_encryption_theory#Malleability_attack
[2]: https://en.wikipedia.org/wiki/Disk_encryption_theory#XTS

**Comment by RonEld** [comment]
XTS-AES PR has been raised in https://github.com/ARMmbed/mbedtls/pull/1602

**Comment by RonEld** [comment]
AES-CBC-MAC is essentially supported, because It's AES_CBC, and the last AES block( 16 bytes) is the MAC

**Comment by RonEld** [comment]
What I mean is, you can write in your code a wrapper, that will call our AES CBC encryption with the cipher API, and you copy the last block of the ciphertext to your MAC

**Comment by gilles-peskine-arm** [comment]
Revisiting this in 2023:

> DSA: include SHA1, SHA224 and SHA256 mode.

In 2023, I think I can confidently state that Mbed TLS will never implement DSA.

> Cipher(AES) CTS and XTS mode

[XTS is implemented](https://github.com/Mbed-TLS/mbedtls/pull/1602). CTS isn't, please raise a new issue for CTS if it's still relevant.

> CBC_MAC: include AES_CBC_MAC_NOPAD, AES_CBC_MAC_PKCS5, 
> DES_CBC_MAC_PKCS5, DES3_CBC_MAC_NOPAD and DES3_CBC_MAC_PKCS5 mode.

We do not implement CBC-MAC and do not intend to implement it. It's a strange mode that has a major gotcha: it's only secure if all inputs for a given key have the same size. We prefer to avoid implementing cryptographic primitives with a high risk of misuse. If you really need it, you can build it on top of AES-CBC.

> CCM: Need more interface: starts, update, finish for integrate.

This is available since Mbed TLS 3.1.

----

Everything that was requested here is either available, or not something we intend to add, apart from CTS. If you still want CTS, please open another issue. For the rest, I am closing this issue as partly completed and partly unplanned.
