### ISSUE TITLE
Clarify OpenSSL RSA-PSK situation in compat.sh

### ISSUE THREAD

**Issue by mpg** [Mbed-TLS/mbedtls#1419]
### Description
- Type: Enhancement (tests)
- Priority: Minor

## Enhancement

In `compat.sh` RSA-PSK suites are not tested for interop with OpenSSL (only with GnuTLS) and no comment clearly explains why. If I remember correctly, it was either because I couldn't find the correct invocation of `openssl s_server/s_client` when I added those suites, of because there was a bug in `openssl` that prevented us from using this key exchange from the command line.

Either way, this should be reevaluated: if interop testing for these suites with OpenSSL can be added, we should do it, or if it can't we should record why (and if there is an issue in `openssl` command, report it).

**Justification - why does the library need this feature?**  

We always want more interop testing.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2154

**Comment by mpg** [comment]
Ok, I think I found what the issue was: RSA-PSK is only supported from OpenSSL 1.1.0 (look for `RSA_PSK` in [the ChangeLog](https://www.openssl.org/news/changelog.html#x10) and currently the CI has 1.0.2 as the default OpenSSL version.

**Comment by gilles-peskine-arm** [comment]
With https://github.com/Mbed-TLS/mbedtls/issues/8170 we are removing support for RSA-PSK in the next release of Mbed TLS (Mbed TLS 4.0), so this issue is now only applicable to long-term support branches (2.28, 3.6).

We have not needed to fix this in years, so this is low importance. As it is now also low relevance, I am closing this issue.
