### ISSUE TITLE
Exclude internal APIs from API checking

### ISSUE THREAD

**Issue by Patater** [Mbed-TLS/mbedtls#1626]
### Description
- Type: Enhancement\Feature Request
- Priority: Minor

---------------------------------------------------------------
## Enhancement

**Expected behavior**

Internal APIs should be excluded from API checking (but must still be included in ABI checking).
The "_internal.h" files are considered internal APIs. 

**Actual behavior**

Changes to internal APIs show up as mistakes (false positives), and potentially hide real mistakes in their noise, in our API/ABI compatibility report.

**Comment by daverodgman** [comment]
This is now done

**Comment by gilles-peskine-arm** [comment]
@daverodgman This is only partially moot (rather than done — moot because private headers are no longer under `include`): public headers still contain some private aspects, mainly private fields in structures. I think it's good enough to focus on private fields in structures, and they're still ABI breaks. https://github.com/Mbed-TLS/mbedtls/issues/6592
