### ISSUE TITLE
Build with "-Werror" by default

### ISSUE THREAD

**Issue by Patater** [Mbed-TLS/mbedtls#1710]
Note: This is just a template, so feel free to use/remove the unnecessary things

### Description
- Enhancement
- Priority: Major

## Enhancement\Feature Request

**Justification - why does the library need this feature?**  
We could easily accidentally miss warnings (which are often real bugs) when building with a simple `make`.

**Suggested enhancement**  
The default build should stop when a warning arises (at least with gcc or clang), so that we make sure we don't add warnings.

**Comment by tom-cosgrove-arm** [comment]
Upon further discussion, let's not force everyone to have `-Werror` enabled when building (e.g. there are 4 open PRs as I write this to fix warnings in builds with IAR).

We do have this on in the CI, which seems to be the best level to do it; third parties can add it to the `CFLAGS` they use when building Mbed TLS.

**Comment by gilles-peskine-arm** [comment]
@tom-cosgrove-arm  We've had this conversation several times over the years (including with Jaeden, I think) and concluded, like you, that `Makefile` shouldn't have `-Werror` by default because people use it with all kinds of compilers and we don't know what kinds of warnings they might have. Whereas `CMakeLists.txt` only enables `-Werror` when building with a known compiler (which still runs into the problem of unknown compiler versions, but that's a lot narrower).

I don't know where or whether those conversations were recorded, so it's good that it's written down. Thanks for all the cleanup you're doing on the backlog!
