### ISSUE TITLE
unused variable warning with non-default config in development-psa

### ISSUE THREAD

**Issue by mpg** [Mbed-TLS/mbedtls#2243]
### Description
- Type: Bug
- Priority: Major

## Bug

**mbed TLS build:**  
Version: branch development-psa  
Configuration: enable `MBEDTLS_EXTENDED_MASTER_SECRET` but disable `MBEDTLS_SHA512_C`  
Compiler and options: GCC (probably Clang too)

**Expected behavior**   
Builds without warnings.

**Actual behavior**  
```
/home/manpeg01/src/mbedtls/library/ssl_tls.c:762:33: warning: unused variable 'md_type' [-Wunused-variable]
        mbedtls_md_type_t const md_type = ciphersuite_info->mac;
                                ^
1 warning generated.
```

**Steps to reproduce**  
```
git checkout development-psa
scripts/config.pl unset MBEDTLS_SHA512_C
make lib
```

**Comment by mpg** [comment]
cc @hanno-arm as I believe you're the last person to touch that code.

**Comment by davidhorstmann-arm** [comment]
@mpg as the `development-psa` branch seems to be archived and this doesn't seem to be an issue in `development`, can this be closed?

**Comment by gilles-peskine-arm** [comment]
@davidhorstmann-arm `development-psa` was a feature branch that has been merged into `development`. If this isn't an issue in `development`, it means we've resolved the issue but didn't notice it could be closed. Since `MBEDTLS_SSL_EXTENDED_MASTER_SECRET` is in the default configuration and we test without SHA512 support via `depends.py`, this must be resolved.

**Comment by gilles-peskine-arm** [comment]
I'm closing this issue since we must have resolve it, at the latest, when we merged `development-psa` back into `development`.
