### ISSUE TITLE
API to extract public key from parsed certificate

### ISSUE THREAD

**Issue by RonEld** [Mbed-TLS/mbedtls#2294]
### Description
- Type: Enhancement\Feature Request
- Priority:  Major
Need an API to extract the public key from the certificate

----------------------------------------------------------------
## Enhancement\Feature Request

**Justification - why does the library need this feature?**  
After looking at https://forums.mbed.com/t/mbedtls-pk-context-handling/4104 and https://forums.mbed.com/t/extracting-public-key-from-the-signed-certificate/4162 it is understandable that the certificate public key is needed, whether it is because member is freed when the certificate is freed, or whether there is a need to store the public key.

**Suggested enhancement**  
Add an API that received a certificate, and copies its encapsulated public key member to a `mbedtls_pk_context*` given as parameter.

**Comment by vipulkute-eaton** [comment]
Is this feature / API is available to extract the public key from the certificate? 
I was also looking for API to extract the public key from the DER formatted certificate. If this feature is available can you please share the link here?

**Comment by gilles-peskine-arm** [comment]
@vipulkute-eaton First, in any case, you need to parse the PEM or DER with one of the `mbedtls_x509_crt_parse*` functions. Then you can access the public key directly as `crt->pk`. What you need to keep in mind is that if you free `crt`, this frees `crt->pk`. So if you still need the public key object after that, you need to make a copy.

This issue is for having a direct way to make a copy of the key. Currently there isn't one. There are two indirect ways:
* Export the key and import it (`mbedtls_pk_write_pubkey_der` then `mbedtls_pk_parse_pubkey_der`). Simple and robust, but slightly wasteful.
* You can check the key type, then create another `mbedtls_pk_context` and fill it with `mbedtls_rsa_copy` or `mbedtls_ecp_copy` or `psa_copy_key`. I do not recommend this approach because you need to know the key representation, and this doesn't actually work with RSA_ALT keys.

**Comment by erdgeist** [comment]
Since with Version 3 of mbedtls, the pk member of the mbedtls_x509_crt becomes inaccessible, having an official API to extract the mbedtls_pk_context becomes much more pressing. Any progress here?

**Comment by gilles-peskine-arm** [comment]
@erdgeist Since Mbed TLS 3.1, the `pk` field of `mbedtls_x509_crt` is public.

**Comment by erdgeist** [comment]
Thanks. Does that mean that I now have to precisely guard against version 3.0 when accessing this field?

**Comment by gilles-peskine-arm** [comment]
Generally speaking, you should not use old versions of Mbed TLS: they tend to have unfixed security issues.

If you're sure that the unfixed security issues in Mbed TLS 3.0 don't affect your application, then yes, you can guard against `MBEDTLS_VERSION_MAJOR == 3 && MBEDTLS_VERSION_MINOR == 1`.

**Comment by davidhorstmann-arm** [comment]
Closing as unnecessary - the `pk` field of `mbedtls_x509_crt` is public.
