### ISSUE TITLE
mbedtls_aes_setkey_dec is slower than mbedtls_aes_setkey_enc

### ISSUE THREAD

**Issue by chenkline** [Mbed-TLS/mbedtls#2784]
### Description
- Type: Enhancement Request
- Priority: Minor

---------------------------------------------------------------
## Enhancement Request

**Justification - expect that mbedtls_aes_setkey_dec is fast as mbedtls_aes_setkey_enc**  

** remove the calling to mbedtls_aes_setkey_enc, mbedtls_aes_setkey_dec shoud not depend on mbedtls_aes_setkey_enc **

**Comment by chenkline** [comment]
enc_time1: 1110, dec_time1:3109

**Comment by chenkline** [comment]
mbedtls_aes_init( &aes_ctx );

    t1 = gettick();
    for (i=0; i<times; ++i) {
        mbedtls_aes_setkey_enc( &aes_ctx, aes_key, 256 );
    }
    enc_time1 = gettick() - t1;
    t1 = gettick();
    for (i=0; i<times; ++i) {
        mbedtls_aes_setkey_dec( &aes_ctx, aes_key, 256 );
    }
    dec_time1 = gettick() - t1;
    fprintf_s( stderr, "enc_time1: %u, dec_time1:%u\n", enc_time1, dec_time1 );

**Comment by chenkline** [comment]
# Test code 

    int i = 0;
    int times = 5000000;
    unsigned int t1;
    unsigned int enc_time1,dec_time1;

    mbedtls_aes_context aes_ctx;
    unsigned char aes_key[32]; // aes-256

    // initialize aes_key ........
    //  .....

    mbedtls_aes_init( &aes_ctx );

    t1 = GetTickCount();
    for (i=0; i<times; ++i) {
        mbedtls_aes_setkey_enc( &aes_ctx, aes_key, 256 );
    }
    enc_time1 = GetTickCount() - t1;
    t1 = GetTickCount();
    for (i=0; i<times; ++i) {
        mbedtls_aes_setkey_dec( &aes_ctx, aes_key, 256 );
    }
    dec_time1 = GetTickCount() - t1;

    mbedtls_aes_free( &aes_ctx );

    fprintf_s( stderr, "enc_time1: %u, dec_time1:%u\n", enc_time1, dec_time1 );

# output
enc_time1: 1110, dec_time1:3109

**Comment by RonEld** [comment]
Hi @chenkline 
Thank you for your comment and interest in Mbed TLS.
Note that the two operations are not equivalent, as the decryption requires inversion of the key schedule, hence it takes longer.
As you can see from [this blog](https://tls.mbed.org/tech-updates/blog/working-towards-mbed-tls-3), Mbed TLS is migrating to psa crypto, which `mbed-crypto` implements it. 
We will take into considerations ways of improving performance, however setting the key happens once in a cipher session, so, as you mentioned, the priority for this is low.

**Comment by daverodgman** [comment]
Given that it's not common to call `mbedtls_aes_setkey_dec` very frequently, the minor performance difference observed here doesn't seem worth addressing.

**Comment by gilles-peskine-arm** [comment]
Modern modes (CCM, GCM) only use the encryption key schedule. `setkey_dec` is only used by CBC (which is somewhat deprecated since it is not authenticated, and it is tricky to build an authenticated mode on top of it) and XTS (which is specifically targeted at sector-based disk encryption, which is not a common use case for Mbed TLS). So optimizing `setkey_dec` is not a priority for Mbed TLS.

Optimizing `setkey_dec` to directly set up the decryption key schedule, rather than call `setkey_enc` then do inversion, would require extra code size to improve performance. Mbed TLS is primarily targeted at constrainted platforms where code size is the most important constraint. So this is not something we'd be likely to consider in any case.
