### ISSUE TITLE
TLS handshake fails with the BG96 Cellular Interface but works with Ethernet on K64F

### ISSUE THREAD

**Issue by sudhirkshirsagar** [Mbed-TLS/mbedtls#2805]
### Description
- Type: Bug 
- Priority: Blocker

---------------------------------------------------------------
## Bug

**OS**  
Mbed OS

**mbed TLS build:**  
Version: b005bf21337e6ffe5393671b92066c3b09c5204b
OS version: 5.13
Configuration: please attach config.h file where possible  
Compiler and options (if you used a pre-built binary, please indicate how you obtained it):  
Mbed Studio 0.5.3 ARM6
Additional environment information:  

**Peer device TLS stack and version**  
Azure IoT Hub
Version:  

**Expected behavior**   
Handshake succeeds 
**Actual behavior**  
Handshake fails
**Steps to reproduce**  
Run https://os.mbed.com/users/coisme/code/Mbed-to-Azure-IoT-Hub/ with a BG96 Cellular Interface
The message length is different than the handshake length
[MBED fails during handshake while using Cellular.txt](https://github.com/ARMmbed/mbedtls/files/3537743/MBED.fails.during.handshake.while.using.Cellular.txt)

----------------------------------------------------------------
## Enhancement\Feature Request

**Justification - why does the library need this feature?**  

**Suggested enhancement**  

-----------------------------------------------------------------

## Question

**Please first check for answers in the [Mbed TLS knowledge Base](https://tls.mbed.org/kb), and preferably file an issue in the [Mbed TLS support forum](https://forums.mbed.com/c/mbed-tls)**

**Comment by RonEld** [comment]
Hi @sudhirkshirsagar 
The error you are receiving is because of a failure in parsing the certificate received from the server.

As you can see from the logs, your client send the fatal alert message:
~~~
send alert level=2 message=42
~~~
42 means MBEDTLS_SSL_ALERT_MSG_BAD_CERT
In addition, the Mbed TLS error returned in your client is:
~~~
[TLSW]: mbedtls_ssl_handshake() failed: -0x3d62 (-15714): PK - Invalid key tag or value : ASN1 - ASN1 tag was of an unexpected value
~~~
This is usually due to configuration issue.

Is it possible that in Ethernet connection the received certificate is different?

If the certificates are same, it is possible that the certificate is a big RSA signed certificate, which can be sent in Ethernet, but in BG96, it is cut in the middle, causing the parsing error

**Comment by sudhirkshirsagar** [comment]
I just found out that it works with a prior release of
mbed-os 7e7f4f561bcdf84e50c947ebd2d5a14437f36f1c but not with the latest.
Unfortunately that means I will not get the bug fixes in BG96 driver after
that release.
I think the entire cert is received but mbed tls does not handle the use
case where the message length is different than the expected handshake
length. You can see the zero padded message. There are also comments in the
TLS code that talk about a related issue (fragmentation) not being handled
correctly.

**Comment by daverodgman** [comment]
Closing - this doesn't appear to be an Mbed TLS bug.
