### ISSUE TITLE
Allow both the alternative and the native implementations at the same time with a switch inside the SSL context

### ISSUE THREAD

**Issue by TrinityTonic** [Mbed-TLS/mbedtls#3045]
### Description
- Type: Enhancement\Feature Request

----------------------------------------------------------------
## Enhancement\Feature Request

Allow both the alternative implementation (e.g. using a hardware accelerator) and the native mbedtls implementation for cryptographic function at the same time. Distinction is made per context for example per SSL context.

Example SSL context 1 uses the alternative implementation for ECC and the native mbedtls implementation for AES and HASH.
Example SSL context 2 uses the alternative implementation for ECC AND the alternative implementation for AES and HASH.

**Justification - why does the library need this feature?**  
mbedTLS might be used as the cryptographic and SSL library on some embedded components that have to meet hard real-time requirements. Those systems must guarantee that certain actions are finished within a pre-defined time interval. However if all low-priority and high-priority components used the same cryptographic acclerator, this hard real-time requirement could not be guaranteed.

Use-Case:
mbedtls used on an embedded system that comes with a HTTPS webserver and real-time IO-communication using TLS. In this case the low-priority webserver could affect the real-time IO-communication if the same cryptographic core was used for both.

**Comment by gilles-peskine-arm** [comment]
The first hurdle is that the library isn't designed to let you even build both the native implementation and the alternative implementation. If you define `MBEDTLS_xxx_ALT`, the native implementation isn't compiled. Calling `mbedtls_aes_encrypt()` either calls the implementation in `aes.c` or the alternative one, whichever is included at compile time.

You can work around this at the cost of some complexity in your build environment: define (for example) `MBEDTLS_AES_ALT`, make a copy of `aes.c` with the functions renamed to something like `mbedtls_aes_encrypt_native`, and in your own implementation of `mbedtls_aes_encrypt`, make a runtime decision whether to call `mbedtls_aes_encrypt_native` or call into the hardware. Instead of duplicating code, you can use preprocessor tricks to rename the function when compiling `aes.c` only (and _not_ when compiling the other Mbed TLS files). (In the long term, we'll switch to the PSA crypto API, which will support this fallback in a sane way.)

Assuming that you have both a software and a hardware implementation of AES in the same binary, the next hurdle is to decide which one to call. There's only a single `mbedtls_aes_encrypt` function, and it's its job to decide which implementation to call. I don't know how the SSL layer could pass this information. An extra parameter to `mbedtls_aes_encrypt` just for this rare use case? An extra function when setting up the context?

Can the AES layer find this information through some other means, for example a thread-global variable?

The SSL code has some limited ability to bypass the crypto code and call custom functions:

* There's `MBEDTLS_SSL_HW_RECORD_ACCEL`, which takes over the symmetric encryption. But it doesn't just do that, it also takes over some of the TLS message formatting. Also it's largely undocumented, [fully untested](https://github.com/ARMmbed/mbedtls/issues/2026), and we're likely to remove it in the future.
* There's a feature to [call an external processor for server-side private key operations](https://tls.mbed.org/kb/how-to/ssl_async). You can use it to call crypto differently, but only for the private key operations. I mention it because it can help (for the asymmetric crypto only) in some similar use cases, but I don't think it'll help you.

**Comment by gilles-peskine-arm** [comment]
(I'm labeling this “open for community contribution” because I don't think we're likely to work on this any time soon. This is a personal judgement, not an official decision. If you or someone else feels like contributing the code, we do welcome contributions, but we'd need to have some discussions about the design first, as this seems to have a fairly large impact on several interfaces.)

**Comment by aditya-deshpande-arm** [comment]
We are not planning to do any further work on the ALT interface. Perhaps the PSA Driver interface could be used to achieve this?
