### ISSUE TITLE
Wrong parameter names in Doxygen comments

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#4209]
There are many places in Doxygen function documentation that use `\p` followed by something that isn't a parameter name. These may be misspellings, copypasta, references to things that aren't parameters, references to parameters passed to another function, etc.

We run `clang -Wdocumentation` (in cmake builds), which detects Doxygen comments that contain a `\param` directive that doesn't match the parameter names in the C code. So the CI validates `\param` directives. But it doesn't validate `\p`.

I used the following “one-liner” to detect places where a `\p` doesn't correspond to a `\param` in the same comment.
```
perl -w -ne 'if (eof) { $. = 0; } if (m!^/\*\*!) { $in_doc = 1; %param = (); %p = (); } if (m!\*/!) { foreach $name (keys %p) { if (!$param{$name}) { foreach $line (@{$p{$name}}) { print "$ARGV:$line: $name\n" } } } $in_doc = 0; } if ($in_doc) { if (/\\param(?: *\[[^\[\]]*\])? +(\w+)/) { $param{$1} = 1; } foreach (/\\p +\*?(\w+)/) { push @{$p{$1}}, $.; } }' include/*/*.h
```

**Comment by AndrzejKurek** [comment]
According to the doxygen documentation, `\c` and `\p` are equivalent in regards to the effect, but the suggestion for usage is different:

> \p - You can use this command to refer to member function parameters in the running text.

> \c -  Use this to refer to a word of code. 

As I understand, we aim to solely use \p for parameters, and \c for other variables?
Do we ever want to use "#"? This will, for example, link to struct members when describing a given struct, and I believe that we should use it in such context (instead of \p). We can also link to other variables / members this way in places that currently use \c.
Source: https://www.doxygen.nl/manual/autolink.html

**Comment by gilles-peskine-arm** [comment]
We already use `#` to link to macros. If there are more opportunities to link things (e.g. structure fields), it would be good to link them as well, but that's out of scope here.
