### ISSUE TITLE
ability to generate certificates with SubjectAltName

### ISSUE THREAD

**Issue by majojoe** [Mbed-TLS/mbedtls#448]
It would be nice to have the ability to generate certificates with the Fields SubjectAltName and ExtendedKeyUsage. This is needed for e.g. OPC-UA.
Until now it is not possible to create certificates for that purpose and openSSL is needed for that to work.
Think it cannot be to difficult to add those extensions since parsing is possible...

Thanks in advance.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-692

**Comment by NWilson** [comment]
The mbedTLS people have a big backlog of PRs at the moment, which I'm
waiting to clear before I submit any more patches, but one of my open PRs
provides ExtendedKeyUsage support: see
https://github.com/ARMmbed/mbedtls/pull/277.

**Comment by sbutcher-arm** [comment]
Hi @majojoe 

Both of these items are already on our internal list of features we want to support, and as @NWilson has said, we have a pending PR for ExtendedKeyUsage which we plan to use.

I'll leave this open as a feature request until both items are satisfied.

**Comment by SwooshyCueb** [comment]
The SAN field would be super nice, as I think it's the only thing preventing us from using mbedtls to generate letsencrypt-compatible CSRs. Glad to hear it's already on the internal TODO

**Comment by daverodgman** [comment]
In #5839 the reporter comments that ExtendedKeyUsage is required by some cloud services (like Azure IoT Hub) in order to sign in.

**Comment by josesimoes** [comment]
👍🏻 for the ability to add extended key usage for cert generation!

I'm on a quest to use Mbed TLS to generate certs for Azure in order to replace Openssl (which is aligned with this [comment](https://github.com/Mbed-TLS/mbedtls/pull/277#issue-105651714) currently the lack of support for writing extended key usage this is the only thing blocking the use of Mbed TLS to generated certificates for Azure instead of Openssl (which is a pain to use and get installed on Windows).

**Comment by tom-cosgrove-arm** [comment]
#6121 added a way to set extended key usages

**Comment by Neustradamus** [comment]
To follow
