### ISSUE TITLE
Support AuthorityKeyId and SubjectKeyId extensions in X.509

### ISSUE THREAD

**Issue by bvbasavaraju** [Mbed-TLS/mbedtls#4666]
### Suggested enhancement
Hello Sir/Madam,

There are some additional extensions which are required to be exposed to the user. Authority Key Id and Subject Key Id.

And while validating the SAN, IP address and URI also needed to be verified.

### Justification

Mbed TLS needs this because, when X509 V3 certificate is created, based on requirement app layer may want to expose additional extensions. For Authority Key Id and Subject Key Id it is missing. And SAN can have IP Address and URI as well. So, while verifying the certificate, SAN verification may fail. So, these features are kind of very important.

**Comment by bvbasavaraju** [comment]
When I downloaded and used the library, I had to modify for above mentioned features/requests. I would like to contribute back if it is OK. Can I please contribute?

**Comment by gilles-peskine-arm** [comment]
Thank you for volunteering! There is already ongoing work to add support for these extensions: https://github.com/ARMmbed/mbedtls/pull/4161 . Rather than write your own, I think it would be easier to finish the ongoing work. If you'd like to help @toth92g, please get in contact with them.

Also, in general, our bottleneck for contributions is the time to review them. So you can help by reviewing pull requests.

**Comment by bvbasavaraju** [comment]
Sure. It is my pleasure to be a part of it. sure. I will review.

**Comment by bvbasavaraju** [comment]
I have reviewed. I had few comments. I hope developer will get an opportunity to look into it.
