### ISSUE TITLE
required symbols not defined in ecdh_curve25519.c example program.

### ISSUE THREAD

**Issue by catmandx** [Mbed-TLS/mbedtls#4901]
### Summary
The example program ecdh_curve25519 is not running while others run fine.

### System information

Mbed TLS version (number or commit id): v3.0.0
Operating system and version: Kali Linux 2021.2
Configuration (if not default, please attach `mbedtls_config.h`): Default
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): gnu make
Additional environment information: none

### Actual behavior
The program complains MBEDTLS_ECDH_C and/or MBEDTLS_ECDH_LEGACY_CONTEXT and/or MBEDTLS_ECP_DP_CURVE25519_ENABLED and/or MBEDTLS_ENTROPY_C and/or MBEDTLS_CTR_DRBG_C not defined

### Steps to reproduce
1. Download mbedtls, extract
2. Run make
3. Run program/pkey/ecdh_curve25519

**Comment by tom-daubney-arm** [comment]
Hi,
Thanks for reporting a potential issue.

Right now I am unable to reproduce this error, following the steps that have been given. I will check with some colleagues and write back with a more proper response.

Thanks,
Tom

**Comment by tom-daubney-arm** [comment]
I see the issue now and have confirmed with a colleague. Thanks for reporting it!

**Comment by AdityaHPatwardhan** [comment]
Hi @mpg any update on this issue ?

**Comment by mpg** [comment]
Sorry, this hasn't progress yet. However, as you can see in the side bar, this is in the "Mbed TLS 3.2" EPIC, which means we are planning to fix this in the next release.

**Comment by tom-daubney-arm** [comment]
Hi, I just wanted to offer an update about a workaround that can be used to get the program to run in version 3.0. The issue is that the `MBEDTLS_ECDH_LEGACY_CONTEXT` option has been largely removed in 3.0 and this program depends on it being defined. In 3.0 `MBEDTLS_ECDH_LEGACY_CONTEXT` can actually be defined by defining `MBEDTLS_ECP_RESTARTABLE`. Below are some steps to get the program running from a fresh checkout of v3.1.0:

Firstly in `programs/pkey/ecdh_curve25519.c` on line 33 you need to remove the `!defined(MBEDTLS_ECDH_LEGACY_CONTEXT)` condition from the `#if` statement.

Then at the terminal (from the mbedtls repository root folder) run:

`scripts/config.py set MBEDTLS_ECP_RESTARTABLE` - this will turn on the `MBEDTLS_ECP_RESTARTABLE` config option.

`make -j`

`programs/pkey/ecdh_curve25519`

You should see the program running at this point. This is obviously a bit of a dirty hack and the full solution is coming however hopefully this is useful for some.
