### ISSUE TITLE
mbedtls_ssl_context private fields getters

### ISSUE THREAD

**Issue by jaudiger** [Mbed-TLS/mbedtls#5184]
### Suggested enhancement

I would like to have access to private fields of `mbedtls_ssl_context` through getters. Right now, I'm using macro `MBEDTLS_PRIVATE()`.

### Justification

I have a use case where I need to handle the DTLS handshaking and to handle the serialization of the security session with Connection ID + session resumption.

For now, I just need to access the private fields:

- `id_len`
- `own_cid`
- `own_cid_len`
- `state` [edit: see #4383]

**Comment by neoxic** [comment]
Please also note that the documentation on `mbedtls_ssl_handshake_step()` explicitly says:

> The state of the context (ssl->state) will be at the next state after this function returns 0. Do not call this function if state is MBEDTLS_SSL_HANDSHAKE_OVER.

which assumes `ssl->state` is public when it is not. Either `ssl->state` must be made public or a getter must be provided (and the manual fixed).

**Comment by mpg** [comment]
Thanks for your report! Regarding the `state` field, your point about `mbedtls_ssl_handshake_step()` being unusable without it (or a replacement) is solid, but the issue is already tracked in #4383, so I suggest we keep this ticket focused on the CID-related fields, who AFAIK were not covered by another ticket.

Can you clarify if you need read-only access to these fields, or also write access, and give us a bit more background about your use case?

**Comment by jaudiger** [comment]
Hi @mpg,

Sure, a bit as https://github.com/ARMmbed/mbedtls/issues/5183, I need to read those variables when I serialize/deserialize a security session of a peer. The session is affected with metadata that comes from those private variables.

**Comment by paul-elliott-arm** [comment]
Hi, @jaudiger I presume from what you are saying here, this means you want the session id_len?

**Comment by paul-elliott-arm** [comment]
Pushed #5638 to cover the own CID accessors - @jaudiger, I am still confused by your request for id_len here.

**Comment by paul-elliott-arm** [comment]
Brilliant - thankyou for your feedback @jaudiger!

**Comment by mpg** [comment]
Hi @jaudiger - while reviewing #5638 I realised I'm no longer so sure I understand what problem exactly we are trying to solve, in particular I'm now under the impression that the current API is actually functionally complete (though perhaps an extension could be useful as a convenience / memory optimisation).

What triggered by change of mind is reading the documentation that says "Get information about our request for usage" - this information should already be available to the application, because it originated from the application: it's the arguments that were passed to `mbedtls_ssl_set_cid()`. So, it seems to me that the application could just remember what it passed to that function, and then wouldn't _need_ `mbedtls_ssl_get_own_cid()` (as it is in the current version of #5638). (Though that function perhaps would be convenient, and would avoid storing two copies of our own cid: one in the application, one in the context.)

Alternatively, perhaps what you want to know is what was actually negociated - in that case, I think all the information is already available as well - our own cid can be saved when calling `mbedtls_ssl_set_cid()` (as observed above), and `mbedtls_ssl_get_peer_cid()` tells if use of CID was successfully negociated or not - based on that, you can infer the effective "own cid" which is either an empty string (if not successfully negociated) or whatever was passed to `mbedtls_ssl_set_cid()`.

So, it seems to me that either way, the information is already available and the new function would mostly be a convenience to avoid storing the same info twice. Is that correct? (Not trying to push back on adding that function, just trying to make sure we have a shared understanding of the problem.)

Also, what would be most useful to you: the new function returning what was requested, or what was negociated?

**Comment by jaudiger** [comment]
Hi @mpg,

That's exactly what I try to avoid today by accessing the internal structure. You're right the Connection ID sent by the Server to the Client comes from the server's application. Since, this information is stored in mbed TLS, I do not want to duplicate it in my application.

So, I just want an API to get back the connection ID given to mbed TLS through `mbedtls_ssl_set_cid()`.

**Comment by mpg** [comment]
Ok, thanks for your response, so I think the current version of #5638 should work for you.

**Comment by jaudiger** [comment]
Yes, it'll suit my needs !
