### ISSUE TITLE
Study: build TLS without Cipher

### ISSUE THREAD

**Issue by mpg** [Mbed-TLS/mbedtls#5211]
After #5207, when `USE_PSA_CRYPTO` is enabled, the TLS library should no longer have any direct dependency on `MBEDTLS_CIPHER_C`, as all crypto operations are now done via PSA. So, ideally the dependency from TLS on `MBEDTLS_CIPHER_C` in `check_config.h` should be replaced with a dependency on `MBEDTLS_USE_PSA_CRYPTO || MBEDTLS_CIPHER_C` and we would be able to build TLS without Cipher.

This task is to study what needs to be done in order to achieve that result.

Expected result: a series of estimated tasks.

**Comment by mpg** [comment]
Right after #5434, I tried building with the default config plus `MBEDTLS_USE_PSA_CRYPTO` minus `MBEDTLS_CIPHER_C` (minus `NIST_KW_C` which depends on it), with the modified dependency in `check_config.h`. This shows two kind of issues:

1. I seems we never tried to build without `CIPHER_C`, as a number of modules have undeclared (meaning: not checked in `check_config.h`) dependencies on it: `ccm.c`, `cmac.c`, `gcm.c`, `pkcs12.c`, `pkcs5.c`, `psa_crypto_cipher.c`, `psa_crypto_mac.c` - these should be documented.
2. So far, the software implementation of ciphers (and some macs, I assume CMAC) in PSA still depends on `cipher.c`, and that dependency should be remove before PSA can be used as a replacement for `cipher.c`.

**Comment by gilles-peskine-arm** [comment]
> the software implementation of ciphers (and some macs, I assume CMAC) in PSA still depends on cipher.c

PSA calls `mbedtls_cipher_xxx` functions for the following purposes:
* In `psa_aead_setup`, just `mbedtls_cipher_info_from_psa` to decode the cipher ID for AEAD algorithms based on block ciphers, to pass it to `mbedtls_gcm_setkey` or `mbedtls_ccm_setkey`.
* Indirectly via the CCM and GCM modules, which implement those AEAD algorithms on top of ECB done via the cipher API.
* For all cipher operations.
* For CMAC, both directly since the API relies on `mbedtls_cipher_cmac_xxx` to perform CMAC opertaions, and indirectly because the CMAC module works  on top of ECB done via the cipher API.

Building PSA without `cipher.c` requires not only removing the indirections in the PSA code, but also rewriting the lower-level modules not to depend on cipher for ECB.

**Comment by mpg** [comment]
Yes, building TLS without `cipher.c` (without drivers) would require much more work than I realised before. The direct dependencies were the easy part, the indirect dependencies are quite deep.

**Comment by mpg** [comment]
Actually, I've been thinking: I think we already have tests (all the `test_psa_crypto_config_accel_xxx` components in `all.sh`) for building a drivers library `libtestdriver1.a` based on our implementation of some primitive X, then building the library (and programs and tests) in a configuration without X by linking to that. We could probably do something similar here - build every primitive that depends on `CIPHER_C` in `libtestdriver1.a` and then build the rest of the library including TLS without `CIPHER_C`, linking to the testdriver library to get an implementation of them via the PSA API.

I'm not sure how hard that extension would be, as I'm not very familiar with how the `libtestdriver1.a` mechanism works. @ronald-cron-arm (since according to git blame you did a lot in this area) do you have thoughts to share?

**Comment by gilles-peskine-arm** [comment]
> build every primitive that depends on CIPHER_C in libtestdriver1.a and then build the rest of the library including TLS without CIPHER_C, linking to the testdriver library to get an implementation of them via the PSA API

That does indeed sound like an evolution of `component_test_psa_crypto_config_accel_cipher`: all cipher mechanisms are provided through `psa_xxx`, and not through `mbedtls_xxx`. The existing test component keeps `MBEDTLS_CIPHER_C` because it's also used for AEAD and because of its existing uses in TLS. So I think you want to make a test component where all ciphers (authenticated or not, and also CMAC) are disabled in `mbedtls_xxx`, and there are PSA drivers for those mechanisms.

**Comment by mpg** [comment]
Actually there's another class of issues with getting a usable build of TLS without all ciphers as PSA drivers and no `CIPHER_C`: currently the dependencies are expressed as `#if defined(MBEDTLS_GCM_C)` so if we did a build with AES-GCM provided by a driver (with our implementation compiled out), currently TLS would think that no AES-GCM ciphersuites are available.

This can be fixed by changing dependencies from `MBEDTLS_xxx` to `PSA_WANT_xxx` in all the right places (perhaps with an extra abstraction layer to account for whether `USE_PSA_CRYPTO` is defined or not). So, definitely not a blocker in the long term, but clearly an extra chunk of work to be planned (and perhaps have design discussions about).

**Comment by mpg** [comment]
Note: as of today's development, libmbedtls no longer has any runtime dependency on any `mbedtls_cipher` symbol when `MBEDTLS_USE_PSA_CRYPTO` is enabled:
```sh
scripts/config.py full
docs/architecture/psa-migration/syms.sh full
egrep 'mbedtls_cipher' full-tls-external
```
has an empty output.

**Comment by mpg** [comment]
Tasks have been created.
