### ISSUE TITLE
Linking External psa_crypto_XXX.c implementation

### ISSUE THREAD

**Issue by zaya-mc** [Mbed-TLS/mbedtls#5288]
### Suggested enhancement
At the moment, if we enable PSA_CRYPTO_API, the build system compiles and links the psa_crypto_XXX.c files. If we need to use an external Secure Element, we need to implement the PSA Driver Interface, but it seems it is still in progress, and it does not support all the features yet. 
For example, psa_crypto.c does not call opeque_import_key() to import keys into the Secure Element. 

We have a fully implemented PSA Crypto API implemented for a specific secure element that passes all PSA Tests, and we would like to link our psa_crypt.c, instead of the psa_crypto.c in mbedtls, but mbedtls build and mbedtls tests statically builds it. 

So, is there a way to link an external psa_crypto.c during build and tests? Otherwise, could we have a flag to exclude the mbedtls psa_crypto implementations?

Thanks

**Comment by gilles-peskine-arm** [comment]
In the medium to long term, we intend to deprecate classic crypto APIs (`mbedtls_sha256_xxx`, `mbedtls_cipher_xxx`, etc.) and to let the interfaces of the corresponding low-level modules to better match the `psa_xxx` APIs. These will be internal interfaces and we do not want to be constrained by backward compatibility there. So we do not intend to support mixing Mbed TLS's implementations of cryptographic primitives with an alternative implementation of the keystore and dispatch interface.

In the medium to long term, we do intend to support using pk, x509 and ssl interfaces on top of any PSA crypto API implementation, not just the one in Mbed TLS. So at that point, it will be possible. A lot of the pk/x509/ssl code is coupled to the our own implementation, and it will take some time to decouple them.

We'll have a full implementation of the driver interface long before that.

So I'm afraid I don't see a way we could help you here: I can only think of solutions that are incompatible with our long-term goals or solutions that will take time.

We are open to requests to prioritize certain parts of the driver interface, or certain aspects of support for alternative implementations of the whole crypto subsystem in pk/x509/tls, especially if you're willing to contribute them as pull requests.

**Comment by gilles-peskine-arm** [comment]
> For example, psa_crypto.c does not call opeque_import_key() to import keys into the Secure Element.

Er, yes, it does. That's basically the first thing we implemented, since we can't do any useful testing without it. Could you clarify the problem you're running into?

There are definitely major parts of the driver interface that are missing, and you have to write the driver wrapper code by hand (work on driver wrapper generation is [just starting](https://github.com/ARMmbed/mbedtls/pull/5193)), but opaque import _is_ present.

**Comment by zaya-mc** [comment]
Thank you for the details @gilles-peskine-arm 

We are trying to work with a "stable" release, and we are using the mbedtls v3.00 tag in the master branch, so We don't see that psa_driver_wrapper_import_key() calls opaque_import_key, it just calls transperant_import_key()
https://github.com/ARMmbed/mbedtls/blob/development/library/psa_crypto_driver_wrappers.c#:~:text=psa_driver_wrapper_import_key

But we saw that it is called in the development branch. So, is the development branch stable enough to use in commercial project?

Or, could you recommend a release or tag to use?

**Comment by gilles-peskine-arm** [comment]
We're actively working on the driver interface, so if you use it, I recommend that you use a very recent branch. We're planning to release 3.1 in December anyway, so if you start integrating with the `development` branch right now, it'll only be a small diff to update to 3.1.

Another reason to use development and not 3.0 is that 3.0 can be hard to use for some things because it makes structure fields private and doesn't yet have accessors for many commonly used fields.

If you want a stable branch, you can use `development_2.x` branch, which will become the 2.28 release (at the same time as 3.1). 2.28 will be a long-time support version, so only use this if it has all the features that you need. We'll keep improving the driver interface in development to be released as 3.1, 3.2, etc., but whatever is in 2.28 will be frozen.

**Comment by zaya-mc** [comment]
Thank you @gilles-peskine-arm, let us have a look at the development branch and see any conflict between interfaces (PSA API, PSA Arch Tests etc)

If I go back to the original question;

For the PSA Compliance,  an environment should implement PSA API, and PSA API should be run stand-alone and PSA Arch Tests should be run on the specific PSA API Implementation, so there is no dependency with mbedTLS.

Just for the TLS operations, we would like to use mbedTLS that makes use of PSA API.

But herein, mbedTLS forces us to use PSA Driver Interface.

**In our case, we implemented PSA API as a stand-alone solution, we pass all PSA Arch Tests, we are PSA Functional API Certified, and you are saying we cannot use our PSA Functional API Certified Implementation with mbedTLS even mbedTLS makes use of PSA API, we have to implement another API to work with mbedTLS.** 

If there would be another abstraction in mbedTLS, it would solve the problem.
- In the mbedTLS build system, we could include psa_crypto_XXX.c source files if a FLAG is enabled instead of statically including them.
- Or all functions in the psa_crypto_XXX.c files could be implemented as __WEAK function. In this way, even we build mbedTLS as a library, the third party could link its customer PSA API Implementation.

**Comment by gilles-peskine-arm** [comment]
> we cannot use our PSA Functional API Certified Implementation with mbedTLS even mbedTLS makes use of PSA API, we have to implement another API to work with mbedTLS.

Yes, because the X.509/TLS parts of Mbed TLS are not yet based on pure PSA crypto. With `MBEDTLS_USE_PSA_CRYPTO`, some cryptograpic operations use the PSA API, for example long-term signature keys, but other operations still use the classic mbedtls_ API. In the coming months, we'll expand the parts that can make use of PSA — see our [roadmap](https://developer.trustedfirmware.org/w/mbed-tls/roadmap/). When that's done, it'll be possible to use PSA drivers for all cryptographic operations in X.509/TLS, but still not possible to use an alternative implementation of the whole cryptography subsystem. That's because X.509/TLS rely on shared features such as ASN.1 parsing which are currently part of the crypto library in Mbed TLS. Untangling this is tentatively planned for the future, at the same time or after “Separate repository from Mbed TLS” in the roadmap.

**Comment by zaya-mc** [comment]
@gilles-peskine-arm yes, we are aware of that mbedTLS is not fully compliant with PSA API and calls a subset of the PSA API. 
That's totally fine.

Just we want to link our fully-implemented PSA Certification-Ready psa_crypo_xxx.c source file, instead of the mbedTLS psa_crypto.c  even mbedTLS does not use all crypto functionality for X.509/TLS yet.

Let us link our implementation, and If mbedTLS fully supports PSA API in the future, our customers will then use our implementation more efficiently.

`make -C library`

As I said, if add a flag to exclude mbedtls psa implementation, or implement psa API using weak functions would solve this problem.

**Comment by gilles-peskine-arm** [comment]
Re-triaging this — as I wrote above, we eventually aim to support linking libmbedx509 and libmbedtls with an implementation of PSA crypto other than libmbedcrypto. But this is a long-term goal, and we don't have an easy short-term solution. So I'm closing this issue, not as “won't fix”, but as “won't fix in the short term”. This is tracked at the roadmap level rather than through GitHub issues.
