### ISSUE TITLE
Fix undeclared dependencies: MD in crypto

### ISSUE THREAD

**Issue by mpg** [Mbed-TLS/mbedtls#5715]
Several parts of the crypto library use the MD module; some have properly declared is as a dependency (documented in `mbedtls_config.h`, enforced in `check_config.h`, for example PKCS5), others don't (documentation or check missing, or both, for example `MBEDTLS_PKCS1_V21`). Similar considerations apply to test functions and test cases.

This task is to rectify the situation and make sure all existing dependencies are documented and checked. As a result:

- [x] a user should be a able to disable `MBEDTLS_MD_C` and everything that's documented as depending on it (recursively), and get a successful build of crypto
- [x] we should have a component in `all.sh` with a config based on `crypto_full` but with `MBEDTLS_MD_C` (and everything that depends on it, recursively) disabled and where `make test` passes. (`ssl-opt.sh` and `compat.sh` are irrelevant because TLS depends on `MD_C` so far)

Since this is a bug fix, it will need backporting to 2.28 as well.

Context: this is a first step towards #5209 and #5210 (see discussions below and in https://github.com/Mbed-TLS/mbedtls/pull/5783 too)
Related: #5716

**Comment by mprse** [comment]
> Several parts of the library use the Cipher module;

I guess that this should be MD module?

**Comment by mpg** [comment]
Yes, bad copy-paste-edit, sorry.

**Comment by gilles-peskine-arm** [comment]
`MBEDTLS_MD_C` is used in so many places that there are only two realistic ways to build Mbed TLS without it:

1. Only including a few symmetric crypto module (e.g. AES, cipher, CCM and nothing else).
2. X.509 and TLS with `MBEDTLS_USE_PSA_CRYPTO`, and all asymmetric crypto and hashes implemtented via PSA accelerator drivers (cipher/AEAD can come from PSA drivers or be built in).

In case 1, spurious dependencies on MD are unlikely. If there are any, it's a long-standing problem, so if anyone cared, they would probably have reported it anyway.

Case 2 is the one we need to work on. It's a new problem because until recently, there were no PSA drivers so no way to make a case-2 build — anything using asymmetric crypto or TLS with PSK would need `MBEDTLS_MD_C` anyway.

We have a framework for testing with drivers: see `component_test_psa_crypto_config_accel_*` in `all.sh`. But it's somewhat hard to use. I think we should do https://github.com/Mbed-TLS/mbedtls/issues/5655 before we add another accel build.

The case of `MBEDTLS_CIPHER_C` in #5716 is similar.

**Comment by mprse** [comment]
Thanks @gilles-peskine-arm for shedding some light on the issue. Looking at the realistic ways to achieve successful build without `MBEDTLS_MD_C` it confirms that most of the features is related and need to be disabled, but I think the goal here is to find and document/check all dependencies. 
So I think that starting from full config is correct approach?

**Comment by mpg** [comment]
What I had in mind was what Gilles calls case 1.

> In case 1, spurious dependencies on MD are unlikely. If there are any, it's a long-standing problem, so if anyone cared, they would probably have reported it anyway.

Agreed, but in my mind it was mostly for our benefit: having an exact list of everything that currently depends on `MD_C`, so that we can use that to plan further steps. (For example, until recently I wouldn't have though about RSA when asked about things that depend on MD.)

So, the purpose is just information gathering, only with a result that's checked programmatically. Though perhaps that wasn't a good idea, feel free to suggest something better.

> So I think that starting from full config is correct approach?

I think so, yes.

**Comment by gilles-peskine-arm** [comment]
> What I had in mind was what Gilles calls case 1.

>> So I think that starting from full config is correct approach?
>
> I think so, yes.

Without `MBEDTLS_MD_C` or PSA hash accelerator drivers, you can't do any part of X.509 or TLS. So start from `crypto_full`, since you can't do anything outside it.

**Comment by mprse** [comment]
Thanks guys.
These dependencies looked like a black magic at the begging, but now I think I'm close to the solution. Maybe later today or tomorrow I will create a PR so we can continue for there.

**Comment by gilles-peskine-arm** [comment]
From memory: in crypto, hashes (with the md layer except when using PSA drivers) are used in HMAC_DRBG, HKDF, RSA (except PKCS1v1.5 encryption but you can't build the library with only that part of RSA), and deterministic ECDSA. So without `MBEDTLS_MD_C`, you can have the individual hash algorithms, entropy (which uses a hash but bypasses the generic md layer), all cipher-related stuff, DHM, ECDSA without the deterministic part, and the generic PSA stuff.

I don't think this results in a useful configuration, so I don't think case 1 is worth pursuing. (Unlike #5716, because a build without ciphers that only uses crypto for authentication and random generation is useful.)

**Comment by mprse** [comment]
Created work-in-progress PR https://github.com/Mbed-TLS/mbedtls/pull/5783.

**Comment by gilles-peskine-arm** [comment]
Actually, apologies, earlier I misremembered something. The PSA crypto implementation is fully independent from the MD module for hash, HMAC and hash-based KDF. So with `MBEDTLS_USE_PSA_CRYPTO`, I think you can do X.509 and TLS. Only with PSK and with ECDH+ECDSA key exchanges, since (unless using drivers) RSA needs hashes (even for encryption, because PKCS#1v1.5 is all or nothing, and “all” includes PKCS#1v1.5 signature padding which uses MD).

And so case 1 is meaningful with `MBEDTLS_USE_PSA_CRYPTO`.

**Comment by mpg** [comment]
> And so case 1 is meaningful with `MBEDTLS_USE_PSA_CRYPTO`.

Good point. However, I'd consider this beyond the scope of this task. The purpose of this task is really information gathering, and checking that information in a programmatic manner to make sure it's correct, not for the config to make actual sense. (And secondarily, fixing bugs in that non-sensical config, because they would likely appear in the other, more meaning full configs we'll consider later.) Then based on that information we can plan further tasks.

One of them may indeed be to allow building TLS with only PSK/ECDH/ECDSA in a config with `USE_PSA` but not `MD_C`. But that will depend on the results of the present investigation.
