### ISSUE TITLE
Self test compilation fails with GCC 12.1.0

### ISSUE THREAD

**Issue by paul-elliott-arm** [Mbed-TLS/mbedtls#5974]
### Summary

With GCC 12.1.0, compilation of selftest.c fails (this was found running `all.sh test_no_platform`

```
test/selftest.c: In function ‘calloc_self_test’:
test/selftest.c:129:17: error: pointer ‘buffer1’ may be used after ‘free’ [-Werror=use-after-free]
  129 |     old_buffer1 = (uintptr_t) buffer1;
      |     ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
test/selftest.c:63:28: note: call to ‘free’ here
   63 | #define mbedtls_free       free
      |                            ^
test/selftest.c:130:5: note: in expansion of macro ‘mbedtls_free’
  130 |     mbedtls_free( buffer1 );
      |     ^~~~~~~~~~~~
```
This is (partially) technically correct, old_buffer1 retains a pointer to the then freed block of memory, although nothing is then done with it other than checking its value against the new returned pointer.

This is a new warning as of GCC 12, and turned on as part of -Wall, so I created this issue for discussion. We are not the only project having issues like this, and I can find virtually no documentation on the new warning.

I am not really sure how best to get around this, to be quite honest. I am not keen on suppressing this warning as I haven't seen any other failures as yet because of this, and its a potentially extremely useful feature.

**Comment by gilles-peskine-arm** [comment]
> old_buffer1 retains a pointer to the then freed block of memory, although nothing is then done with it other than checking its value against the new returned pointer

If that was what's going on, it would be invalid C: using a pointer to freed memory in any way, including comparing it, has undefined behavior. It could cause a fault on an architecture with checked pointers, and it allows the compiler to eliminate any code path that necessarily leads to this invalid use of the pointer.

But that's not what's going on. We're taking a copy of the value of the cast of the pointer to `uintptr_t`. This value is an integer and we can use it however we want. Ideally GCC would notice that `old_buffer1` is never converted back to a pointer and wouldn't emit this warning.

We're not really using `old_buffer1` for anything useful though, just to get a slightly more precise message. As far as I remember, I only printed that little bit of information because it was available and why not. The important part was whether alloc(0) is null.

I'll submit a fix.

**Comment by tom-cosgrove-arm** [comment]
So (urgh) a real fix might be

```
diff --git a/programs/test/selftest.c b/programs/test/selftest.c
index a314bd22d..6315294c0 100644
--- a/programs/test/selftest.c
+++ b/programs/test/selftest.c
@@ -126,7 +126,12 @@ static int calloc_self_test( int verbose )
             mbedtls_printf( "  CALLOC(1): passed\n" );
     }
 
+#pragma GCC diagnostic push
+#if __GNUC__ >= 12
+#pragma GCC diagnostic ignored "-Wuse-after-free"
+#endif
     old_buffer1 = (uintptr_t) buffer1;
+#pragma GCC diagnostic pop
     mbedtls_free( buffer1 );
     buffer1 = mbedtls_calloc( 1, 1 );
     if( buffer1 == NULL )
```

**Comment by tom-cosgrove-arm** [comment]
Hmm, this seems to be https://gcc.gnu.org/bugzilla/show_bug.cgi?id=104215

**Comment by daverodgman** [comment]
Some interesting exploration of the behaviour here: https://gcc.godbolt.org/z/fof8a747z
