### ISSUE TITLE
Add fast reduction dispatch to the new Bignum interface

### ISSUE THREAD

**Issue by yanesca** [Mbed-TLS/mbedtls#6025]
Currently there are optimised reduction functions in a number of named moduli, but they are not being used yet.

The task is to modify `mbedtls_mpi_mod_raw_mul()` so that it uses optimised reduction when available. 

Namely, when `MBEDTLS_MPI_MOD_REP_OPT_RED` is set in the moduli, use normal multiplication instead of Montgomery and reduce the result with the optimised reduction function. These functions only guarantee that the result is at most as long as the modulus, therefore we will need to call `mbedtls_mpi_mod_raw_fix_quasi_reduction()` to make it canonical.

In terms of testing, it is enough to extend the tests added in #7265 to cover the remaining named moduli.

**Comment by minosgalanakis** [comment]
Following the investigation into this item, it feels like the `mbedtls_mpi_mod_write` method needs to be updated for COORDINATE moduli since [it only allocates temporary memory](https://github.com/Mbed-TLS/mbedtls/blob/development/library/bignum_mod.c#L377-L392) for SCALAR moduli.

This will be addressed as part for this task.

**Comment by yanesca** [comment]
I am sorry, I am not sure I understand what you mean. The `bignum_mod` module doesn't know about coordinate or scalar. It only knows `MBEDTLS_MPI_MOD_REP_MONTGOMERY` and `MBEDTLS_MPI_MOD_REP_OPT_RED`. In the linked code we only allocate memory for `MBEDTLS_MPI_MOD_REP_MONTGOMERY`, which seems to be correct, as we don't need to convert the residue if the corresponding modulus is `MBEDTLS_MPI_MOD_REP_OPT_RED`.
