### ISSUE TITLE
ssl_debug_helpers_generated.c not added to Visual Studio project in Mbed TLS 3.2.1

### ISSUE THREAD

**Issue by irwir** [Mbed-TLS/mbedtls#6198]
### Summary

The topmost bugfix entry in change.log for version 3.2.1 is

> Re-add missing generated file library/ssl_debug_helpers_generated.c

However, the module would be missing in the object library becase the file has not been added into the Visual Studio project.

### System information

Mbed TLS version 3.21
Visual Studio 2022

### Expected behavior

ssl_client2 should build right out of the box

### Actual behavior

Link error: unresolved external symbol mbedtls_ssl_states_str referenced in function mbedtls_ssl_handshake_step	ssl_client2	mbedTLS.lib(ssl_tls.obj)

**Comment by daverodgman** [comment]
This seems to have been an error in the process for auto-generating the VS project file.

Re-running `./scripts/generate_visualc_files.pl` against a fresh checkout will fix this, or manually apply the following patch:

```
diff --git a/visualc/VS2010/mbedTLS.vcxproj b/visualc/VS2010/mbedTLS.vcxproj
index 62237b7474..ad6afd1aa1 100644
--- a/visualc/VS2010/mbedTLS.vcxproj
+++ b/visualc/VS2010/mbedTLS.vcxproj
@@ -359,2 +359,3 @@
     <ClCompile Include="..\..\library\ssl_cookie.c" />
+    <ClCompile Include="..\..\library\ssl_debug_helpers_generated.c" />
     <ClCompile Include="..\..\library\ssl_msg.c" />
```

**Comment by daverodgman** [comment]
I don't think this justifies a new release. As it's a manual error, it shouldn't affect future releases so I'll update our process with a note to check for this, and close this issue.

**Comment by daverodgman** [comment]
Re-opening to track follow-up work - @paul-elliott-arm please review updated process & changelog.

**Comment by irwir** [comment]
> Re-running `./scripts/generate_visualc_files.pl` against a fresh checkout will fix this, or manually apply the following patch:

Was this check correct?
This script can only add the list of existing `.c` and `.h` files to the library project. Creation of "generated" files should have been completed before this step (using corresponding scripts or makefile). There is a chance that the file was not existing at the time.

Additional note: It was more convenient and reliable when "generated" files were kept in the repository, because it was possible to compile the library from downloaded snapshot `.zip` without running any scripts or merging from the latest release.

**Comment by runout0** [comment]
**Summary**

!! in conjunction with WIZnet-PICO-C !!

CMake Error at src/spi/WIZnet-PICO-C/libraries/mbedtls/library/CMakeLists.txt:162 (add_library):
  Cannot find source file:

    ssl_debug_helpers_generated.c

Re-add missing generated file library/ssl_debug_helpers_generated.c

also an issue: erro.c doesn't exist (fixed by run scripts\generate_errors.pl)


**System information**

Mbed TLS version 3.6.2
Visual Studio 2019
Windows **10**

**Expected behavior**

MbedTLS should build right out of the box

**Actual behavior**

Compiler Error:
 CMake Error at src/spi/WIZnet-PICO-C/libraries/mbedtls/library/CMakeLists.txt:162 (add_library):
  Cannot find source file:
    ssl_debug_helpers_generated.c

run "make_generated_files.bat" throw failues

run "generate_ssl_debug_helpers.py" also fails :-(

d:\Daten\VisualStudio\RpPicoWiznet01\src\spi\WIZnet-PICO-C\libraries\mbedtls\scripts>python ..\framework\scripts\generate_ssl_debug_helpers.py
Traceback (most recent call last):
  File "d:\Daten\VisualStudio\RpPicoWiznet01\src\spi\WIZnet-PICO-C\libraries\mbedtls\framework\scripts\generate_ssl_debug_helpers.py", line 415, in <module>
    sys.exit(main())
             ~~~~^^
  File "d:\Daten\VisualStudio\RpPicoWiznet01\src\spi\WIZnet-PICO-C\libraries\mbedtls\framework\scripts\generate_ssl_debug_helpers.py", line 410, in main
    generate_ssl_debug_helpers(args.output_directory, args.mbedtls_root)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Daten\VisualStudio\RpPicoWiznet01\src\spi\WIZnet-PICO-C\libraries\mbedtls\framework\scripts\generate_ssl_debug_helpers.py", line 393, in generate_ssl_debug_helpers
    with open(os.path.join(output_directory, 'ssl_debug_helpers_generated.c'), 'w') as f:
         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'library\\ssl_debug_helpers_generated.c'
