### ISSUE TITLE
Bignum: extract core_sub_int from the prototype

### ISSUE THREAD

**Issue by yanesca** [Mbed-TLS/mbedtls#6231]
The task is to extract `core_sub_int` from the [prototype](https://github.com/hanno-arm/mbedtls/tree/ecp_prototype):
https://github.com/hanno-arm/mbedtls/blob/ecp_prototype/library/bignum_core.c#L214-L227

The function declaration should go to `library/bignum_core.h` and implementation to `library/bignum_core.c`.

The task includes making the legacy Bignum functions call the extracted functions where the functionality is duplicated. (To minimise impact on code size.)

The prototype is too macro heavy. Most new macros should be expanded/removed or replaced with static functions if possible. (Pre-existing macros should not be touched.) The macro `MPI_CORE` should expand to `mbedtls_mpi_core_ ## func ##` instead of `mbedtls_mpi_core_ ## func ## _minimal`.

**Comment by tom-cosgrove-arm** [comment]
> [make] legacy Bignum functions call the extracted functions where the functionality is duplicated

This is going to be tricky if just bringing over `core_sub_int`, since the equivalent `mbedtls_mpi_sub_int()` in existing bignum is signed (and it works by creating an MPI from the given integer then subtracting the MPIs).

Even if we brought over `core_sub_add` at the same time, and called that if the scalar passed to `mbedtls_mpi_sub_int()` was negative, I don't think this would work, since the `core_sub_int` is unsigned/two's complement/returns borrow (whichever way you want to look at it) so would need quite a bit of fix-up at the end.

**Comment by gilles-peskine-arm** [comment]
Almost all the logic in implementing `mbedtls_mpi_sub_int` on top of `core_sub_int` would be the same as the implementation of `mbedtls_mpi_sub_mpi` on top of `mbedtls_mpi_sub_abs`. This is more complex than the way it's done now, with `sub_int` on top of `sub_mpi`. So I agree with Tom, it seems best to keep the current implementation of `mbedtls_mpi_sub_int`, subcontracting to `mbedtls_mpi_sub_abs` which itself calls the new core subtraction function.

**Comment by yanesca** [comment]
I agree, we shouldn't completely refactor the signed Bignum implementation just to reuse a function as we might easily end up with higher code size and doesn't worth the effort anyway.

That said, `mbedtls_mpi_sub_int()` could be used to propagate the carry to the higher limbs of the result in `mbedtls_mpi_sub_abs()` (using it instead the `if( carry != 0)` block in the end).

**Comment by tom-cosgrove-arm** [comment]
NIce spot @yanesca - I've done that in f462973f74e8efe2c88eb3917f559aa4571cd9e9
