### ISSUE TITLE
Get size of available application data

### ISSUE THREAD

**Issue by KloolK** [Mbed-TLS/mbedtls#6240]
Is there some way to retrieve the currently available number of bytes of application data without calling `mbedtls_ssl_read()`?

I'm writing a "TLS socket" for higher layers to use and would like to notify them when new application data is available, tell them how much it is, but leave it up to them when and how much to retrieve.
I'd like to prevent having to buffer all application data inside my TLS socket, because that would mean copying it once from mbedtls' buffer to my socket and then again from there to the application whenever it actually requests the data.

After a quick look into the sources, it seems like, if at all, this might be possible for single records. But all related fields are private and I could not find any API for this.

#551 seems related, but is more about peeking into the application data, while I would be fine with knowing just the size of available application data.

**Comment by minosgalanakis** [comment]
To my knowledge that is still not possible for the same reasons that #551 is describings, because it effectively requires modifcation on how the asynchronous reads/writes are handled across platforms. It may be possible to do the required modifications for your system, but it would not be portable across all platforms. 

I hope that was of help. 

I would also encourage you to ask the question on the mailing list (mbed-tls@lists.trustedfirmware.org), because it reaches a wider community, and is more fitted for support requests.
