### ISSUE TITLE
Running `all.sh --force` on a clean repository removes `programs/fuzz/Makefile`

### ISSUE THREAD

**Issue by AndrzejKurek** [Mbed-TLS/mbedtls#6247]
This forces the user to discard `programs/fuzz/Makefile` changes to regain a working repository copy.

**Comment by gilles-peskine-arm** [comment]
Same with `Makefile`, `programs/Makefile`, etc. This is because some components use CMake in-tree, and that overwrites `**/Makefile`. [It's documented](https://github.com/Mbed-TLS/mbedtls/blob/v3.2.1/tests/scripts/all.sh#L34). The point of `--force` is to say you don't mind this.

Why is this issue about `programs/fuzz/Makefile` specificatlly? Just the one you happened to notice, or is it / should it be treated differently from the others?

**Comment by AndrzejKurek** [comment]
Oh, maybe I wasn't specific enough. The script fails to execute and does not clean after itself on a fresh repository:
```
./tests/scripts/all.sh test_full_cmake_gcc_asan --force
cp: cannot stat 'include/mbedtls/mbedtls_config.h.all.bak': No such file or directory
git status
On branch pkcs5-no-md
Your branch is up to date with 'AndrzejKurek/pkcs5-no-md'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        deleted:    programs/fuzz/Makefile

no changes added to commit (use "git add" and/or "git commit -a")
```
