### ISSUE TITLE
How can I set the DTLS version to DTLS 1.2 in the DTLS protocol using MBEDTLS

### ISSUE THREAD

**Issue by remainfox** [Mbed-TLS/mbedtls#6263]
# How can I set the DTLS version to DTLS 1.2 in the DTLS protocol using MBEDTLS

`mbedtls version`: `2.27.0`
this is my code:
```c
mbedtls_entropy_init(&pDtlsSession->entropy);
mbedtls_ctr_drbg_init(&pDtlsSession->ctrDrbg);
mbedtls_ssl_config_init(&pDtlsSession->sslCtxConfig);
 mbedtls_ssl_conf_min_version(&pDtlsSession->sslCtxConfig,MBEDTLS_SSL_MAJOR_VERSION_3,MBEDTLS_SSL_MINOR_VERSION_3);
mbedtls_ssl_conf_max_version(&pDtlsSession->sslCtxConfig,MBEDTLS_SSL_MAJOR_VERSION_3,MBEDTLS_SSL_MINOR_VERSION_3);

mbedtls_ssl_init(&pDtlsSession->sslCtx);
 mbedtls_ctr_drbg_set_prediction_resistance(&pDtlsSession->ctrDrbg, MBEDTLS_CTR_DRBG_PR_ON);
CHK(mbedtls_ctr_drbg_seed(&pDtlsSession->ctrDrbg, mbedtls_entropy_func, &pDtlsSession->entropy, NULL, 0) == 0, STATUS_CREATE_SSL_FAILED);

mbedtls_ssl_conf_min_version(&pDtlsSession->sslCtxConfig,MBEDTLS_SSL_MAJOR_VERSION_3,MBEDTLS_SSL_MINOR_VERSION_3);
mbedtls_ssl_conf_max_version(&pDtlsSession->sslCtxConfig,MBEDTLS_SSL_MAJOR_VERSION_3,MBEDTLS_SSL_MINOR_VERSION_3);
```

# result

After I set the DTLS version as described above, the DTLS negotiation will still use the DTLS1.0 version for the handshake

# wireshark pcap

![image](https://user-images.githubusercontent.com/10653136/188791387-d6aca354-9cab-4991-8002-40ca6215b01f.png)

**Comment by gilles-peskine-arm** [comment]
I'm confused. What's the problem? The wireshark trace shows “DLTSv1.2” as the protocol version. Wireshark shows “DTLS” without a version for the ClientHello because the version hasn't been negotiated yet, it doesn't show a different indication in the case where the client only supports a single version.

**Comment by remainfox** [comment]
@gilles-peskine-arm 

Thank you for your answer. I have two questions

1. Check whether the DTLS version of the `first Client Hello` packet can be set to 1.2

2. The interval from the first client Hello packet to the second Client Hello packet takes 1 second seconds. Can this interval be reduced

![image](https://user-images.githubusercontent.com/10653136/188810959-9eb88b72-f370-482e-8a3b-64bec017e83e.png)

**Comment by gilles-peskine-arm** [comment]
> Whether the DTLS version of the first Client Hello packet can be set to 1.2

A ClientHello packet doesn't “have” a version, since the version has not been negotiated yet. That's why Wireshark doesn't display a version. If you look at the details of the packet in Wireshark, you'll see the set of versions offered by the client.

> The interval from the first client Hello packet to the second Client Hello packet takes 1 second seconds. Can this interval be reduced

That might be a problem with the client, with the server, or with the network. It's impossible to diagnose without knowing your network, and it's not something we can help with.
