### ISSUE TITLE
missing #ifdef breaks build when MBEDTLS_SSL_KEEP_PEER_CERTIFICATE not defined

### ISSUE THREAD

**Issue by rlezuo1** [Mbed-TLS/mbedtls#6382]
https://github.com/Mbed-TLS/mbedtls/blob/845de0898e505df4b9b2bf3eb95e2592a9910e98/library/ssl_tls13_server.c#L3039

access struct mbedtls_ssl_session's peer_cert member unconditionally, but should be conditional on defined(MBEDTLS_SSL_KEEP_PEER_CERTIFICATE)

this breaks the build.

**Comment by tom-daubney-arm** [comment]
Hi, thanks for posting an issue. At this time we do not consider this to be a bug. MBEDTLS_SSL_KEEP_PEER_CERTIFICATE is currently a prerequisite to using TLS 1.3 in the library and so the library should not be built without it when planning to use TLS 1.3 functionality. In the future, the need for MBEDTLS_SSL_KEEP_PEER_CERTIFICATE will be removed and so this will be addressed when that happens. I will now close this issue due to not technically being a bug at this time.

**Comment by gilles-peskine-arm** [comment]
How did you get that far with the build? `#error "MBEDTLS_SSL_PROTO_TLS1_3 defined without MBEDTLS_SSL_KEEP_PEER_CERTIFICATE"` from `check_config.h` should have prevented the build as well.

**Comment by rlezuo1** [comment]
@gilles-peskine-arm a good question indeed, I was just compiling the library ( 07ba2be20ba4baedbc2f167b8a64dddb8d660ac5 ). Nothing seems to include check_config.h that way. I was reducing features to minimize flash utilization for an embedded project, which does not need certificates, base64 and x509 at all. This peer_cert is very significant therefore.

**Comment by gilles-peskine-arm** [comment]
I'm curious how you managed to make a build that does not to include `check_config.h`: it's not supposed to be possible. (It was in Mbed TLS 2.x, but not in 3.x.) `check_config.h` is included via `build_info.h`, which is the same file that includes `mbedtls_config.h` (or alternative specified by `MBEDTLS_CONFIG_FILE`). What did we miss? Can you share some information about your platform, build system and compiler options?

**Comment by rlezuo1** [comment]
I do not know how the build succeeded, I can not reproduce it, maybe I disabled the check in check_config.h.
Sorry for the noise.
