### ISSUE TITLE
 mbedTLS RSA encrypt/decrypt can't support for Java’s “RSA/ECB/OAEPWithSHA-256AndMGF1Padding”

### ISSUE THREAD

**Issue by cloudyfly** [Mbed-TLS/mbedtls#6406]
### Suggested enhancement
encrypt data with mbedTLS rsa library and decrypt with Java “RSA/ECB/OAEPWithSHA-256AndMGF1Padding”.
In my code, mbedtls_rsa_context is initted as PKCS_V21, and hash id is MD_SHA1.  This can be decrypted in Java with "RSA/ECB/OAEPWithSHA-1AndMGF1Padding"。 
But when I set mbedtls_rsa_context initted as PKCS_V21, and hash id with MD_SHA256, I can't decrypt in Java with "RSA/ECB/OAEPWithSHA-256AndMGF1Padding".
That is to say mbedTLS RSA seems only support RSA/ECB/OAEPWithSHA-1AndMGF1Padding"? 

### Justification

Mbed TLS needs this because it can encrypt and decrypt with java as "RSA/ECB/OAEPWithSHA-256AndMGF1Padding"

**Comment by yanesca** [comment]
Hi @cloudyfly, thank you for raising this issue. Could you please post some more information (test data, code snippets) so that we can reproduce the issue?

**Comment by gilles-peskine-arm** [comment]
OAEP uses a hash function for two purposes: to hash the label, and as a building block for the mask generation function (everyone uses MGF1 for that). Unfortunately, there are two schools of thought about what “OAEP with SHA-256” means:

* It means SHA-256 for the label, and MGF1 using SHA-256 for the mask generation function. This is what Mbed TLS does. It's also what BouncyCastle does for "RSA/ECB/OAEPWithSHA-256AndMGF1Padding".
* It means SHA-256 for where OAEP uses a hash directly, i.e. for the label. Since no hash is explicitly specified for MGF1, it uses SHA-1, because that's the default for MGF1 according to [PKCS#1 2.2](https://www.rfc-editor.org/rfc/rfc3447#section-7.1). This is what Sun does for "RSA/ECB/OAEPWithSHA-256AndMGF1Padding". (Or used to, my knowledge about Java may be out of date.)

Mbed TLS does not offer a way to use two different hashes for OAEP. We can implement this if there's a strong business case. There is no known security weakness in using SHA-1 for MGF1 (unlike the OAEP label, for which there is a major security weakness in some rare circumstances). However, since the world is largely moving away from SHA-1, our recommendation is to not use SHA-1, and instead use a modern cryptography .

Suggested reading about the OAEP hash mess in Java: [background](https://stackoverflow.com/questions/32161720/breaking-down-rsa-ecb-oaepwithsha-256andmgf1padding), [concrete solution](https://stackoverflow.com/questions/33572909/rsa-ecb-oaepwithsha-256andmgf1padding-but-with-mgf1-using-sha-256).

**Comment by gilles-peskine-arm** [comment]
I'm labelling this “help-wanted”, because we're very unlikely to implement this ourselves. If you really want this, you'll have to add the necessary interfaces and tests. Please get in touch with us first so we can validate the interface and schedule the bandwidth for review.

Since the relevance of SHA-1 keeps getting smaller over time, we may still just close this request as no longer relevant.

**Comment by cloudyfly** [comment]
> Hi @cloudyfly, thank you for raising this issue. Could you please post some more information (test data, code snippets) so that we can reproduce the issue?

pls refer：
[](https://forums.mbed.com/t/mbedtls-equivalent-for-javas-rsa-ecb-oaepwithsha-256andmgf1padding/4839)

- mbedtls encrypt and java decrypt , it's OK with **sha1**
【mbedtls】:
mbedtls_rsa_set_padding(rsaCtx, MBEDTLS_RSA_PKCS_V21, **MBEDTLS_MD_SHA1**)
…………
mbedtls_rsa_pkcs1_encrypt( )
【Java】: 
    public static String decrypt(String str,String privateKey) throws Exception {
        ………………
        Cipher cipher = Cipher.getInstance("**RSA/ECB/OAEPWithSHA-1AndMGF1Padding**");
        cipher.init(Cipher.DECRYPT_MODE, priKey);
        String outStr=new String(cipher.doFinal(inputByte));
        return outStr;
    }

- mbedtls encrypt and java decrypt , it's not OK with **sha256**
【mbedtls】:
mbedtls_rsa_set_padding(rsaCtx, MBEDTLS_RSA_PKCS_V21, **MBEDTLS_MD_SHA256**)
…………
mbedtls_rsa_pkcs1_encrypt( )
【Java】: 
    public static String decrypt(String str,String privateKey) throws Exception {
        ………………
        Cipher cipher = Cipher.getInstance("**RSA/ECB/OAEPWithSHA-256AndMGF1Padding**");
        cipher.init(Cipher.DECRYPT_MODE, priKey);
        String outStr=new String(cipher.doFinal(inputByte));
        return outStr;
    }

**Comment by cloudyfly** [comment]
>

**Comment by cloudyfly** [comment]
I have fixed this problem with followed code in Java.
…………
Cipher cipher = Cipher.getInstance("**RSA/ECB/OAEPWithSHA-256AndMGF1Padding**", new BouncyCastleProvider());
…………

thanks
