### ISSUE TITLE
Avoid assumptions about implementation in EC J-PAKE tests

### ISSUE THREAD

**Issue by mpg** [Mbed-TLS/mbedtls#6502]
Currently the tests for EC J-PAKE assume that it's OK to tests multiple invalid parameters in a row, and that in some circumstance you can successfully do a valid operation after an invalid one; however that is not necessarily the case, the first test could have put the operation in a special state that affects the result of subsequent tests.

Also, after https://github.com/Mbed-TLS/mbedtls/pull/6390 the tests also rely on the assumption that making a shallow copy of the operation context works, which happens to be true of our built-in implementation currently, but is far from guaranteed. This should be fixed too.

This task is to design a test strategy that both avoids this issue, and ensure good testing, including of the fact that otherwise valid calls fail when the follow a call the return an error (something that's not systematically tested so far), and implement it.

Cc @gilles-peskine-arm who might expand on this description by suggesting reasonable strategies.

**Comment by valeriosetti** [comment]
@mpg I took a quick look at the test functions used for EC-JPAKE and for example in `ecjpake_setup` there's an alternation of "internal" tests (verification done inside the function without interaction with the `.data` file) and "external" ones. Of course all the "internal" ones are also executed every time the function is called.
So in my opinion there might be 2 solutions: 

1. move "internal" tests to a separate function (or more than one) which is tested only once
2. for every "controlled" failure, reinitialize the the `operation` structure. However this might be slightly complex since at each step that structure might be in different states

What do you think?

**Comment by valeriosetti** [comment]
@mpg I have a question about this sentence:

>  including of the fact that otherwise valid calls fail when the follow a call the return an error

As per my understanding this means that when I call a function after the preceding one failed, even though the new call is OK, it fails due to the previous error. Is that right?
I'm asking because according to your description of the current implementation it seems that it's possible to continue invoking functions even though the previous one failed. In this case such test would fail by default **unless** we add a new state variable in the JPAKE context's structure which keeps track of the previous operation (maybe it's already present) so that you cannot call another function if the previous one failed and you didn't reinitialize  the operation.

Is my understanding correct?

**Comment by mpg** [comment]
> @mpg I took a quick look at the test functions used for EC-JPAKE and for example in `ecjpake_setup` there's an alternation of "internal" tests (verification done inside the function without interaction with the `.data` file) and "external" ones. Of course all the "internal" ones are also executed every time the function is called. So in my opinion there might be 2 solutions:
> 
>     1. move "internal" tests to a separate function (or more than one) which is tested only once
> 
>     2. for every "controlled" failure, reinitialize the the `operation` structure. However this might be slightly complex since at each step that structure might be in different states
> 
> 
> What do you think?

I agree that's a problem with the current structure. I think the structure you're proposing makes sense, that's actually one I was considering while this was on me. Regarding the second point, something I had considered, was to have a sequence of calls with an enum representing each step in that sequence / thing that can go wrong. Then, either in a loop or controlled by a parameter in the `.data` file, run the sequence using only valid inputs and asserting everything works until you reach the point indicating by the loop index / parameter, then do the wrong think it says, like use paramaters that are invalid (in the specified way) for the  next call, assert it fails, and from now on until the end of the sequence, use valid inputs again but assert failure at each step.

I hope it makes sense, I'm not sure my description is very clear.

cc @gilles-peskine-arm with whom I discussed this and who might have useful suggestions.

**Comment by gilles-peskine-arm** [comment]
>  was to have a sequence of calls with an enum representing each step in that sequence / thing that can go wrong. (…)

In pseudocode:

```
void test_operation_sequence(step_number_t step_to_fail) {
    status = psa_ecjpake_foo(step_to_fail == FOO ? invalid input : valid input);
    TEST_EQUAL(status, step_to_fail == FOO ? PSA_ERROR_INVALID_THING : PSA_SUCCESS);
    status = psa_ecjpake_bar(step_to_fail == BAR ? invalid input : valid input);
    TEST_EQUAL(status, step_to_fail == BAR ? PSA_ERROR_INVALID_THING : PSA_SUCCESS);
    …
}
```
