### ISSUE TITLE
PSA repository investigation

### ISSUE THREAD

**Issue by ronald-cron-arm** [Mbed-TLS/mbedtls#6602]
The goal of this task is:
- [x] to define the requirements for the PSA repository
- [x] to define the PSA repository 
- [x] to determine the modifications needed and/or nice-to-have to the Mbed TLS code base to ease the creation and update of the PSA repository from the Mbed TLS code base.

The definition of the PSA repository encompasses:
- [x] the definition of its directory structure including the content of the directories
- [x] the definition of the supported build systems
- [x] the definition of how it is configured
- [x] the definition of the platform interface
- [x] the definition of when and how it is updated from the Mbed TLS code base
- [x] how when updated, it is validated which relates to how is the PSA repository code tested
- [x] the definition of its CI

**Comment by ronald-cron-arm** [comment]
I have covered all the tasks of the description either in https://github.com/Mbed-TLS/psa-crypto or by creating a task under the [PSA cryptography repository prototype](https://github.com/orgs/Mbed-TLS/projects/1#column-19270803) EPIC. Not a final solution for everything (like the configuration) but enough investigation to have a reasonable idea of the remaining amount of time that's needed.

**Comment by glarsennordic** [comment]
Sorry to jump into the comments unannounced -- Is https://github.com/Mbed-TLS/psa-crypto a private repo? I'm trying to keep an eye on the latest regarding PSA support in mbed-tls. It seems like it'd be a good idea to be following that repo, but GitHub tells me it doesn't exist

**Comment by gilles-peskine-arm** [comment]
@glarsennordic It's private for now because it's still in the very early stages. We'll make it public when it's ready for beta (in the software sense of “go ahead and try it out, but be aware that it might change completely”).

Not that the new repository will not have any better PSA support than Mbed TLS: all it changes is the code's presentation, removing or hiding the legacy and non-crypto parts of Mbed TLS. All the features (key store, driver support, implementations of algorithms) are snapshots of Mbed TLS.
