### ISSUE TITLE
Missing cipher functionality for CCM mode

### ISSUE THREAD

**Issue by jethrogb** [Mbed-TLS/mbedtls#662]
Several cipher functions are not implemented for CCM mode (but they are for GCM):
- mbedtls_cipher_update_ad
- mbedtls_cipher_update
- mbedtls_cipher_write_tag
- mbedtls_cipher_check_tag

**Comment by jethrogb** [comment]
I guess supporting all those might be tricky since for CCM you need to know the message length before doing anything else

**Comment by SideChannel** [comment]
I would strongly support adding functionality for Initialize, Update, Finalize Interface to (AES-) CCM. In the moment it is not possible to encrypt and authenticated (arbitrary) large plaintext with the standard interface while with GCM and Chacha20Poly1305 it is possible. Note, that this has nothing todo with GCM being online and CCM not. That you know the length of the message (as required at the start of CCM) is not the same as knowing the contents of the message. 

Only the second step would then be adding this functionality to the cipher layer.

**Comment by gilles-peskine-arm** [comment]
@SideChannel This is possible according to the PSA Crypto API: [`psa_aead_set_lengths`](https://armmbed.github.io/mbed-crypto/html/from_doxygen.html#psa_aead_set_lengths) is in this API for the sake of CCM. We haven't implemented PSA multipart AEAD in Mbed TLS yet, but this is on our [roadmap](https://developer.trustedfirmware.org/w/mbed-tls/roadmap/).

Since we're moving from the mbedtls API to the PSA API for crypto, we don't have plans to add this feature to the `mbedtls_ccm_xxx` or `mbedtls_cipher_xxx` interface. However, we wouldn't be opposed to an external contribution.

**Comment by gilles-peskine-arm** [comment]
I'm closing this issue as completed since multipart CCM is available in the library, only with the PSA interface. [There is a newer issue tracking the request for CCM in the legacy crypto interface](https://github.com/Mbed-TLS/mbedtls/issues/8545).
