### ISSUE TITLE
compat.sh: report and filter cipher suite names consistently

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#6651]
`compat.sh` reports cipher suite names based on the client's naming scheme. So the `x->y` and `y->x` directions report different names for the same cipher suite, which makes the reports hard to track.

@mpg notes that the filtering is also based on this name, which makes filtering tricking, and can lead to asymmetric filters. This has tripped me up more than once (and I've only just now understood this was the reason `compat.sh` wasn't doing what I expected).

For example:
```
$ ./tests/compat.sh -V NO -p OpenSSL -m tls12 -t PSK
m->O tls12,no TLS-PSK-WITH-AES-128-CBC-SHA ............................. PASS
m->O tls12,no TLS-PSK-WITH-AES-256-CBC-SHA ............................. PASS
O->m tls12,no PSK-AES128-CBC-SHA ....................................... PASS
O->m tls12,no PSK-AES256-CBC-SHA ....................................... PASS
------------------------------------------------------------------------
PASSED (4 / 4 tests (0 skipped))
$ ./tests/compat.sh -V NO -p OpenSSL -m tls12 -t PSK -f AES128
O->m tls12,no PSK-AES128-CBC-SHA ....................................... PASS
------------------------------------------------------------------------
PASSED (1 / 1 tests (0 skipped))
```

I think reporting and filtering should be based on the standard names.

**Comment by yanrayw** [comment]
I had some search on the standard names here. Should it be in the format of `TLS_PSK_WITH_AES_128_CBC_SHA`? Alternatively can we use what it's defined in mbedtls like `TLS-PSK-WITH-AES-128-CBC-SHA`?

**Comment by gilles-peskine-arm** [comment]
@yanrayw The [TLS cipher suite registry](https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#tls-parameters-4) has official names for cipher suites. They look like `TLS_PSK_WITH_AES_128_CBC_SHA`. I think the names in mbedtls are the same except with `-` instead of `_`.

**Comment by yanrayw** [comment]
After some investigation, I plan to implement the code as following design:
1. Since we plan to report and filter cipher suite names based on standard names. We could rename all cipher suite defined in `add_common_ciphersuites`, `add_openssl_ciphersuites`, `add_gnutls_ciphersuites`, and `add_mbedtls_ciphersuites` to  standard names. Then everything is handled with standard names at first.
2. Once we filter all cipher suites after `filter_ciphersuites`, then we call `translate_ciphers.py` to translate standard names to cipher suite names for OpenSSL, gunTLS and mbedTLS respectively. 
3. In `run_client`, we pass cipher suites based on client's naming convention as current design, plus standard cipher suites names in order to report the results as standard names. 

Since it involves lots of modifications in the code, I'm afraid of going the wrong way. Above is my draft design plan, if it doesn't make sense pleases fix me. Thanks!

**Comment by mpg** [comment]
Your plan looks sensible to me!

**Comment by gilles-peskine-arm** [comment]
Your plan looks sensible to me too.

However, we *may* rewrite `compat.sh` in Python at some point. If we do it soon, we should not waste time doing a lot of modifications in the current version.

So please wait a couple of days before spending more time on this.
