### ISSUE TITLE
Setup D during ECDSA_ALT method for SecureEnclave

### ISSUE THREAD

**Issue by sevilS** [Mbed-TLS/mbedtls#6673]
### Suggested enhancement
Enable access to d variable in order to configure private keys from device Secure Enclave
Usage of device Secure Enclave keys inside mbedtls has changed since version 3.x.x, and it requires to call MBEDTLS_PRIVATE variable

### Explanation

We are using the method xxxxx in order to configure public and private key, this key is comming from Secure Enclave so we are not able to configure a regular key.
Instead we are obtaining the Handle from secure enclave in order to configure a parameter in method: xxxxx
In order to be used in method: mbedtls_ecdsa_sign

This is what we are doing right now:
When obtaining the mbedtls_pk_context:
 // Configure public key
...
// Configure private key
mbedtls_ecp_keypair* ecKeyPair = mbedtls_pk_ec(*pkContext);
mbedtls_mpi_read_binary(&ecKeyPair->MBEDTLS_PRIVATE(d), (const unsigned char*) &keyHandle, sizeof(CRYPTO_HANDLE));
// This keyHandle is the way we have to recover the key from SecureEnclave 

This is what we are doing in order to recover the key:
In method mbedtls_ecdsa_sign:
...
// Recover private key handle
CRYPTO_HANDLE keyHandle;
mbedtls_mpi_write_binary(d, (unsigned char*) &keyHandle, sizeof(CRYPTO_HANDLE));
...

This is working fine, but we are wondering if the usage of MBEDTLS_PRIVATE is okay or if there is something wrong or missing.

**Comment by gilles-peskine-arm** [comment]
I didn't even realize you could use `MBEDTLS_ECDSA_SIGN_ALT` to put the ECDSA secret key in a secure enclave without patching the library. This is not officially supported.

You can use `MBEDTLS_PRIVATE` if you want. As long as you follow the documentation and you do your own quality assurance, this can work. However, you have to handle the risk that a future Mbed TLS 3.x will remove this field, or change its semantics, and break your code. So if you use `MBEDTLS_PRIVATE`, you should let us know and ask for a proper official feature, as you did here.

We are not going to add official support for secure enclaves in the legacy crypto interface. Please switch to the PSA crypto API, which officially supports opaque keys for all cryptographic mechanisms. Since we are not going to officially support the feature as requested, I am closing this issue.

Support for PSA drivers is still incomplete. If you urgently need a feature that's not implemented yet, we welcome contributions.

For information, we're currently doing a major rewrite of the bignum code, which eventually (probably around Mbed TLS 3.5 or so) will lead to changing the type of `mbedtls_ecp_keypair::d`. I think you'll still be able to use this d punning trick after that, but you'll need to change your code a bit.
