### ISSUE TITLE
The PKCS7 module lacks test coverage for failure cases

### ISSUE THREAD

**Issue by bensze01** [Mbed-TLS/mbedtls#6745]
The tests for the PKCS7 module fail to cover cases where the various validity tests within the module fail.

This lack of coverage prevents the address sanitizer from finding potential memory management issues that might crop up if one of these branches is taken.

Instructions to get an [lcov coverage report](https://github.com/linux-test-project/lcov) for the pkcs7 module (Thanks @mpg!)
```bash
scripts/config.py set MBEDTLS_PKCS7_C
make CFLAGS='--coverage -g3 -O0' LDFLAGS=--coverage -C tests test_suite_pkcs7
(cd tests && ./test_suite_pkcs7)
make lcov
firefox Coverage/index.html
# click my way to pkcs7.c and look at exactly which lines/branches are not covered
```

Here is the resulting coverage report for the current head of development (90af1a1):
[View](https://htmlpreview.github.io/?https://gist.githubusercontent.com/bensze01/0f46d07e02f56a4e5e6cd5d25bda0153/raw/38a5d7242b03d2d1fc15f0bd38507c2218e7b306/pkcs7.c.gcov.html) [Download](https://gist.githubusercontent.com/bensze01/0f46d07e02f56a4e5e6cd5d25bda0153/raw/38a5d7242b03d2d1fc15f0bd38507c2218e7b306/pkcs7.c.gcov.html)

**Comment by bensze01** [comment]
@nick-child-ibm Could you take a look at the coverage report, and add negative tests for the missed branches?

**Comment by gilles-peskine-arm** [comment]
There may be cases that we choose not to test for now, in particular if the only possible failure is malloc (we don't yet have a good way to force memory allocations to fail). But non-coverage needs to be justified. Every validation error path should be covered by a test.

**Comment by mpg** [comment]
I'd like to highlight that adding negative test should not be just a mechanical process of getting lines covered, we should also constantly think if there are other kinds of invalid inputs that we can generate and that perhaps the code is not already handling. 

Adding tests for uncovered lines will only cover cases that we thought about while writing the code, but their may be other cases that the code currently doesn't handle, and writing test cases is a good opportunity to think about those.

**Comment by gilles-peskine-arm** [comment]
> I'd like to highlight that adding negative test should not be just a mechanical process of getting lines covered

Right. There are two things to watch for in negative testing. One is that things that should be rejected are rejected, and you don't get that information from coverage: if a check is missing, coverage isn't going to tell you. Another is that when an error happens, it's handled gracefully (e.g. memory is cleaned up correctly). That second kind of problem is where coverage is a good measurement.

**Comment by nick-child-ibm** [comment]
Hello,
As noted, most of these unexecuted code branches are error cases during parsing of an asn1 buffer into a struct. I agree these should be hit and tested. I also fully agree with the mentality of testing the entire input data to hit cases that the code does not expect.
While I could go and generate several DER pkcs7 data files with slight modifications to try and hit all of these possible error cases. Why not just use the fuzzer? Or if it really must be covered by `test_suite_pkcs7`, would it be acceptable to just iterate through the DER bytes, flip the bits, and attempt to parse/verify?

The idea of adding a makefile entry for how to generate several slightly incorrect pkcs7's does not sound like the best way to go about things, especially if we want to cover cases that the code does not know how to handle.

**Comment by mpg** [comment]
> The idea of adding a makefile entry for how to generate several slightly incorrect pkcs7's does not sound like the best way to go about things

Indeed it's not. Fortunately testing does not have to use files. What other similar modules (for example X.509) do, is they have a test function that takes input from files, and one that takes input as a hex string (such as `x509parse_crt()`) that's mostly used for negative testing with malformed input. Traditionally we used to generate these inputs manually which frankly can be a bit tedious (especially if you need to adjust multiple length bytes). I think generating these inputs from a script based on the ASN.1 structure would be great, but I don't think we've done that so far.

There are a few problems I see with the approach "just iterate through the DER bytes, flip the bits, and attempt to parse/verify": one is to determine what the expected behaviour is (parse error, verify error, or perhaps even no error at all if flipping some bits leaves the data valid), another is that not all by bytes of a DER encoding are as interesting, so we should mostly focus on the tag and length bytes, flipping bits elsewhere is likely wasted time, and finally for length bytes ideally instead of flipping a bit we probably want to have two cases: increment/decrement.

For reference, for X.509 certificate parsing, it looks like we went about it in a fairly systematic way, starting from the empty string and building our way up to a valid certificate: https://github.com/Mbed-TLS/mbedtls/blob/development/tests/suites/test_suite_x509parse.data#L1062

**Comment by gilles-peskine-arm** [comment]
To add to @mpg's reply:

> Why not just use the fuzzer?

Because fuzzers aren't deterministic so we can't really know what they've tested in any given campaign, and fuzzers are slow so we don't run them as part of our CI. They serve a different purpose from unit tests.

> just iterate through the DER bytes, flip the bits, and attempt to parse/verify

No, because we don't just want to know that Asan is happy, we also want to know that correct inputs are accepted and incorrect inputs are rejected with an appropriate error.
