### ISSUE TITLE
Bad performance of v3.3.0 compared to v3.2.1 on arm µC

### ISSUE THREAD

**Issue by dns13** [Mbed-TLS/mbedtls#6790]
### Summary
I'm currently using mbedTLS v3.2.1 together with open62541 on my arm target (GD32F450). The SSL Handshake when connecting with AES128 and SHA256 is quite slow, but reasonable (about 4-8s). After updating to v3.3.0 using the same configuration the handshake is taking about double to triple that time (16-20s).

I don't know how much of that time is spent inside mbedTLS, but the difference is very notable and reproducable every time I switch versions.

I've also tried to add the new configuration options, but that result in no difference.

I know that use case is quite specific, hard to reproduce and the informations I can give are spares, but maybe there is an obvious change that may cause this issue.

### System information

Mbed TLS version (number or commit id): v3.3.0
Operating system and version: FreeRTOS V10.4.6
Configuration (if not default, please attach `mbedtls_config.h`): [mbedtls_config.zip](https://github.com/Mbed-TLS/mbedtls/files/10235484/mbedtls_config.zip)
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): arm-none-eabi-gcc 11.3Rel1
`-Os -DNDEBUG -flto=auto -fno-fat-lto-objects -mcpu=cortex-m4 -mfloat-abi=hard -specs=nosys.specs -ffunction-sections -fdata-sections -fstack-usage -ffast-math -std=gnu++20 `
Additional environment information: 

### Expected behavior
Same handshake speed as with v3.2.1.

### Actual behavior
Much slower.

### Additional information
I'm using latest open62541 v1.3.4.

**Comment by gilles-peskine-arm** [comment]
It's going to be hard to figure this out without more information. At least please tell us which cipher suite you're using, which curve if using ECC, etc.

Any other information you can get would help. Can you get network traces (e.g. with Wireshark) and compare the timing and non-encrypted content of packets? That would tell us whether the same options are negotiated, and which part is taking time.

**Comment by dns13** [comment]
Network traces are a good idea, I will create them, better than debugging the deep insides of open62541 🙈

**Comment by dns13** [comment]
Wireshark traces weren't helpful at all, nothing to add without knowing the internals of OPC-UA.

But I've tracked the issue down to a mbedtls function call. During handshake the library is calling `mbedtls_rsa_rsaes_oaep_decrypt()` twice. On v3.2.1 one call is taking around 2 seconds, on v3.3.0 one call takes around 5 seconds.

I don't know anything about the used contextes, but can provide more informations when required.

**Comment by gilles-peskine-arm** [comment]
Thanks! This gives us something to look at. What's the value of `MBEDTLS_MPI_WINDOW_SIZE` in your configuration? It's a memory vs performance compromise. Can you try tuning it and see if it makes a difference on your platform?

Also, what's the key size, and is `MBEDTLS_RSA_NO_CRT` enabled in your configuration?

The 3.3.0 release includes a security fix that does make RSA decryption slower (almost all the CPU time of RSA decryption is modular exponentiation, and we've fixed a timing side channel in modular exponentiation). However, in our benchmarks, the impact was measurable but small, not anything near +100%. This may depend on the configuration and platform though.

**Comment by dns13** [comment]
`MBEDTLS_RSA_NO_CRT` is not defined.
`MBEDTLS_MPI_WINDOW_SIZE` is also not defined, so it may be 6 if the defaults in the configuration are correct

**Comment by gilles-peskine-arm** [comment]
Ok. I'm afraid your system is already configured for performance, so probably nothing to be gained there. Although part of the compromise is between the number of memory accesses and the number of integer ops. Can you try lower values of `MBEDTLS_MPI_WINDOW_SIZE` and see if it helps on your platform? 3.3.0 makes more memory accesses, and since that's hurting you and the number of memory accesses increases with the window size, it may be faster to reduce the window size (and do more multiplications).

**Comment by gilles-peskine-arm** [comment]
Labeling [bug], targeting the next release even though this is just about performance and not a functionality bug, because this is a very large performance regression, affecting the LTS branch as well.

**Comment by dns13** [comment]
With `MBEDTLS_MPI_WINDOW_SIZE == 1` I'm getting about the same performance as with v3.2.1.

Thank you!

**Comment by dns13** [comment]
From 1 to 3 there does not seem to be a measurable difference, starting with 4 it's getting slower.

**Comment by mpg** [comment]
> From 1 to 3 there is no notable difference, starting with 4 it's getting slower.

Interesting, thanks for sharing. As Gilles said, higher values are supposed to give higher performance (at the expense of RAM), up to a point, but apparently since we added side-channel counter-measures like constant-time table lookup, this seems to negate the expected performance benefits of larger values.

For comparison, here as some figure on a very different platform, based on an Intel core-i7. This is 2nd-best and 2nd-worst of 5 runs, for two key sizes, in operations per second (so, higher is better).

| w    |    6    |    5    |    4    |    3    |    2    |    1    |
| - | - | - | - | - | - | - |
| 2048 | 158-165 | 237-247 | 266-277 | 298-346 | 337-346 | 300-334 |
| 4096 |  43-43  |  50-54  |  57-59  |  58-59  |  59-60  |  51-55  |

So, 2 seems to be the sweet spot for performance on that platform and since you say there is no notable difference from 1 to 3 on your platform, it looks to me like we should use 2 as the new default value.

**Comment by AndrzejKurek** [comment]
Added a fix here: https://github.com/Mbed-TLS/mbedtls/pull/7169
