### ISSUE TITLE
Add getters for some fields

### ISSUE THREAD

**Issue by soldatkin** [Mbed-TLS/mbedtls#6840]
### Suggested enhancement
Hello, could you please add getters for next private fields of structures
file     - ssl.h
struct - mbedtls_ssl_context
field   - hostname

file     - ssl.h
struct - mbedtls_ssl_config 
field   - endpoint

file     - ssl_cache.h
struct - mbedtls_ssl_cache_context
field   - mutex
field   - chain

file     - ssl_cache.h
struct - mbedtls_ssl_cache_entry
field   - timestamp
field   - next

file     - ssl_cache.h
struct - mbedtls_ssl_cache_context
field   - timeout

file     - rsa.h
struct - mbedtls_rsa_context
field   - len

### Justification

Mbed TLS needs this because 

These fields are used in our code, which provides a tls channel to the client application

**Comment by mpg** [comment]
Thanks for your report. I'm labeling "bug" and scheduling for the next release as this looks like a usability regression in 3.0

**Comment by mpg** [comment]
> file - ssl.h struct - mbedtls_ssl_context field - hostname

I don't understand why you need a getter for that. This will always have the value passed by the application to `
mbedtls_ssl_set_hostname()`. So, can't the application just remember what it passed to that function, instead of trying to read it back from the SSL context?

> file - ssl.h struct - mbedtls_ssl_config field - endpoint
> 
Same remark: this is what was passed to `mbedtls_ssl_conf_endpoint()`, so the application already knows it.

> file - ssl_cache.h struct - mbedtls_ssl_cache_context field - mutex field - chain
> 
> file - ssl_cache.h struct - mbedtls_ssl_cache_entry field - timestamp field - next
> 
> file - ssl_cache.h struct - mbedtls_ssl_cache_context field - timeout

Taking a step back, what are you doing with the cache that makes you want to access those? I'd like to point out that the provided `ssl_cache` is just an example covering the most basic use cases, but the coupling with the rest of SSL is very loose, so if it doesn't fit your needs you can also code up your own cache implementation and pass it to `mbedtls_ssl_conf_session_cache()`.

> file - rsa.h struct - mbedtls_rsa_context field - len

Don't we already have `mbedtls_rsa_get_len()` for that?

**Comment by lpy4105** [comment]
Hi @soldatkin, I'm working on getting this issue closed. 
It seems that the only remaining item is about `mbedtls_ssl_cache_xxx`. As @mpg pointed out,

>  The provided `ssl_cache` is just an example covering the most basic use cases, but the coupling with the rest of SSL is very loose, so if it doesn't fit your needs you can also code up your own cache implementation and pass it to `mbedtls_ssl_conf_session_cache()`.

My suggestion would be code up your own cache implementation since the cache structure is totally under your control.

> Why don't you use mbedtls_rsa_get_len MBEDTLS_PRIVATE macros in the API? As I see it, len is a private field, like function mbedtls_ssl_context_get_config in ssl.h

The private members of the structures are allowed to be accessed from `library`.

Please let me know if you have any further questions.

**Comment by gilles-peskine-arm** [comment]
> can't the application just remember what it passed to that function, instead of trying to read it back from the SSL context?

This is not convenient in an application that exchanges data on multiple SSL contexts simultaneously. When the application receives data on one context, it needs to figure out its own data associated with the context. It must anyway have some way of mapping the input event (e.g. file descriptor) to the SSL context, and that mapping can also let it access whatever other data it wants. But for data that's already in the SSL context, it saves memory and potentially complexity in the application if it doesn't have to store the data independently.

As long as we're confident that the data will remain easily accessible from the context, it's very cheap for us to provide a getter function. In terms of code size, a `static inline` function costs nothing if it's unused, and even a linkable version of it would be very small. In terms of library complexity, it's a one-liner, and unlikely to get more complicated in the future. In terms of compatibility commitment, there's very little risk as long as the way the information is stored doesn't change significantly — moving structures around would be fine, the only risk I can see is around memory management.

So:

* `endpoint`: no risk.
* `hostname`: this is a string so there is some risk around memory management. Either we provide a function that copies the host name (which is not a one-liner) or we provide a function that returns the pointer (which has a limitation on the pointer's validity). I think it's acceptable here to return the pointer stored in the context, so the data remains owned (in the Rust sense) by the context, and is invalidated by any future call to `set_hostname`, `session_reset` or `free`.
* cache `timestamp`: I think it's ok to provide a getter. I wouldn't necessarily want a setter there: should we really give the application that power?
* cache `timeout`: We already provide a setter. I don't see any problem with a getter. We should define the scale though. `int` looks like the wrong type, but the getter should probably be aligned with the setter.
* cache `chain`, `next`: this allows the application to traverse the entries. But it also forces the cache to remain a linear list, and I don't like making that commitment. Though realistically, the odds that we'll want to use a more sophisticated structure are low.
* cache `mutex`: I don't like giving access to that one. It commits us to a particular way to manage concurrency, and we do have plans to evolve here (changing the mutex abstraction).

For the cache, there's no point in giving access to fields if the application can't enumerate the entries. So I think the right solution would be to have a function that enumerates all the entries (in an unspecified order) and calls a callback function on each entry.

```
typedef int (*mbedtls_ssl_cache_callback_t)(mbedtls_ssl_cache_entry *entry, void *param);
// Call func on each entry in unspecified order.
// Stop if func returns a nonzero value and return that value.
// If func always returns 0, return 0.
int mbedtls_ssl_cache_iterate(mbedtls_ssl_cache_context *cache, mbedtls_ssl_cache_callback_t func, void *param);
```

**Comment by lpy4105** [comment]
- `endpoint` and `hostname`: It's fine for me to add the getters if there is no specific considerations that we should not have a getter for a specific field. But it still looks strange that an application don't record the `endpoint` and `hostname` itself instead of query the tls settings.
- cache `timeout`: It's OK to add the getter.

For the cache, as far as I understand it, the `ssl_cache.c` is an example not an abstraction of cache, so our implementation shouldn't cover all the use cases.

> For the cache, there's no point in giving access to fields if the application can't enumerate the entries.

I agree, and similarly there's neither no point in enumerating the entries if the application can't access the fields. So, I think what we need is an API to remove/invalidate `cache_entry` from the `list` by the `session id`.

**Comment by lpy4105** [comment]
Two PRs are added for this issue:
- Adding getters: https://github.com/Mbed-TLS/mbedtls/pull/7216
- Cache entry removal: https://github.com/Mbed-TLS/mbedtls/pull/7217
