### ISSUE TITLE
https://github.com/Mbed-TLS/mbedtls/archive/refs/tags/v2.28.1.tar.gz sha256 mismatch with release note

### ISSUE THREAD

**Issue by miktsai** [Mbed-TLS/mbedtls#6984]
### Summary

https://github.com/Mbed-TLS/mbedtls/releases/tag/v2.28.1
https://github.com/Mbed-TLS/mbedtls/archive/refs/tags/v2.28.1.tar.gz

download does not match its stated sha256.

sha256sum mbedtls-2.28.1.tar.gz
b63d75d12f234d3474932525b6214f4ab20e13153393c389da6b3a1da3525156  mbedtls-2.28.1.tar.gz

Instead of 
6797a7b6483ef589deeab8d33d401ed235d7be25eeecda1be8ddfed406d40ff4
mentioned on the release note.

### System information

Mbed TLS version (number or commit id):  v2.28.1
Operating system and version: 
Configuration (if not default, please attach `mbedtls_config.h`): 
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): 
Additional environment information: 

### Expected behavior

Should match Sha256. Did something change?

### Actual behavior

Checksum mismatch. So we don't know what to trust.

**Comment by miktsai** [comment]
We happen to have an "older" matched .gz. So we dig a little.

# New one
gzip -v -l  mbedtls-2.28.1.tar.gz 
method  crc     date  time           compressed        uncompressed  ratio uncompressed_name
defla e2f551e0 Jan 30 23:36             3915664            26501120  85.2% mbedtls-2.28.1.tar

# Old one
method  crc     date  time           compressed        uncompressed  ratio uncompressed_name
defla e2f551e0 Jan 30 23:35             3914247            26501120  85.2% v2.28.1.tar

The tar itself seems the same, which is good it means the source was not modified, but the result gzip compressed a little worse in the new one. So it looks like something definitely changed. Some tooling or?

In any case, it would be nice to match the release note still because it provides extra comfort. Thanks.

**Comment by daverodgman** [comment]
Thanks for the report, I'll investigate.

**Comment by daverodgman** [comment]
Oh, it looks like the "older" one contains a tar named `v2.28.1.tar`, whereas the newer one contains a tar named `mbedtls-2.28.1.tar`.

These files are generated by GitHub based on tags - we use tags with both names (`v2.28.1` and `mbedtls-2.28.1`). If we set the release to use the `v...` name instead of the `mbedtls...` name at some point during the release process, it's possible that this is how the different file was created. If that is the case, this must have happened briefly around the date of the release, as we haven't touched these files since then. I don't remember that happening but it's possible.

**Comment by miktsai** [comment]
Sorry, I meant to respond earlier. This should be resolved now. The github had a rollback of git yesterday that caused mass problem on package checksum mismatch. It upgraded git that caused this to happen. This wasn't the only package.

https://github.com/bazel-contrib/SIG-rules-authors/issues/11#issuecomment-1409438954

Thanks for looking into this.
