### ISSUE TITLE
check_openssl_server_bug may be obsolete

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#7002]
In `compat.sh`, we exclude certain test cases with the function [`check_openssl_server_bug`](https://github.com/Mbed-TLS/mbedtls/blob/mbedtls-2.28.0/tests/compat.sh#L205):

```
# OpenSSL 1.0.1h with -Verify wants a ClientCertificate message even for
# PSK ciphersuites with DTLS, which is incorrect, so disable them for now
check_openssl_server_bug()
{
    if test "X$VERIFY" = "XYES" && is_dtls "$MODE" && \
        echo "$1" | grep "^TLS-PSK" >/dev/null;
    then
        SKIP_NEXT="YES"
    fi
}
```

This did not exclude (EC)DHE-PSK cipher suites. In https://github.com/Mbed-TLS/mbedtls/pull/6902#discussion_r1092472176 we find that at least with semi-recent OpenSSL (1.1.1f) (EC)DHE-PSK suites work.

The goal of this task is:

1. Determine whether the bug is still present in the versions of OpenSSL we use for testing (legacy=1.0.1j, default=1.0.2g, next=1.1.1).
2. If the bug is resolved in all versions we use, remove `check_openssl_server_bug` altogether.
3. If the bug is resolved in 1.0.2g but present in 1.0.1j, maybe remove `check_openssl_server_bug` and add ad hoc exclusions where needed in `all.sh` (depending on how often it's needed).
4. If the bug is present in 1.0.2g, modify `check_openssl_server_bug` to only skip if openssl is too old (e.g. if it's present in 1.0.2g but not 1.1.1, we might skip only if openssl is older than 1.1.1 — ideally we should find the exact version, but it's not worth spending more than a few minutes on that).

**Comment by yanrayw** [comment]
I'm not clear how to determine the bug directly except for looking at the source code, so I simply check the results by comment and uncomment `check_openssl_server_bug` in `compat.sh`.

1. In legacy version (openssl-1.0.1j), since `OpenSSL <1.0.2` [doesn't support DTLS 1.2](https://github.com/Mbed-TLS/mbedtls/blob/development/tests/compat.sh#L1022), DTLS 1.2 related tests would be skipped for legacy version. I think we could ignore legacy version in this issue. 

3. In default Openssl version (1.0.2g), the bug of PSK ciphersuites still exits. Attach following log as a reference to look at. 
Code is on the head of b20028b with minor modifications for display.

Keep `check_openssl_server_bug` and got
```
$ ./tests/compat.sh -m dtls12 -t PSK -p Openssl 
OpenSSL 1.0.2g  1 Mar 2016
m->O dtls12,no TLS_PSK_WITH_AES_128_CBC_SHA ............................. PASS
m->O dtls12,no TLS_PSK_WITH_AES_256_CBC_SHA ............................. PASS
O->m dtls12,no TLS_PSK_WITH_AES_128_CBC_SHA ............................. PASS
O->m dtls12,no TLS_PSK_WITH_AES_256_CBC_SHA ............................. PASS
m->O dtls12,yes TLS_PSK_WITH_AES_128_CBC_SHA ............................ SKIP
m->O dtls12,yes TLS_PSK_WITH_AES_256_CBC_SHA ............................ SKIP
O->m dtls12,yes TLS_PSK_WITH_AES_128_CBC_SHA ............................ PASS
O->m dtls12,yes TLS_PSK_WITH_AES_256_CBC_SHA ............................ PASS
------------------------------------------------------------------------
PASSED (8 / 8 tests (2 skipped))
```

Remove `check_openssl_server_bug` and got
```
yanwan04@a015546:/var/lib/ws/home/yanwan04/mbedtls$ ./tests/compat.sh -m dtls12 -t PSK -p Openssl 
OpenSSL 1.0.2g  1 Mar 2016
m->O dtls12,no TLS_PSK_WITH_AES_128_CBC_SHA ............................. PASS
m->O dtls12,no TLS_PSK_WITH_AES_256_CBC_SHA ............................. PASS
O->m dtls12,no TLS_PSK_WITH_AES_128_CBC_SHA ............................. PASS
O->m dtls12,no TLS_PSK_WITH_AES_256_CBC_SHA ............................. PASS
m->O dtls12,yes TLS_PSK_WITH_AES_128_CBC_SHA ............................ FAIL
  ! outputs saved to c-srv-5.log, c-cli-5.log
m->O dtls12,yes TLS_PSK_WITH_AES_256_CBC_SHA ............................ FAIL
  ! outputs saved to c-srv-6.log, c-cli-6.log
O->m dtls12,yes TLS_PSK_WITH_AES_128_CBC_SHA ............................ PASS
O->m dtls12,yes TLS_PSK_WITH_AES_256_CBC_SHA ............................ PASS
------------------------------------------------------------------------
FAILED (6 / 8 tests (0 skipped))
```
In c-srv-5.log, it prints `verify depth is 10, must return a certificate` which proves the bug is still present.

3. In next version(1.1.1a), the bug is resolved. See below

Code is on the head of b20028b with minor modifications for display.

Keep `check_openssl_server_bug` and got
```
$ ./tests/compat.sh -m dtls12 -t PSK -p Openssl 
OpenSSL 1.1.1a  20 Nov 2018
m->O dtls12,no TLS_PSK_WITH_AES_128_CBC_SHA ............................. PASS
m->O dtls12,no TLS_PSK_WITH_AES_256_CBC_SHA ............................. PASS
O->m dtls12,no TLS_PSK_WITH_AES_128_CBC_SHA ............................. SKIP
O->m dtls12,no TLS_PSK_WITH_AES_256_CBC_SHA ............................. SKIP
m->O dtls12,yes TLS_PSK_WITH_AES_128_CBC_SHA ............................ SKIP
m->O dtls12,yes TLS_PSK_WITH_AES_256_CBC_SHA ............................ SKIP
O->m dtls12,yes TLS_PSK_WITH_AES_128_CBC_SHA ............................ SKIP
O->m dtls12,yes TLS_PSK_WITH_AES_256_CBC_SHA ............................ SKIP
------------------------------------------------------------------------
PASSED (8 / 8 tests (6 skipped))
```

Remove `check_openssl_server_bug` and got
```
$ ./tests/compat.sh -m dtls12 -t PSK -p Openssl 
OpenSSL 1.1.1a  20 Nov 2018
m->O dtls12,no TLS_PSK_WITH_AES_128_CBC_SHA ............................. PASS
m->O dtls12,no TLS_PSK_WITH_AES_256_CBC_SHA ............................. PASS
O->m dtls12,no TLS_PSK_WITH_AES_128_CBC_SHA ............................. SKIP
O->m dtls12,no TLS_PSK_WITH_AES_256_CBC_SHA ............................. SKIP
m->O dtls12,yes TLS_PSK_WITH_AES_128_CBC_SHA ............................ PASS
m->O dtls12,yes TLS_PSK_WITH_AES_256_CBC_SHA ............................ PASS
O->m dtls12,yes TLS_PSK_WITH_AES_128_CBC_SHA ............................ SKIP
O->m dtls12,yes TLS_PSK_WITH_AES_256_CBC_SHA ............................ SKIP
------------------------------------------------------------------------
PASSED (8 / 8 tests (4 skipped))
```
Two additional tests passed which proves the bug is fixed. 

**Conclusion**: we have to modify `check_openssl_server_bug` to skip old versions (<1.1.1a in our case, I can't determine the bug was resolved in which Openssl version for a short time).
@gilles-peskine-arm Please take a look at above logs. Let me know if anything is wrong. Thanks!

**Comment by gilles-peskine-arm** [comment]
Thanks for the investigation. But after thinking about it overnight and confirming with Manuel, we should actually do this differently (and it makes this task useless, sorry).

When using a PSK cipher suite, there is no certificate verification. So when `$TYPE = PSK`, `$VERIFY` has no effect, except if the script or the tools have a bug related to option processing (as is the case here).

What we should do instead is change `compat.sh` to ignore `$VERIFY` when `$TYPE = PSK`. I'm going to file a task for that.
