### ISSUE TITLE
Extend test framework for Record Size Limit Extension

### ISSUE THREAD

**Issue by yanesca** [Mbed-TLS/mbedtls#7006]
### Suggested enhancement

Add a new test precondition option to ssl-opt.sh that only makes a test run if the available GnuTLS version supports Record Size Limit Extension. (Support has been added in version 3.6.8 according to the GnuTLS [website](https://www.gnutls.org/manual/gnutls.html))

OpenSSL is out of scope as they don't seem to support this extension yet (they have an open [issue](https://github.com/openssl/openssl/issues/8187) and a [PR](https://github.com/openssl/openssl/pull/18248) for it).

This should be done in a way consistent how we already do similar conditions. For example here is how TLS 1.3 support is detected in GnuTLS:
https://github.com/Mbed-TLS/mbedtls/blob/mbedtls-3.3.0/tests/ssl-opt.sh#L604-L621

And this is how it is used to filter tests:
https://github.com/Mbed-TLS/mbedtls/blob/mbedtls-3.3.0/tests/ssl-opt.sh#L11204

### Justification

Mbed TLS needs this because we are about to add Record Size Limit Extension and we need testing available as early as possible.

### Definition of Done

- [ ] Record Size Limit Extension support detection is added to ssl-opt.sh
- [ ] A new test case is added to ssl-opt.sh that passes but only runs if the available GnuTLS  version has Record Size limit extension (the sole purpose of this test case is to confirm that the new filter works)
- [ ] This new test runs in Travis CI (GnuTLS recent enough) and is skipped in Open CI (GnuTLS version too old)

**Comment by KloolK** [comment]
Having spent some time getting familiar with your CI infrastructure, I think the last of the three tasks has a mix-up between TravisCI and OpenCI:

The [three OpenCI images](https://github.com/Mbed-TLS/mbedtls-test/tree/master/resources/docker_files) build a recent GnuTLS from source (3.7.2)

TravisCI is used with the default Ubuntu 16.04 (xenial) or with Ubuntu 20.04 (focal) image depending on the job.
20.04 currently comes with GnuTLS 3.6.13: https://packages.ubuntu.com/focal/gnutls-bin

Can you confirm / adapt the task accordingly please?

Side note:
GnuTLS support for TLS 1.3 / the Record Size Limit extension seems to be available since 3.6.4 already:
https://gitlab.com/gnutls/gnutls/-/blob/gnutls_3_6_4/NEWS#L25

Thus, some of the TLS 1.3 tests should also be runnable in TravisCI. The reason why they currently don't, is that the ssl-opt.sh expects GNUTLS_NEXT_CLI and GNUTLS_NEXT_SERV to be defined and otherwise assumes that TLS 1.3 is not supported at all.

But it's probably not worth spending the time to change the TLS 1.3 detection logic in ssl-opt.sh, since the TLS 1.3 tests are run in OpenCI already?

**Comment by gilles-peskine-arm** [comment]
About the CI:

* On Travis, we run `ssl-opt.sh` on Ubuntu 20.04 focal which has GnuTLS 3.6.13, with none of the `GNUTLS_xxx` variables set.
* On Linux on Jenkins, we run `ssl-opt.sh` with `GNUTLS_CLI` and `GNUTLS_SERV` pointing to GnuTLS 3.4.10 (regardless of the Ubuntu version), and `GNUTLS_NEXT_CLI` and `GNUTLS_NEXT_SERV` pointing to GnuTLS 3.7.2. (There is no reference to `GNUTLS_NEXT_` in `all.sh`, but the environment variable is set by Docker and passed through.)

So indeed the tests requiring GnuTLS ≥3.6.4 should be runnable in both Travis and Jenkins, as long as they use `GNUTLS_NEXT_xxx` if set and `gnutls-xxx` otherwise.

The logic to select what to run in `ssl-opt.sh` is not ideal, and improvements are welcome. We'd like to gradually move to having fixed assumptions about what LEGACY/∅/NEXT versions can do, to checking what `${GNUTLS,OPENSSL}_xxx` can do and running whatever test cases is possible. However, there is a downside to this more flexible approach: if we get the logic wrong, or if we have requirements that aren't actually met in our CI environment, then we might end up with test cases that don't run at all. For this, we are working on a mechanism to ensure that every test case runs at least once, but it's incomplete (currently it emits a non-fatal warning, because we have a backlog of excusable cases).

So in the short term, `ssl-opt.sh` should assume that `GNUTLS_NEXT_xxx` is available and can do TLS 1.3. On Travis, I guess the best solution would be to set `GNUTLS_NEXT_xxx`, and if there are test cases that require GnuTLS more recent than 3.6.13, exclude those with `ssl-opt -e`.

**Comment by KloolK** [comment]
Thanks for the explanation @gilles-peskine-arm

I created a PR that does not change any of the established detection logic for now to keep it simple.
