### ISSUE TITLE
Legacy MBEDTLS_PK_PARSE_C and MBEDTLS_PK_WRITE_C dependencies in test_suite_psa_crypto

### ISSUE THREAD

**Issue by paul-elliott-arm** [Mbed-TLS/mbedtls#7055]
The dependencies on MBEDTLS_PK_PARSE_C and MBEDTLS_PK_WRITE_C in this file are legacy problems — since 3.0, if the user just enables MBEDTLS_PSA_CRYPTO_C and MBEDTLS_PSA_CRYPTO_CONFIG and the requisite PSA_WANT_xxx symbols, that should be enough.

All tests in test_suite_psa_crypto with MBEDTLS_PK_PARSE_C and MBEDTLS_PK_WRITE_C dependencies need their dependencies redone with the requisite PSA_WANT_xxx.

**Comment by mpg** [comment]
Note: while I agree with the issue, users aren't require to set `MBEDTLS_PSA_CRYPTO_CONFIG` - we need to work both with and without it. (That's one of the annoying list of options that we need to support both on and of for the time being, and that should be always on at some indefinite point in the future, when the transition period is finally over and everything is always based on PSA Crypto all the time.)

It doesn't change the fact that this test suite should only have `PSA_WANT_xxx` dependencies and that the details of what (combination of) `PSA_WANT_` macro necessitates which `MBEDTLS_` thing to be auto-enabled should be managed internally (most likely in `include/mbedtls/config_psa.h`).

**Comment by mpg** [comment]
Note: we already auto-enable PK (including parse + write) in `build_info.h` when RSA and PSA Crypto are enabled: https://github.com/Mbed-TLS/mbedtls/blob/development/include/mbedtls/build_info.h#L90

So, I think those dependencies are always satisfied. As a result, I recommend the following course of action:

1. Mass-remove them.
2. Check if anything breaks - hopefully nothing, otherwise investigate and fix.

This can be applied not just to `test_suite_psa_crypto` but to all other `test_suite_psa_crypto*` test suites.

Additionally, as a clean-up, in `psa_crypto_rsa.c` we can remove the `#if defined(MBEDTLS_PK_WRITE_C` because it is always true thanks to the bit in `build_info.h`.

**Comment by valeriosetti** [comment]
@mpg
Suggestion: since we are changing dependencies in test, shall we use `outcome-analysis.sh` as a verification that we're not missing something that was tested in the past?

**Comment by mpg** [comment]
I don't think we can cause any test to be skipped by simply removing dependency declarations. If however we find ourselves adding new dependency declarations or modifying how existing ones are expressed, then indeed we should run `outcome-analysis.sh`. Anyway, running it even when we shouldn't need it doesn't hurt, except for the time it takes to run it of course.

**Comment by valeriosetti** [comment]
> Additionally, as a clean-up, in `psa_crypto_rsa.c` we can remove the `#if defined(MBEDTLS_PK_WRITE_C` because it is always true thanks to the bit in `build_info.h`

Sorry, but I am not very favorable to this change. If `psa_crypto_rsa.c` has a strict dependency for something that is guarded from `MBEDTLS_PK_WRITE_C` I prefer to keep the `#if defined(MBEDTLS_PK_WRITE_C` guard there. Maybe that this is satisfied automatically for now, but it is due to some "external" configuration that might change in the future. I prefer to keep things explicit.
@mpg  wdyt?

**Comment by mpg** [comment]
I think that `#if`s that are always true can be confusing, so if we keep it I'd like to add a comment along the lines of "Currently this is always true due to the fact that build_info.h auto-enables MBEDTLS_PK_WRITE_C whenever both PSA and RSA_C are enabled."
