### ISSUE TITLE
Build without assembly optimization fails on x64 due to AESCE being enabled

### ISSUE THREAD

**Issue by guidovranken** [Mbed-TLS/mbedtls#7234]
### Summary

Currently the no assembly build of Cryptofuzz on OSS-Fuzz is failing. It complains about AESCE being enabled, while this is a x64 system. Shouldn't AESCE be disabled by default on x64?

The reproduction steps below still used to work a while ago.

### System information

x64 Ubuntu with Clang

### Expected behavior

No build failure.

### Actual behavior

Build failure:

```
/home/jhg/cf-mbed/mbedtls/include/mbedtls/check_config.h:74:2: error: #error "MBEDTLS_AESCE_C defined, but not all prerequisites"
   74 | #error "MBEDTLS_AESCE_C defined, but not all prerequisites"
```

### Steps to reproduce

```sh
git clone --depth 1 -b development https://github.com/ARMmbed/mbedtls.git
cd mbedtls/
scripts/config.pl set MBEDTLS_PLATFORM_MEMORY
scripts/config.pl set MBEDTLS_CMAC_C
scripts/config.pl set MBEDTLS_NIST_KW_C
scripts/config.pl set MBEDTLS_ARIA_C
scripts/config.pl unset MBEDTLS_HAVE_ASM
scripts/config.pl unset MBEDTLS_PADLOCK_C
scripts/config.pl unset MBEDTLS_AESNI_C
mkdir build/
cd build/
cmake .. -DENABLE_PROGRAMS=0 -DENABLE_TESTING=0
make -j$(nproc)
```

**Comment by gilles-peskine-arm** [comment]
`MBEDTLS_AESCE_C`, like `MBEDTLS_AESNI_C` or `MBEDTLS_PADLOCK_C`, has no effect on the compiled code when building for an architecture other than the one that can have the feature. On other architectures, `aesce.o`, `aesni.o` and `padlock.o` are empty.

But they do have an effect on compile-time processing. Specifically, they can trigger compile-time errors through the checks in `mbedtls_config.h`, and also a warning about memory sanitizers in `aesni.c`. Those two checks are not gated by the target architecture.

The warning in `aesni.c` should be moved down to be under `MBEDTLS_HAVE_X86_64`.

The checks in `mbedtls_config.h` should also be gated by the architecture, but they depend on more elaborate macros that aren't defined in public headers. I'm not sure what the best solution is here: reproduce those macros? Move the `#error` into a header in `library`? (In fact we _could_ move the whole `check_config.h` into `library`: there's no need to check the configuration when building an application — it must be the same as when building the library, otherwise applications are likely to misbehave in mysterious ways.)

Note that this is a preexisting bug (or at least annoyance) for `MBEDTLS_AESNI_C` and `MBEDTLS_PADLOCK_C`, so we should probably fix 2.28 too.

**Comment by gilles-peskine-arm** [comment]
I'm adding this to the epic for the upcoming release because it's a regression. If we can't agree quickly on a proper fix that encompasses AESNI, we should at least make a quick fix that works for AESCE.

**Comment by guidovranken** [comment]
Thanks, for now I've fixed it on OSS-Fuzz by disabling AESCE as well (https://github.com/google/oss-fuzz/pull/9892) so for me there's no rush to fix it.

**Comment by gilles-peskine-arm** [comment]
After some internal discussion, our definition of done for this issue is:

We edit check_config.h to only check AESCE_C && !HAVE_ASM under a condition that's equivalent to the current definition of MBEDTLS_HAVE_ARM64 (which can be done by copying that or by defining MBEDTLS_HAVE_ARM64 in build_info.h).

After the release, we follow up with https://github.com/Mbed-TLS/mbedtls/issues/7236 to fix the preexisting issue with AESNI and PADLOCK.
