### ISSUE TITLE
Code Size: AES Encrypt Only: Determine configurations

### ISSUE THREAD

**Issue by tom-cosgrove-arm** [Mbed-TLS/mbedtls#7367]
(maybe below the line)

Gather list of AES-related configuration macros.

Look for "can we exclude AES decrypt if only these ones set"

DoD: We know which macros to examine to know if we can disable AES decryption code

The work in #2891 can be used as a reference

Related:

* #7368
* #7369
* #7370

**Comment by gilles-peskine-arm** [comment]
With the mbedtls legacy API, that's a tricky one because single-block processing (what we call ECB mode) is always available. You can't tell from the existing configuration macros whether the application wants single-block processing in both directions, only for encryption, or not at all. So I don't see a way to get around adding a configuration option `MBEDTLS_AES_ONLY_ENCRYPT` or `MBEDTLS_CIPHER_ONLY_ENCRYPT` as in #2891 (which might be incompatible with `MBEDTLS_CIPHER_MODE_CBC` and `MBEDTLS_CIPHER_MODE_XTS` for simplicity).

With the PSA API, the `PSA_WANT_xxx` mechanism doesn't distinguish between encryption and decryption. But ECB mode has to be requested explicitly (and there is no API for single-block processing). So “do I need decryption?” can be approximated as “is a mode with decryption enabled?”.

The modes that require both directions are ECB, CBC and XTS. The modes that require only encryption are CFB, OFB and CTR.

**Comment by tom-cosgrove-arm** [comment]
> The modes that require both directions are ECB, CBC and XTS. The modes that require only encryption are CFB, OFB and CTR.

Also encryption-only should be GCM and CCM, as they're based on CTR mode

**Comment by yuhaoth** [comment]
I think that should be an internal option. If MBEDTLS_CIPHER_MODE_CBC and MBEDTLS_CIPHER_MODE_XTS are disabled and GCM or CCM is enabled, AES decrypt should be disabled.

**Comment by tom-cosgrove-arm** [comment]
> I think we should go with CIPHER_ENCRYPT_ONLY for following reasons.

Agreed
