### ISSUE TITLE
[G1] Code Size: AES Encrypt Only: Implementation

### ISSUE THREAD

**Issue by tom-cosgrove-arm** [Mbed-TLS/mbedtls#7368]
(maybe below the line)

Implement an internal macro MBEDTLS_AES_NO_DECRYPT

DoD: when this configuration set, decryption code is configured out, and code size reduced comparably to TF-M's implementation

The work in #2891 can be used as a reference

Prerequisite:

* https://github.com/Mbed-TLS/mbedtls/issues/7367

Follow-ups:

* https://github.com/Mbed-TLS/mbedtls/issues/7369
* https://github.com/Mbed-TLS/mbedtls/issues/7370

**Comment by valeriosetti** [comment]
I was reading the description of this issue since I'm the reviewer of the associated PR (#8124) and I have a question about the name of the new symbol. IIRC I have been told in the past that MbedTLS usually prefers additive symbols rather than negating ones, so instead of `MBEDTLS_AES_NO_DECRYPT` I would expect `MBEDTLS_AES_DECRYPT`.
Of course I don't think this changes much for the final implementation since it just inverts the logic, but I thought it might be helpful to keep a similar pattern for all the symbols.

**Comment by gilles-peskine-arm** [comment]
> MbedTLS usually prefers additive symbols rather than negating ones

Yes, it's simpler both for users and for maintainers if all configuration options are “I want this thing”, rather than a mixture of “I want this thing”, “I don't want this thing”, “I want this thing but only if that other thing is enabled”, etc. Although sometimes it's good not to take things too far, for example we do want a simple way to say “I want all AES key sizes” without having to separately enable AES-128, AES-192 and AES-256.

However, another important consideration is backward compatibility. We already have `MBEDTLS_AES_C` meaning “I want AES”, so if we create separate options, we need to keep that at least as a backward compatibility alias for “I want AES in both directions”.

This still allows us to define an option `MBEDTLS_AES_ENCRYPT_ONLY` which enables AES-encrypt without enabling full AES. (We don't want to support builds with only AES decryption, because it would be a very uncommon requirement.) Note how this is slightly different from a `MBEDTLS_AES_NO_DECRYPT` that is ignored if `MBEDTLS_AES_C` is disabled.

I think that's what we should do. It would be essentially the same amount of work, but a little simpler both for implementers and for users. For users because there's less complexity (just declare what you use). For users transitioning, the transition would be to replace `MBEDTLS_AES_C` by `MBEDTLS_AES_ENCRYPT_ONLY`, rather than add `MBEDTLS_AES_NO_DECRYPT`. For implementers because dependencies would either be on `MBEDTLS_AES_C` or `MBEDTLS_AES_ENCRYPT_ONLY` (or their PSA-aware equivalents) and not on `MBEDTLS_AES_C && !MBEDTLS_AES_NO_DECRYPT`.

**Comment by gilles-peskine-arm** [comment]
@tom-cosgrove-arm I was just looking at https://github.com/Mbed-TLS/mbedtls/pull/8124 and I'm a bit confused, given that it does not introduce `MBEDTLS_AES_NO_DECRYPT` as the issue requests. I'm also confused whether this is meant to become a public option or not.

**Comment by mpg** [comment]
> This still allows us to define an option `MBEDTLS_AES_ENCRYPT_ONLY` which enables AES-encrypt without enabling full AES. (We don't want to support builds with only AES decryption, because it would be a very uncommon requirement.) Note how this is slightly different from a `MBEDTLS_AES_NO_DECRYPT` that is ignored if `MBEDTLS_AES_C` is disabled.

I'll note that's what #8124 is currently doing is much closer to what you call `MBEDTLS_AES_NO_DECRYPT`.

I think we want to avoid backwards compatibility issues we need to keep the meaning of `AES_C` unchanged: when you enable it you get all functions from `aes.h`. Then we add a new option, say `MBEDTLS_AES_LIGHT` or `MBEDTLS_AES_ENCRYPT`that on its own only enables a subset of `aes.c`. (Naming note: the name should not say "only" because that's wrong: if you define both the new option and `AES_C` then you get the full `aes.c` as usual.)

Then in `config_adjust_legacy_from_psa.h`, instead of always enabling `AES_C` for anything that needs AES, we need to be more careful and choose if we need to enable only the new option, or the full `AES_C`.

Note: I think if we want that to work for more than just AES, we'll need a new option per module (Aria, Camellia).
