### ISSUE TITLE
Code Size: baremetal libmbedcrypto: r624: SHA256_SMALLER

### ISSUE THREAD

**Issue by tom-cosgrove-arm** [Mbed-TLS/mbedtls#7373]
Bring in the changes from https://github.com/Mbed-TLS/mbedtls-restricted/pull/624

Expected saving: Text: 6743, Data: -24

**Comment by yanrayw** [comment]
With some investigation, there isn't any code size improvements by bringing in the changes from https://github.com/Mbed-TLS/mbedtls-restricted/pull/624. 

By default (with head of 03d557d), we got `Text: 6605` for `sha256.o`. 
```
mbedtls$ size library/sha256.o
   text	   data	    bss	    dec	    hex	filename
   6605	      0	      0	   6605	   19cd	library/sha256.o
```
If we simply replace `MBEDTLS_PUT_UINT32_BE` to a [static function](https://github.com/yanrayw/mbedtls/commit/98dd4cb1a45291f7cda309b2960325903e6a02f1), there is no code size change. That's because code size was improved from `Text: 6698` to `Text: 6554` withe the introduction of #6666. There isn't much code size improvements to be made unless we change how to put 32bits from a memory to another destination.

**Comment by yanrayw** [comment]
This issue is closed seeing https://github.com/Mbed-TLS/mbedtls/pull/7414#issuecomment-1507903055
