### ISSUE TITLE
Wrong order of dependency fixups in build_info.h

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#7420]
In `build_info.h`, we automatically enable some `MBEDTLS_xxx` features when they're required by another feature. When `MBEDTLS_PSA_CRYPTO_CONFIG` is enabled, some `MBEDTLS_xxx` features are enabled via `mbedtls/config_psa.h` based on `PSA_WANT_xxx`. But this is done after the ad hoc automatic enabling, so if `MBEDTLS_FOO` should auto-enable `MBEDTLS_BAR`, but `MBEDTLS_FOO` is auto-enabled based on `PSA_WANT_FOO`, then `MBEDTLS_BAR` doesn't get enabled as it should.

This concerns at least several modules requiring `MBEDTLS_MD_LIGHT` (since 3.4.0) and crypto modules requiring `MBEDTLS_PK_xxx` features (some dating as far back as 3.0.0 — there was no such thing in 2.x). The bug has been around since 3.0.0, but 3.4.0 made it worse (due to `MBEDTLS_MD_LIGHT`), so I am classifying this as a regression.

I think the correct fix is:

* In `build_info.h`, include `mbedtls/config_psa.h` before the ad hoc configuration tweaks.
* In `build_info.h`, add a note to warn that we must not auto-enable `MBEDTLS_xxx` features that `mbedtls/config_psa.h` would analyze when `MBEDTLS_PSA_CRYPTO_CONFIG` is disabled. I think we don't currently automatically enable something in `build_info.h` that `mbedtls/config_psa.h` analyzes.

Testing: it would be good to have a configuration that catches this on the CI, but this may be overkill. As an acceptance test, see TF-M below.

This is part of a more general problem around configuration fixups: https://github.com/Mbed-TLS/mbedtls/issues/7609.

----

From an internal report by @Summer-ARM. [Mbed TLS 3.4.0 broke TF-M](https://review.trustedfirmware.org/c/TF-M/trusted-firmware-m/+/20317), requiring a patch to manually enable `MBEDTLS_MD_LIGHT`. Steps to reproduce:

1. Download [TF-M](https://review.trustedfirmware.org/admin/repos/TF-M/trusted-firmware-m) at [d635cd0981999d762cd03bda4a3970f402996c13](https://review.trustedfirmware.org/plugins/gitiles/TF-M/trusted-firmware-m/+/d635cd0981999d762cd03bda4a3970f402996c13)
2. Discard `lib/ext/mbedcrypto/0008-Auto-enable-MBEDTLS_MD_LIGHT-after-MBEDTLS_PSA_CRYPT.patch`
3. `cmake -G "Unix Makefiles" -S . -B cmake_build -DTFM_PLATFORM=arm/mps2/an521 -DTFM_TOOLCHAIN_FILE=toolchain_ARMCLANG.cmake -DCMAKE_BUILD_TYPE=Debug -DTEST_NS=ON -DTEST_S=ON ../` — the build should succeed.

**Comment by minosgalanakis** [comment]
The breaking behaviour reported by this issue has been resolved by merged pr #7611 (which moved the inclusion before MD_LIGHT and adds a comment for user to check the defined symbols ). Also the requirements set by this issue are a minor subset of #7609 and #7615 .

I could further move the inclusion so that psa_crypto.h is done right after user configuration but before any auto-configuration takes place and could add a note to specically tell the user to verify the symbols when MBEDTLS_PSA_CRYPTO_CONFIG  is off. 

e.g

~~~~~~
/* User configurations here */
#include MBEDTLS_USER_CONFIG_FILE
......

/* ===> Set config_psa.h at that stage <==== */
#include "mbedtls/config_psa.h"
.....

/* Automatic configuration from this point onwards */
#define MBEDTLS_CTR_DRBG_USE_128_BIT_KEY

~~~~~~

Would that make sense @gilles-peskine-arm ? Or it shouldn't warrant a PR given that there are already two issues looking at the same area?

**Comment by gilles-peskine-arm** [comment]
@minosgalanakis I don't understand why you want to prioritize this patch compared to the other problems with the current order. I'd rather move on with https://github.com/Mbed-TLS/mbedtls/pull/7615, which is currently stuck due to a lack of time when there's enough development+review bandwidth to merge it without conflicts due to the ongoing work that's changing `config_psa.h`. So if you have time to work on this isuse, please review https://github.com/Mbed-TLS/mbedtls/pull/7615 (but I'll rebase it first, and request a freeze on `config_psa.h`, otherwise this is never going to get done).

**Comment by minosgalanakis** [comment]
Reopening since there is still a relevant PR pending.

**Comment by minosgalanakis** [comment]
Closing since the stale pr is only introducing a comment, not directly related to the the ask. If needed the pr can be cherry-picked 
-> [26cb4057 ](https://github.com/Mbed-TLS/mbedtls/pull/8094/commits/26cb405742b095dc3a82bfbf3c94bbccf3f887b1)
