### ISSUE TITLE
Mildly inconsistent types in PSA headers

### ISSUE THREAD

**Issue by irwir** [Mbed-TLS/mbedtls#7481]
For example, function declaration: https://github.com/Mbed-TLS/mbedtls/blob/53c6553deb552a91f7441fefc62272ba5b67d347/include/psa/crypto.h#L944
Definition: https://github.com/Mbed-TLS/mbedtls/blob/53c6553deb552a91f7441fefc62272ba5b67d347/include/psa/crypto_struct.h#L89
### Suggested enhancement
Definitions should use exactly the same types as declarations.

### Justification
Strictly speaking, data types written diffrently are different.

**Comment by gilles-peskine-arm** [comment]
> Strictly speaking, data types written diffrently are different.

According to the C language, they're the same, since `psa_hash_operation_t` is defined as a typedef for `struct psa_hash_operation_s`. So the declaration and the definition do use “exactly the same type”, even if this type is written out using a different sequence of tokens.

IIRC the reason this particular function (and similar ones in `crypto_struct.h`) uses `struct foo_s` is to give some flexibility in the header inclusion order, allowing `crypto_struct.h` to be included before the header that defines the name `psa_crypto_operation_t`. This flexibility is not currently needed, but might be needed if we reorganize headers. And there may be similar cases where the flexibility is needed. So I'd rather not make changes without a good reason.

**Comment by irwir** [comment]
It is possible to define types `volume` and `temperature` as floating point values. C compiler should allow to add `temperature` to `voulume`, then multiply the sum by a random `float distance` (no special typedef for this one ).

Also it seems that helper tools such as "Find declaration" or "Find definition" in compiler's IDE behave less reliably with differing definitions and declarations.

**Comment by paul-elliott-arm** [comment]
These are structures though, so you can't use a common type here.

Although it is slightly annoying that find declaration / definition won't work exactly correctly (although should take you straight to the typedef in the defined type, which then allows you to hop through to the other type) - this is as mentioned before a pattern we have used extensively throughout the library to allow flexibility in header include order (see previous post). I think here the flexibility outweighs inconvenience, and lets face it the amount of work it would take to change all of the instances, and uses thereof.

I'm therefore closing this, as I do not believe this is something we are prepared to implement.

**Comment by irwir** [comment]
> These are structures though, so you can't use a common type here.

This was not about user defined vs built-in types.
The point was: What is written differently might be different.
