### ISSUE TITLE
Address validation after memory access

### ISSUE THREAD

**Issue by irwir** [Mbed-TLS/mbedtls#7529]
https://github.com/Mbed-TLS/mbedtls/blob/14d6b1124bffbcefbacedeb6f6eba5c960abcc28/library/ssl_tls.c#L1158-L1159
The order of checks in the loop condition should be reversed.

**Comment by tom-daubney-arm** [comment]
Hi, thanks for the report.

Could you please explain your reasoning here a bit for me? I would like to understand why you think this and if this has caused an issue for you in your code.

As I understand so far:

`curve_list` is an array of type `mbedtls_ecp_group_id` which is an `enum` of group ids. Before entering this `for` loop, `curve_list` comes from the SSL config struct and has already been checked to make sure it is not `NULL` before being assigned, thus we know it has some valid contents. `length` is just a `size_t` that is being used as a loop counter in this for loop and it starts at `0`.
The job of this `for` loop is purely to determine the `length` of the `curve_list` array. `length` is the loop counter and is only incremented when `curve_list[length]` is not `MBEDTLS_ECP_DP_NONE` and it can't go beyond the max number of supported curves.

From the way the code is implemented else where it seems that `MBEDTLS_ECP_DP_NONE` terminates the `curve_list` array (but am struggling to definitively prove this because it has been deprecated and isn't used in the code, or examples much) and so the loop conditions seem ok.

The additional condition of ` (length < MBEDTLS_ECP_DP_MAX)` seems to be there as an additional sanity check to ensure we are not finding a length of greater than the max number of supported curves.

I don't think we are going to ever try to read off the end of the buffer, assuming that `curve_list` is terminated by `MBEDTLS_ECP_DP_NONE` so I am of the opinion that this looks ok.

Now if curve_list is malformed, and is not terminated correctly, then I can definitely see the argument that we should be checking` (length < MBEDTLS_ECP_DP_MAX)` first in the loop conditions. However, if we are trying to protect against malformed `curve_list` arrays then I don't think the loop conditions go far enough anyway to prevent a bad address access, which might be a separate issue.

Please let me know your thoughts. Thanks

**Comment by irwir** [comment]
For the array `curve_list[MBEDTLS_ECP_DP_MAX]` valid range of indexes is from `0` to `MBEDTLS_ECP_DP_MAX-1`.
With `length` equal to `MBEDTLS_ECP_DP_MAX` reading of `curve_list[length]` accesses memory beyond the array boundary.

**Comment by gilles-peskine-arm** [comment]
To confirm Tom's analysis: `MBEDTLS_ECP_DP_MAX` has nothing to do with the allocated size of `curve_list`, so the check `length < MBEDTLS_ECP_DP_MAX` has no impact on the validity of the memory access `curve_list[length]`. `curve_list` comes directly from `ssl->conf` and is set by [`mbedtls_ssl_conf_curves`](https://mbed-tls.readthedocs.io/projects/api/en/development/api/file/ssl_8h/#ssl_8h_1aa5f57bc7af0a5584764ef083be319c7e), which only passes a pointer to the zero-terminated array and not a size.

I do agree that the check on `MBEDTLS_ECP_DP_MAX` is weird though. It was added by #4859 which introduced the translation from `mbedtls_ssl_conf_curves` (only listing ECP curves, using Mbed TLS identitiers) to `mbedtls_ssl_conf_groups` (also accepting FFDH groups, and potentially later PQ KEM, all in the IANA encoding). It seems intended as a weak sanity check: if the curve list has more than `MBEDTLS_ECP_DP_MAX` entries then it must have invalid entries or duplicate entries. But it's a very weak sanity check: even a shorter list can have invalid or duplicate entries. Furthermore, if it is a sanity check, then if it fails, the function should return an error, not silently truncate the list.

So I think we should just remove this check.

**Comment by gilles-peskine-arm** [comment]
@irwir Where do you see that `curve_list` has the length `MBEDTLS_ECP_DP_MAX`? I can't think of a context where it would make sense. `MBEDTLS_ECP_DP_MAX` is the largest internal curve id, which currently happens to be the number of curves supported in the code (but might not be if we introduced a hole in the numbering for whatever reason). If there ever was an array meant to be sized to the number of curves, we'd want it to be sized by the number of curves supported in the _build_, so that disabling curves would save memory.

**Comment by gilles-peskine-arm** [comment]
@irwir Yes, but we don't have the memory size here. We'd have to change the API for that. And since `mbedtls_ssl_conf_curves` is deprecated, we aren't going to replace it by a safer API in the next major release: we're just going to remove it.

**Comment by gilles-peskine-arm** [comment]
> Reordered condititons is more natural and requires no deep code investigations and lengthy explanations to be typed here.

No, changing the order wouldn't help because `MBEDTLS_ECP_DP_MAX` has nothing to do with the allocated length of `curve_list`. In practice, `curve_list` is very likely to be shorter than `MBEDTLS_ECP_DP_MAX`, so reading until `MBEDTLS_ECP_DP_MAX` would be a buffer overread anyway.

**Comment by irwir** [comment]
> `curve_list` is very likely to be shorter than `MBEDTLS_ECP_DP_MAX`

What if curve_list is not shorter than `MBEDTLS_ECP_DP_MAX`?
Is it forbidded to use smaller value and save memory?

**Comment by gilles-peskine-arm** [comment]
It's possible to have a curve list that's longer than `MBEDTLS_ECP_DP_MAX`, but it would have to have duplicate or invalid values, so it would be pointless. It would waste, not save, memory.

**Comment by mpg** [comment]
> So I think we should just remove this check.

Agreed. Indeed it looks weird here, and is not really useful, so let's remove it to make the weirdness go away.

**Comment by irwir** [comment]
Declaration with initialization might be used:
>         size_t length = 0;
>         ...
>         for (; curve_list[length] != MBEDTLS_ECP_DP_NONE; length++);
