### ISSUE TITLE
OPC UA: add URI subtype verification for SubjectAltName extension

### ISSUE THREAD

**Issue by AndrzejKurek** [Mbed-TLS/mbedtls#7563]
Background:

- #7436 added verification of IP address subtype of SubjectAltName;
https://github.com/Mbed-TLS/mbedtls/pull/7025 added support for URI subtype of SubjectAltName;

The aim of this task is to:
- add URI verification in the same manner as the IP and dns subtypes are verified.
- determine whether an API change (extension?) is needed to not mix up URI and dns subtypes due to the ambiguous type of common name passed to `x509_crt_verify_name`;
- check the RFC's to see what order / mechanism of verification should be used when multiple SAN's are present;
- add tests for verification, both positive and negative, also with several matching / partially matching SAN's of various types.

**Comment by gilles-peskine-arm** [comment]
Do we need full compliance?

Generally, non-compliance is a bad idea, because if two implementations have different ideas as to whether a certificate is valid, that can enable attacks. However, it may be possible to fail in edge cases in a way that is safe in the scenarios where Mbed TLS is used. Of course this needs to be documented.

For example, RFC 5280 requires Unicode normalization. Mbed TLS does not have any knowledge of unicode and treats UTF8String strings as byte strings. This is fine on the verifier side: if the application passes non-normalized Unicode but the relying party presents normalized Unicode, the verifier will fail safe by rejecting the names as distinct. (This could be a denial-of-service in some scenarios where the application receives the non-normalized Unicode from a third party and for some reason cannot do the normalization itself.) This would be problematic if Mbed TLS was used in a CA in a way that allows separate registrations for distinct byte strings that would normalize to the same Unicode string.

**Comment by AndrzejKurek** [comment]
There was no request for full compliance so far.
The reason I'm suggesting bit-by-bit comparison is exactly because it will be used for verification: we might reject some valid certificates, but that's the same behaviour as we're having now. The caller can check an URI SAN themselves in the user callback if they notice an `MBEDTLS_x509_BADCERT_CN_MISMATCH` in flags.
