### ISSUE TITLE
Need mbedtls_aes_crypt_ctr() example code

### ISSUE THREAD

**Issue by zliucd** [Mbed-TLS/mbedtls#7618]
### Suggested enhancement
There  are examples of AES encryption/decryption using `ECB`, `CBC` and `GCM`, but example of `CTR`  is missing.

### Justification

Mbed TLS needs this because it would be helpful for users especially careful use of nonce and IV.

**Comment by minosgalanakis** [comment]
Given that this interface has been superseded by the PSA interface, and given the finite bandwidth, both development and community focus in the latter. 

This is a reasonable request though, so I would like to keep it open because we are always happily accepting contributions.

**Comment by ubersandro** [comment]
Hello everyone, I would like to start contributing to this project and I noticed this is a "good-first-issue". Is there any interest in it after 1 year? Thanks a lot for your time. 
Alessandro

**Comment by gilles-peskine-arm** [comment]
@ubersandro Thanks for offering! The `mbedtls_aes_` API will be removed in the next version of Mbed TLS, so this issue is no longer of much use. Only the long-time support branches will still have the functions. Furthermore this is a low-level function in the first place, which applications should not call. We should have sample programs showing how to use `mbedtls_cipher_xxx` in Mbed TLS 3.6, and showing `psa_xxx` in 3.6 and development/4.x.

If you're offering to work on sample programs, that would be great! Our sample programs need a lot of love. But not this one. The most urgent task regarding sample programs is to expand the sample programs for the PSA crypto API. We have `psa_hash`, `aead_demo` ([incomplete](https://github.com/Mbed-TLS/mbedtls/issues/8139)) and `hmac_demo` but lack sample programs for non-authenticated cipher and for asymmetric cryptography. Someone has already written PSA sample programs in https://github.com/Mbed-TLS/mbedtls/pull/5064, but we need some work to upstream them as has been done for the hash program in https://github.com/Mbed-TLS/mbedtls/pull/7942. I've filed https://github.com/Mbed-TLS/mbedtls/issues/9416 for that task.

**Comment by gilles-peskine-arm** [comment]
I'm closing this issue because adding example code for low-level APIs that are being removed is no longer relevant.
