### ISSUE TITLE
Partial old cipher suites not supported in `ciphersuite_definitions`

### ISSUE THREAD

**Issue by zliucd** [Mbed-TLS/mbedtls#7677]
### Summary
Some old (weak) cipher suites are not supported in ```static const mbedtls_ssl_ciphersuite_t ciphersuite_definitions[]``` (ssl_ciphersuites.c line 293), e.g., 

0x000a: TLS_RSA_WITH_3DES_EDE_CBC_SHA (https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml)

Sample code:
```
void test_old_ciphersuite()
{
    const mbedtls_ssl_ciphersuite_t *info;

    info = mbedtls_ssl_ciphersuite_from_id(0x000a);
    assert (info != NULL);      // panic here
}
```

I looked into ```mbedtls_ssl_ciphersuite_from_id()```, which looks up table ```ciphersuite_definitions```, and the table does not contain ```TLS_RSA_WITH_3DES_EDE_CBC_SHA```, so it returns NULL.

### System information

Mbed TLS version (number or commit id):  3.1.0

### Expected behavior
All valid cipher suites listed in https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml (approximately 340+) are expected to support.

### Actual behavior
See summary.

### Steps to reproduce
See sample code above.

**Comment by gilles-peskine-arm** [comment]
> All valid cipher suites listed in https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml (approximately 340+) are expected to support.

Sorry, this is not a reasonable expectation. Mbed TLS has never aimed to support _all_ cipher suites. For example it has never supported unauthenticated cipher suites, “export” weakened crypto, DSS (non-EC DSA), etc.

Mbed TLS 2.x supported 3DES cipher suites, but this was [removed](https://github.com/Mbed-TLS/mbedtls/issues/4367) in [Mbed TLS 3.0](https://github.com/Mbed-TLS/mbedtls/releases/tag/v3.0.0) because 3DES was already widely deprecated at that point.

In general, Mbed TLS does not aim to support weak cryptography. Mbed TLS does sometimes support weak cryptography, but that is typically only because there's no clear cutoff (e.g. minimum RSA or FFDH key size), or for legacy compatibility (e.g. Mbed TLS 3.x still supports DES to read encrypted private keys), or because it was historically supported and we haven't removed it yet (e.g. 192-bit ECC curves will go away in 4.0 — we only remove features when there's a major version change).

**Comment by zliucd** [comment]
@gilles-peskine-arm   Thanks for clarification. Is there a reference list of currently supported cipher suites (in addition to that appeared in source code)?

**Comment by gilles-peskine-arm** [comment]
That's a good question. No, I don't think we have this in our documentation. [`ssl_ciphersuites.c`](https://github.com/Mbed-TLS/mbedtls/blob/development/library/ssl_ciphersuites.c#L46) is the place to look.

**Comment by zliucd** [comment]
Hi Gilles,

I'm preparing to release a free software in binary, which uses mbedtls.
Can you give me a hint how to attach mbedtls license?

1. There are several other packets the software uses(e.g., boost), which
also requires attaching license.  How to give the name of each license and
notice file?

2. According to Apache Foundation, I must include Apache V2 license file
and also notice file.
https://www.apache.org/licenses/LICENSE-2.0.txt

Notice file  (how to give the file name? e.g., NOTICE-mbedtls)

Apache [mbedtls]
Copyright [XXXX-XXXX] The Apache Software Foundation

This product includes software developed at
The Apache Software Foundation (http://www.apache.org/).


Thanks!

Gilles Peskine ***@***.***> 于2023年6月2日周五 21:59写道：

**Comment by gilles-peskine-arm** [comment]
I'm sorry, I can't give legal advice. I'm an engineer, not a lawyer.

Unofficially — if you search the web for software that ships with a copy of the Apache license, or `/usr/share/doc/*/copyright` on an Ubuntu machine, you'll see plenty of examples.
