### ISSUE TITLE
Conversion function between raw and DER ECDSA signatures

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#7765]
There are two widespread formats for ECDSA signatures: fixed-size, or DER. The X.509 and TLS ecosystem and the legacy mbedtls API use the DER format. Most cryptoprocessors including Cryptoki (PKCS#11) and PSA Crypto use the fixed size format.

Converting between the two formats is awkward. We should offer an API for it, at least to facilitate the life of code (including our own X.509/TLS code) that needs the X.509/TLS format and wants to use the PSA API.

Goals of this issue (which may be broken down into sub-issues):

* Design the ECDSA signature format conversion API.
* Implement and test it.
* Make sure that we're using the new functions inside the library rather than an ad hoc implementation. (Some of our code uses the ECDSA functions that expose (r,s) as bignums rather than formatting them as a byte string; this may be the right choice sometimes.)
* List it in the upcoming PSA transition guide.

**Comment by gilles-peskine-arm** [comment]
I think that in terms of API design, this one should stay simple:

```
int mbedtls_ecdsa_raw_to_der(const unsigned char *raw, size_t raw_len,
                             unsigned char *der, size_t der_size, size_t *der_len);
int mbedtls_ecdsa_der_to_raw(const unsigned char *der, size_t der_len,
                             unsigned char *raw, size_t raw_size, size_t *raw_len);
```

Should these functions be gated by `MBEDTLS_PSA_CRYPTO_C`?

But as an extra wrinkle, for the purpose of implementing the PSA API, it would be more convenient to have conversions between the raw format and a pair of bignums. These are not functions we want in the external interface: they're bridges inside our crypto library, not relevant to drivers. So do they belong in `ecdsa.c` or in `psa_crypto_ecp.c`?

**Comment by gilles-peskine-arm** [comment]
I wonder if these should be functions to convert ECDSA signatures, or functions to convert signatures in general between the PSA format and the X.509 format. Those formats are the same for RSA and [for EdDSA](https://datatracker.ietf.org/doc/html/draft-josefsson-pkix-eddsa-04#section-6). We don't know yet whether they'll be the same for PQ algorithms.

**Comment by gilles-peskine-arm** [comment]
Just dropping a note that the absence of this function has caused an Arm user to spend some time implementing it, plus our time supporting them. The application in question was originally written for RSA only, and switching to ECDSA led to gaps in key parsing and signature parsing. The application is not TLS or X.509, so the pk API was not a convenient bridge.

**Comment by mpg** [comment]
Note for whoever implements this: we already have internal functions that mostly do this, except with an API that's not clean enough to just make them public as-is:
- [`extract_ecdsa_sig()`](https://github.com/Mbed-TLS/mbedtls/blob/90d07118ad0108b9d1f61524173d801c6e8ce781/library/pk_wrap.c#L696)
- [`pk_ecdsa_sig_asn1_from_psa()`](https://github.com/Mbed-TLS/mbedtls/blob/90d07118ad0108b9d1f61524173d801c6e8ce781/library/pk_wrap.c#L936)

**Comment by mpg** [comment]
> > But as an extra wrinkle, for the purpose of implementing the PSA API, it would be more convenient to have conversions between the raw format and a pair of bignums. These are not functions we want in the external interface: they're bridges inside our crypto library, not relevant to drivers. So do they belong in `ecdsa.c` or in `psa_crypto_ecp.c`?
> 
> I think both are OK, with a slight preference for `psa_crypto_ecp.c` since we already have `library/psa_crypto_ecp.h` but no internal ECDSA header.

On second thought, they clearly don't belong in `psa_crypto_ecp.h` - as Valerio pointed out privately, this is for the built-in implementation of EC algs. While the new functions should be available regardless of whether ECC is built-in or provided by a driver.

On top of that, they should be declared in a public header (that's kinda the whole point of this task), so `library/psa_crypto_ecp.h` was clearly never the right place.

This leave us with:
- `ecdsa.h` + `ecdsa.c` - now feels wrong for the same reason as `psa_crypto_ecp`: the functions should be available even when `ECDSA_C` is undefined and ECDSA provided by a driver. We could carve an exception, but I'd rather avoid that if we can.
- ``mbedtls/psa_util.h` + `psa_util.c` - now feels like the best choice. That's also where we have newly-introduced metadata conversion functions, so this feels like a good place.

**Comment by mpg** [comment]
> * Should `to_der` write to the end of the buffer or to is beginning?

In the meantime I convinced myself it should write the the beginning of the buffer: https://github.com/Mbed-TLS/mbedtls/pull/8657#discussion_r1436395847

> > Should we pass the curve family as well, even though it isn't necessary for ECDSA?
> > [...]
> > I wonder if these should be functions to convert ECDSA signatures, or functions to convert signatures in general between the PSA format and the X.509 format.
> 
> I'm inclined to make this ECDSA-only for now, and not pass unnecessary parameters. We don't know what the constraints of other formats will be yet, and what information they'll need.

Looks like Gilles and I are in agreement on this: https://github.com/Mbed-TLS/mbedtls/pull/8657/files#r1436396199

**Comment by mpg** [comment]
> > > But as an extra wrinkle, for the purpose of implementing the PSA API, it would be more convenient to have conversions between the raw format and a pair of bignums. These are not functions we want in the external interface: they're bridges inside our crypto library, not relevant to drivers. So do they belong in `ecdsa.c` or in `psa_crypto_ecp.c`?
> > 
> > 
> > I think both are OK, with a slight preference for `psa_crypto_ecp.c` since we already have `library/psa_crypto_ecp.h` but no internal ECDSA header.
> 
> On second thought, they clearly don't belong in `psa_crypto_ecp.h` - as Valerio pointed out privately, this is for the built-in implementation of EC algs. While the new functions should be available regardless of whether ECC is built-in or provided by a driver.

Ah, I should read what I'm quoting: the initial question was about extra internal functions converting between raw and a pair of bignum, which are internal and not relevant to drivers as clearly stated... So, for those functions, I still think `psa_crypto_ecp.c` would be the right place. (More than `ecdsa.c` because raw is the format used by PSA, not by legacy.)

My comment above was about the main functions that this issue is about (public and should work regardless of whether ECDSA is provided by drivers or built-in).

**Comment by valeriosetti** [comment]
## Introduction to implemented PR

So far we have 3 different implementation (PRs) for this issue:

1. https://github.com/Mbed-TLS/mbedtls/pull/8681 -> implements required ECDSA conversion functions using ASN1 functions for parsing and writing DER data. 
2. https://github.com/Mbed-TLS/mbedtls/pull/8696 -> same as (1), but in this case ASN1 functions are re-implemented also in `psa_util`. This is done in order to have the possibility to exclude ASN1 module in some super constrained build, but still benefit of the relevant functionalities. OTOH this also cause partial code duplication when conversion functions are enabled and `MBEDTLS_ASN1_[WRITE|PARSE]_C` is enabled.
3. https://github.com/Mbed-TLS/mbedtls/pull/8703 -> same as (1), but proper guards are added to the ASN1 module so that relevant functions are still available for ECDSA conversion even if `MBEDTLS_ASN1_[WRITE|PARSE]_C` are disabled.

## Footprint comparison

Footprint tests are performed with Ubuntu 20.04 Docker image and with the following commands/scenarios:
- `./tests/scripts/all.sh build_arm_none_eabi_gcc_m0plus` -> build with the `baremetal_size` configuration which has `MBEDTLS_ASN1_[WRITE|PARSE]_C` enabled.
- `./mtest -S` (in case extra parameters are required, a specific note is added to list them) -> build with TFM configuration, which does not have ASN1 support enabled.

Here the size (in bytes) of `libmbedcrypto.a` for the above scenarios:

|| #8681 | #8696 | #8703 |
|---|---|---|----|
| build_arm_none_eabi_gcc_m0plus | 222600 | 222748 | 222600 |
| mtest | 36298[^1] | 33972 | 34040 |

[^1]: add `MBEDTLS_ASN1_WRITE_C MBEDTLS_ASN1_PARSE_C` to the command line

## Analysis
TODO

**Comment by mpg** [comment]
I really the version in #8703, as I think it achieves the best of both worlds (no duplication, no dependency/re-enabling of full ASN.1 parse/write). Also, I hadn't noticed before reviewing that PR, but the two functions we need are already handled in a special way, so this is and even smaller change to the ASN.1 modules than I anticipated.

@gilles-peskine-arm Wdyt?
