### ISSUE TITLE
Access private members of struct mbedtls_x509_crl 

### ISSUE THREAD

**Issue by ademyankov** [Mbed-TLS/mbedtls#7852]
Hello,

a struct below now declares some members as private:

```
typedef struct mbedtls_x509_crl
{
    mbedtls_x509_buf MBEDTLS_PRIVATE(sig);
}

```

Q: How would I access those members without patching the library?

### System information

mbedtls-3.4.0
Ubuntu 22.4

P.S. not sure what was the reason/purpose of doing that, don't want to be rude, but I don't think it is a smart decision. There is no such thing as private members of a stuct in C language. There is an old C-saying about using macros and other stuff: "don't invent your own language". If something needs to be private then it should have been hidden behind the private interface/struct implementation.

Now I have a bunch of code that cannot be upgraded with the new version of the library.

**Comment by gilles-peskine-arm** [comment]
> How would I access those members without patching the library?

1. Preferably, use the API functions, following their documentation.
2. If the API functions are insufficient for your use case, either open a discussion on the mailing list, or open an issue with a specific requirement. Not just “I want to access this field” but “I want to do X and I would like to do it by accessing this field in this way”.
3. At your own risk, use `MBEDTLS_PRIVATE(field_name)`. But if you do that, we make no guarantee that your code will work with the next release of Mbed TLS (including security updates).

> There is no such thing as private members of a stuct in C language

Indeed, that is one of the limitations of the language. That's why we make members private via documentation rather than via a language feature. Just like, for example, functions that expect a pointer to a valid value express this through documentation and not just through their prototype.

>  If something needs to be private then it should have been hidden behind the private interface/struct implementation.

That's impossible when the compiler needs to know the size. As an embedded library, we try to limit the needs for dynamic memory allocation (even if we're still far from supporting a malloc-less environment).

**Comment by ademyankov** [comment]
Fair enough! Thanks @gilles-peskine-arm
