### ISSUE TITLE
Protecting a client’s private key in mutual authentication TLS

### ISSUE THREAD

**Issue by ROMAINPC** [Mbed-TLS/mbedtls#7889]
### Suggested enhancement
Hi, according to this [documentation](https://mbed-tls.readthedocs.io/en/latest/kb/how-to/ssl_async/) MbedTLS allows you to customize the signature and encryption functions used when establishing a TLS link. It would be nice to have the same functionality for client-side operations in the case of mutual authentication.

Is that possible to use `mbedtls_ssl_conf_async_private_cb(...)` similarly for the client ? Would it be necessary to create a second function or can this one be reused ? Client side, are there the same problems of asynchronicity than server side ?
With a little guidance I may be able to attempt this contribution.

### Justification

Mbed TLS needs this because protecting private keys in a crypto chip or in a trusted environment is a modern security solution. Some connected objects use TLS mutual authentication, acting as clients. Securing the private key of a device in the field is a real problematic.

**Comment by gilles-peskine-arm** [comment]
> protecting private keys in a crypto chip or in a trusted environment is a modern security solution

Nowadays we have a different way of doing this:

* Write a [PSA secure element driver](https://github.com/Mbed-TLS/mbedtls/blob/development/docs/psa-driver-example-and-guide.md).
* Build the library with `MBEDTLS_USE_PSA_CRYPTO` and point the TLS stack at the key that is in the secure element.

The tooling and documentation around drivers is still rough, please don't hesitate to ask if you need help with that.

Because we have this different approach, we are very unlikely to extend the `MBEDTLS_SSL_ASYNC_PRIVATE` feature.

**Comment by gilles-peskine-arm** [comment]
The async approach is beneficial in a server environment where threads are expensive and the server has a very large number of concurrent clients: it doesn't require a thread to block while it's waiting for the secure element. This is typically not a concern on the client side, which is why we're unlikely to address this requirement via a TLS feature when we (now) have a crypto stack that can address the security side of the requirement.

For this reason, I'm closing this feature request as “already supported, but in a different way”.

**Comment by ROMAINPC** [comment]
Thanks you @gilles-peskine-arm for your very clear explanation. I understand much better why this feature is called ASYNC.

I am actually looking to make an "opaque" driver, I will investigate this and the `MBEDTLS_USE_PSA_CRYPTO` option.
