### ISSUE TITLE
PSA driver functions return wrong type

### ISSUE THREAD

**Issue by AgathiyanB** [Mbed-TLS/mbedtls#7917]
### Summary

2 functions in scripts/data_files/driver_templates/psa_crypto_driver_wrappers.c.jinja have incorrect return types.

### Description

`psa_driver_wrapper_sign_hash_get_num_ops` and `psa_driver_wrapper_verify_hash_get_num_ops` return uint32_t. These are driver interface functions so they should probably return `psa_status_t`.

**Comment by paul-elliott-arm** [comment]
The problem here is slightly more complicated. The original functions that these wrap return a `uint32_t`, but of course the wrapper functions can return an error, which will be negative.

The number of operations these can return cannot be negative, so we have something of a conflict of interest. The only suggestion I have is to move the actual return value into a parameter and only return success/error.

The fact that this was not caught at compile time is another reason for having better warnings implemented.

**Comment by tom-cosgrove-arm** [comment]
> The number of operations these can return cannot be negative

How likely is the number of operations to be > `2^31 - 1` ?

**Comment by gilles-peskine-arm** [comment]
The scale is implementation-specific. Nobody's written drivers yet, and our own implementation doesn't get anywhere near 2^31 (it counts multiplications).

**Comment by tom-cosgrove-arm** [comment]
Could we specify this as being saturating - i.e. never returning a "successful" result of > `2^31 - 1`, so that we can then either (a) change the return type to `psa_status_t` and directly return errors, or (b) keep the return type as `uint32_t` but force error returns to give `0`?

Yes, this is a spec/API change, but clearly what we have is currently wrong, so it's a case of the least damaging change rather than "we have to leave it as is". Especially if we don't think there are many users right now.

**Comment by gilles-peskine-arm** [comment]
The API is beta, so we can change it. But I don't like overloading statuses with useful values. The PSA crypto API currently does that. Getters that can't fail return a value, and anything else returns a status.

I'm not sure if this driver entry point actually needs to return errors, or even exist at all. This is a case where it might be better not to follow the API exactly. But I don't have time to dig into it right now. It's just a detail that we can revisit when we revisit the interfaces, which we'll do anyway when we finish designing them (we've only done one-shot sign-hash but we also need multipart sign-message and key agreement).
