### ISSUE TITLE
gen_key example cannot generate x25519 keys

### ISSUE THREAD

**Issue by gtorres88** [Mbed-TLS/mbedtls#8091]
### Summary

When trying to generate a pub/priv key pair using Curve25519, the module fails with `OID is not found`

### System information

Mbed TLS version (number or commit id): 3.4.1
Operating system and version:  OSX Ventura 13.5
Configuration (if not default, please attach `mbedtls_config.h`): default
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): default settings on release
Additional environment information: 

### Expected behavior

I expected a key to be generated, but the program fails.

### Actual behavior

The program fails.

### Steps to reproduce

gabe.torres$ programs/pkey/gen_key type=ec ec_curve=x25519 format=der filename=keyfile.key

  . Seeding the random number generator...
  . Generating the private key ... ok
  . Key information:
curve: x25519
X_Q:   40802F093C3638D294FE7536BA12988CCD5A03E160A7FD094852AB2C041A371E
Y_Q:
D:     64EDC9DF9CD1213E64D26A28EDA7DAEA501B19D9D55D7200EE82078F2E0D7070
  . Writing key to file... failed
 - OID - OID is not found

**Comment by tom-cosgrove-arm** [comment]
Support for this is present in the `development` branch, presumably from #6838, and will be present in the next release

**Comment by gtorres88** [comment]
> Support for this is present in the `development` branch, presumably from #6838, and will be present in the next release

Thanks for the quick response. Does this mean the current mbedtls release is unable to generated EC key pairs using curve25519 or just that this example doesn't work?

I am trying to generate key pairs and generate a self signed x.509 cert using curve25519 and I'm having trouble getting the examples to work.

**Comment by gilles-peskine-arm** [comment]
_Generating_ Curve25519 keys has been present since the library started supporting them a very long time ago. What failed was _exporting_ the key in DER format, which will be supported in the next release.

> generate a self signed x.509 cert using curve25519

Curve25519 doesn't have an associated signature algorithm, so it's impossible to make a self-signed certificate for a Curve25519. You can make a proof-of-possession for a Curve25519, but it has to rely on encryption, not signature, and I don't know of a standard certificate-like format for that.

You can make a self-signed certificate for e.g. a secp256r1 key that is then used for ECDH, but the signature in the certificate is an ECDSA signature (that's bad hygiene, but generally believed to be secure). The same is not possible for Curve25519 since there's no ECDSA or similar on that curve. There's EdDSA on the mathematically related Ed25519 curve, but that's not the same curve and using the mathematical correspondance to perform a signature to attest a Curve25519 is not standard (and I don't know if it's secure).

If you need a proof-of-possession for a Curve25519, you can't use a certificate and you're dangerously close to designing your own cryptography. I recommend sticking to an existing, well-analyzed protocol.

**Comment by gtorres88** [comment]
@gilles-peskine-arm Thanks so much for the wisdom. I had incorrectly assumed that curve25519 and ed25519 were the same curve and that mbedtls would use EdDSA to sign the certificate. I think I will try to move to `secp256r1` instead for now.

If you could humor a couple more questions:

- Why do is self signing a cert using `secp256r1` and ECDSA bad hygiene?
- Does mbedtls support generating keys for `ed25519` and self signing a cert using EdDSA? I can't seem to get the PSA to work with twisted edwards curves

**Comment by gilles-peskine-arm** [comment]
> Why do is self signing a cert using secp256r1 and ECDSA bad hygiene?

A certificate for a secp256r1 key that's self-signed using ECDSA is fine. The bad hygiene is if you use that key with an algorithm other than ECDSA.

> Does mbedtls support generating keys for ed25519 and self signing a cert using EdDSA?

No. Mbed TLS doesn't support Edwards curves and EdDSA yet. We have a contribution for it but it isn't merged yet because we don't have the time to review it.

**Comment by gtorres88** [comment]
Thank you so much @gilles-peskine-arm , this was really helpful
