### ISSUE TITLE
Bit length of generated EC private key is less than bit length of order of group

### ISSUE THREAD

**Issue by rrajbe** [Mbed-TLS/mbedtls#8233]
### Summary
When I generate the EC keypair using `mbedtls_ecp_gen_keypair` API, for `MBEDTLS_ECP_DP_SECP256R1` curve, the bitlength of the private key varies from 250 to 256;

I thought that the bit length of the EC private key must be equal to bit length of the order of the group.
Could anyone help me to understand the correct behavior here?

### System information

Mbed TLS version (number or commit id): 5edb9427086a4cdc8e567bb8069db9d09a58e21b
Operating system and version: OSX
Configuration (if not default, please attach `mbedtls_config.h`): 
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): clang
Additional environment information: 

### Expected behavior
The bit length of the generated EC private key must be equal to bit length of the order of the group.

### Actual behavior
The bit length of the generated EC private key varies.

### Steps to reproduce
`    

    int err = 0;
    size_t outlen = 0;

    mbedtls_mpi private_key;        mbedtls_mpi_init(&private_key);
    mbedtls_ecp_point public_key;   mbedtls_ecp_point_init(&public_key);
    mbedtls_ecp_group ecp_grp;      mbedtls_ecp_group_init(&ecp_grp);

    err = mbedtls_ecp_group_load(&ecp_grp, MBEDTLS_ECP_DP_SECP256R1);
    if (err) {
        printf("Error in mbedtls_ecp_group_load: [%d]", err);
        return -1;
    }

    err = mbedtls_ecp_gen_keypair(&ecp_grp, &private_key, &public_key, mbedtls_test_rnd_pseudo_rand, NULL);
    if (err) {
        printf("Error in mbedtls_ecp_gen_keypair: [%d]", err);
        return -1;
    }

    assert ( mbedtls_mpi_bitlen(&private_key) == mbedtls_mpi_bitlen(&ecp_grp.N));

`

**Comment by yanesca** [comment]
> I thought that the bit length of the EC private key must be equal to bit length of the order of the group.

That is not the case. It only has to be greater than 0 and less than the order of the group.

From [SEC 1](https://www.secg.org/sec1-v2.pdf), section 3.2.1 "Elliptic Curve Key Pair Generation Primitive":

> Randomly or pseudorandomly select an integer d in the interval [1, n − 1].

I am going to close this issue, but please feel free to comment if you need more information, or reopen if you still think that there is an issue.

**Comment by rrajbe** [comment]
Understood; Thanks for the information.

**Comment by gilles-peskine-arm** [comment]
In cryptography, the “length” or “size” of a number is sometimes the size of an actual value (exact sense: a B-bit number is between 2^(B-1) and (2^B)-1), and sometimes the space needed to store any permitted value (at-most sense: a B-bit number is between 0 and (2^B)-1). You have to check carefully to know which meaning applies.

The function `mbedtls_mpi_bitlen` returns the bit-length in the exact sense. You can't tell the bit-length in the at-most sense from an MPI value because the at-most sense is not a property of a number, it's a property of a collection of numbers.

ECC private keys are values between 1 and n-1 where n is the curve order. For secp256r1, the curve order is slightly less than 2^256, i.e. n is a 256-bit number in the exact sense. A private key has a nearly 1/2 chance for its top bit to be 0 vs 1, so it's a 256-bit number in the at-most sense but it's only a 256-bit number in the at-most sense about half the time, a 255-bit number (top 2 bits are 0) about 1/4 of the time, a 254-bit number (top 3 bits are 0) about 1/8 of the time, etc. Revealing the value of top bits would be revealing part of the private key.

> I thought that the bit length of the EC private key must be equal to bit length of the order of the group.

Beware also that the order of the curve (n) and the order of the group (p) are not the same. Private keys are a number on the curve, while public keys are a pair of coordinates and each coordinate is a number in the group. There's a mathematical theorem that states that they must be nearly equal, but it's possible for their exact bit-length can differ by 1 bit. For most common curves they happen to be the same, but Mbed TLS supports one deprecated curve (sec224k1) where p is slightly less than 2^224 while n is slightly more than 2^224.

**Comment by yanesca** [comment]
> Beware also that the order of the curve (n) and the order of the group (p) are not the same. Private keys are a number on the curve, while public keys are a pair of coordinates and each coordinate is a number in the group.

I think instead of group it is better to say field, as when we talk about elliptic curves and say group, most people think of the group of curve points with respect to point addition and not the additive group of the coordinate field.
