### ISSUE TITLE
Make unit tests thread safe

### ISSUE THREAD

**Issue by yanesca** [Mbed-TLS/mbedtls#8343]
### Suggested enhancement

Tasks:
- In order to avoid deadlocks, `MBEDTLS_TEST_MUTEX_USAGE` wrappers should check their parameter and only do their thing if it is not the mutex protecting `mbedtls_test_info`. If it is, they just let through the call to the Mbed TLS platform function.
- Protect the global structure `mbedtls_test_info` with a mutex, preferably by adding setters and getters for the fields, which take and release the mutex.
- ~Protect calls to `mbedtls_snprintf` in the test framework with a mutex, preferably by adding a wrapper that takes and releases the mutex.~

Remarks:
- Make small PRs: the two can go in two separate PRs and the second can be broken down by subsets of fields if needed
- In each PR add a test where the newly protected functions are called directly and concurrently
- ~The mutex is a pthreads mutex and not an Mbed TLS mutex (to avoid deadlock) and as such, must be conditional on `MBEDTLS_THREADING_PTHREAD`~ 

### Justification

Mbed TLS needs this because we are adding [multi-threaded unit tests](https://github.com/Mbed-TLS/mbedtls/pull/8342) and we don't want spurious failures or scrambled output.

**Comment by gilles-peskine-arm** [comment]
> Protect calls to mbedtls_snprintf in the test framework with a mutex

Do you mean all calls to this function? In which case, why? I would expect all calls to this function to be thread-safe. As far as understand, it's guaranteed for standard library functions by C11 (N1570 §7.1.4/5:

> Unless explicitly stated otherwise in the detailed descriptions that follow, library
functions shall prevent data races as follows: A library function shall not directly or
indirectly access objects accessible by threads other than the current thread unless the
objects are accessed directly or indirectly via the function’s arguments. A library
function shall not directly or indirectly modify objects accessible by threads other than
the current thread unless the objects are accessed directly or indirectly via the function’s
non-const arguments.

And even for non-C11-compliant standard libraries, I wouldn't expect `snprintf` to use static objects.

Or do you mean protecting the calls to `mbedtls_snprintf` where the target is a field in `test_info`? In which case, that's covered by the first bullet point.

> The mutex is a pthreads mutex and not an Mbed TLS mutex (to avoid deadlock) and as such, must be conditional on MBEDTLS_THREADING_PTHREAD

I don't understand that part. Why could there be a deadlock with an mbedtls mutex, that can be avoided by directly using a pthreads mutex? On a pthreads platform, I would expect the mbedtls mutex to remain a thin wrapper around a pthreads mutex.

**Comment by yanesca** [comment]
> Do you mean all calls to this function? In which case, why?

I want the writes to be atomic for easier reading and understanding. As far as I remember with standard `printf` the following sequence is possible:
1. thread 1 writes first half of its buffer
2. thread 2 writes first half of its buffer
3. thread 1 writes second half of its buffer
4. thread 2 writes second half of its buffer

(Strictly speaking this is not a data race, but still not optimal.)

> I don't understand that part. Why could there be a deadlock with an mbedtls mutex, that can be avoided by directly using a pthreads mutex?

The Mbed TLS mutex has a test wrapper that accesses `test_info` when `MBEDTLS_TEST_MUTEX_USAGE` is on. Alternatively, we could add a new compile time flag and make it mutually exclusive with `MBEDTLS_TEST_MUTEX_USAGE` or make the saved, unwrapped Mbed TLS mutex platform functions global and use those directly (`mutex_functions` in `tests/src/threading_helpers.c`). Using pthread mutexes directly seams simpler to me and since in the unit tests we use pthreads directly anyway in the short to mid term (the available tooling is pthreads specific), this seems like an acceptable constraint.

**Comment by gilles-peskine-arm** [comment]
> with standard printf the following sequence is possible (…)

Is this about `printf` and `fprintf`, rather than `snprintf`? We don't normally call `printf` during unit tests (only after each unit test is complete), so I don't see a need to protect it.

> `MBEDTLS_TEST_MUTEX_USAGE`

This option was intended to perform some simple validations of mutex usage in single-threaded programs. If we have multi-threaded tests, then in principle we don't need `MBEDTLS_TEST_MUTEX_USAGE`. Still, `MBEDTLS_TEST_MUTEX_USAGE` deterministically finds a limited set of problems, whereas multi-threaded tests non-deterministically find a much larger set of problems. The deterministic nature means that `MBEDTLS_TEST_MUTEX_USAGE` remains useful. But we could turn it off in some builds or in some tests if it's problematic when the tests are actually multithreaded.

If we want to keep `MBEDTLS_TEST_MUTEX_USAGE`, I guess its wrappers should skip the mutex that protects `test_info`. We aren't interested in testing the usage of mutexes inside the test framework anyway.

> the available tooling is pthreads specific

Specifically, `MBEDTLS_TEST_MUTEX_USAGE` is conditioned on `MBEDTLS_THREADING_PTHREAD`. The reason is that it needs to store some data in a mutex object (structure field `mbedtls_threading_mutex_t`), and this is compatible with `MBEDTLS_THREADING_PTHREAD` but not with `MBEDTLS_THREADING_ALT` (because that comes with a custom definition of the type `mbedtls_threading_mutex_t`). `MBEDTLS_THREADING_PTHREAD` but not with `MBEDTLS_THREADING_ALT` are the only two alternatives. This is just an API compatibility problem, it's not that the `MBEDTLS_TEST_MUTEX_USAGE` implementation has any particular requirement on pthreads (it doesn't call any pthreads function or make any assumption on how the mutexes work).

**Comment by yanesca** [comment]
> If we want to keep MBEDTLS_TEST_MUTEX_USAGE, I guess its wrappers should skip the mutex that protects test_info.

I agree, that was my intent too. The two ways I can think of doing that is using pthread directly, or making the saved platform functions global and using those. Did you mean that the wrappers should check whether the parameter is the mutex protecting `test_info` and dispatch to the platform function without doing anything else?

**Comment by gilles-peskine-arm** [comment]
> RECORD_STATUS

That's a pretty obscure feature meant to help measure test coverage. It doesn't need to be compatible with multithreading.

> Did you mean that the wrappers should check whether the parameter is the mutex protecting test_info and dispatch to the platform function without doing anything else?

Yes, that was my idea. I favor it because it keeps the complexity of `MBEDTLS_TEST_MUTEX_USAGE` contained.

**Comment by yanesca** [comment]
> the available tooling is pthreads specific

By this I mostly meant that the suitable tooling like TSan, Helgrind, DRD all only work with pthreads and the threading unit tests will need to use API for creating and destroying threads that is not in the platform abstraction anyway.

**Comment by paul-elliott-arm** [comment]
Breaking out https://github.com/Mbed-TLS/mbedtls/issues/8473 and https://github.com/Mbed-TLS/mbedtls/issues/8474 into seperate issues. This issue is basically reliant on both of them, however.
