### ISSUE TITLE
Nginx support 

### ISSUE THREAD

**Issue by zliucd** [Mbed-TLS/mbedtls#8465]
Hi,

I'm not sure if Mbedtls supports Nginx with source building.  Nginx uses some SSL-level APIs from openssl, and is it possible to build Nginx with Mbedtls?

Thanks.

**Comment by tgonzalezorlandoarm** [comment]
Hello @zliucd !

For third-party Mbed TLS integrations like Nginx, could I suggest you ask this via the Nginx forum?

In addition, for the future, questions of the sort are better suited for the mailing list ( mbed-tls@lists.trustedfirmware.org ) (except for third party integrations, as already mentioned).
We are closing this issue here and are happy to discuss your future questions from the mailing list :)
