### ISSUE TITLE
Implement test cases indicating that known vulnerabilities are absent

### ISSUE THREAD

**Issue by mschulz-at-hilscher** [Mbed-TLS/mbedtls#8597]
### Suggested enhancement

There is a list of [Security Advisories](https://mbed-tls.readthedocs.io/en/latest/security-advisories/) indicating which mbedTLS versions are affected by a particular vulnerability. Some vulnerabilities were introduced in a particular version so that older versions might not be affected, however, this is not fully documented (see https://mbed-tls.readthedocs.io/en/latest/security-advisories/mbedtls-security-advisory-2023-10-1/, for example). Additionally, only because a vulnerability was fixed once, does not guarantee that will will be reintroduced in future versions, maybe due to refactoring, ...

Hence, I would like to have test cases that proof the absense of all known mbedTLS vulnerabilities. They shall be executable via the test framework. Users can then check if their, maybe, old mbedTLS versions are affected or not and as part of integration tests verify whether potential workaround are correctly applied.

### Justification

Mbed TLS needs this because testing for the absense of known security vulnerabilities becomes more important during system development.

**Comment by gilles-peskine-arm** [comment]
> Additionally, only because a vulnerability was fixed once, does not guarantee that will will be reintroduced in future versions, maybe due to refactoring, ...

Whenever we fix a bug, including security vulnerabilities, we add a non-regression test if it's practical. So there's nothing more we can do here.

> Some vulnerabilities were introduced in a particular version so that older versions might not be affected

For vulnerabilities that are severe enough to warrant advisory, the advisory will mention in which version the vulnerability was introduced. We at least go back on the supported branches (currently: 2.28.x and 3.x), and often even going back to unsupported branches. But only to a reasonable extent — we wouldn't chase it all the way back to XySSL!

> see https://mbed-tls.readthedocs.io/en/latest/security-advisories/mbedtls-security-advisory-2023-10-1/, for example

That bug was present in all versions of Mbed TLS that are currently supported. From my analysis notes, it was also present in the 2.16 branch, which has been out of support for two years. I didn't check earlier versions.

> I would like to have test cases that proof the absense of all known mbedTLS vulnerabilities. They shall be executable via the test framework.

I'm sorry but this is not realistic. We can't offer support for all older versions of the library. Backporting non-regression tests often involves backporting auxiliary code in the test framework. I'm afraid we (the Mbed TLS development team) don't have time for that.

If you want more support for older versions of Mbed TLS, that would be a conversation to have inside [Trusted Firmware](https://www.trustedfirmware.org/about/), which defines the general policies that we follow. This could happen if there's enough interest. My personal impression (I am not a spokesman for Arm, just an engineer!) is that the effort would have to come largely from outside Arm.

**Comment by gilles-peskine-arm** [comment]
I am closing this issue because we're already doing what we can realistically do.

**Comment by mschulz-at-hilscher** [comment]
Hi @gilles-peskine-arm,
I did not want to request a ready backport of those tests for all older versions. Just to have a test case available that we could backport on demand. Is there any test case available for https://mbed-tls.readthedocs.io/en/latest/security-advisories/mbedtls-security-advisory-2023-10-1/, if yes, where do we find it and could it be referenced somewhere in the advisory?

We checked the code from mbedtls 2.16 and it seems that there is a length check included that was removed in later versions (see: https://github.com/Mbed-TLS/mbedtls/blob/cf4667126010c665341f9e50ef691b7ef8294188/library/ssl_tls.c#L2096). Hence, we asked our-selves whether 2.16 is affected or not.
