### ISSUE TITLE
Wrong value for macro in oid.h

### ISSUE THREAD

**Issue by amodw** [Mbed-TLS/mbedtls#8622]
### Summary
MBEDTLS_OID_EC_ALG_UNRESTRICTED is set to "\x02\01". If I am not mistaken, it should be "\x02\x01" (with an additional 'x').

### System information
Mbed TLS version 3.5.0

**Comment by bensze01** [comment]
Hi, thanks for the report!

Fortunately, while the macro definition is slightly ugly as-is, it is functionally correct.

[`\x01` is a hexadecimal escape sequence while `\01` is an octal escape sequence](https://en.cppreference.com/w/c/language/escape) - but since 1 is smaller than 8, they both represent the same byte.
