### ISSUE TITLE
Uninstall doesn't seem to be working

### ISSUE THREAD

**Issue by cpp77** [Mbed-TLS/mbedtls#8785]
Hi I've installed mbedtls using `make` and `make install` on Ubuntu 22.04. However, when I try to uninstall using `sudo make uninstall` it doesn't seem to do anything. There's no confirmation of libraries removed etc.

Then when I do `sudo apt-get install -y libmbedtls-dev` it says there's nothing to install.

How do I remove my installation built from source?

**Comment by tgonzalezorlandoarm** [comment]
Hello ! Thanks for your comment.

We currently deal with support requests through our mailing list [mbed-tls@lists.trustedfirmware.org](mailto:mbed-tls@lists.trustedfirmware.org). I am closing this issue because this is not the correct channel for support requests but we are happy to deal with this question on the mentioned mailing list.

Thanks
