### ISSUE TITLE
 psa_generate_key() returned -27648 (-0x6c00) 

### ISSUE THREAD

**Issue by Tuxist** [Mbed-TLS/mbedtls#9046]
### Summary

Hi,

i got a psa_generate_key() returned -27648 (-0x6c00) when I try to join with https client.

my code is there:

https://tuxist.de/git/jan.koester/libnetplus

usaged by:

https://tuxist.de/git/jan.koester/libhttppp

required for libhtttppp example apps:

https://tuxist.de/git/jan.koester/libhtmlpp

for debugging is used the the example applications.

### System information

Mbed TLS version (number or commit id):   master
Operating system and version:  Debian 12
Configuration (if not default, please attach `mbedtls_config.h`): 
Compiler and options (if you used a pre-built binary, please indicate how you obtained it):  GCC 12
Additional environment information: 

### Steps to reproduce
mkdir libnetplus/build
cd libnetplus/build
cmake ../
make
sudo make install

cd ..
cd ..
cd libhtmlpp
mkdir libhtmlpp/build
cmake ../
make
sudo make install

cd ..
cd ..
cd libhttppp
mkdir libhttppp/build
cmake ../
make
sudo make install

to run the test:
gdb --args ./examples/httphello -a 0.0.0.0 -p 8443 -c /etc/blogi/blogi.crt -k /etc/blogi/blogi.key

**Comment by gilles-peskine-arm** [comment]
That error code is `MBEDTLS_ERR_SSL_INTERNAL_ERROR`. It's unfortunate that we're [printing an internal translated code rather than the actual returned value](https://github.com/Mbed-TLS/mbedtls/issues/9047).

I haven't tried to reproduce the failure or looked at your code, but at a guess: this might be the first PSA function that accesses the key store or the RNG. Have you [called `psa_crypto_init`](https://mbed-tls.readthedocs.io/projects/api/en/development/api/file/ssl_8h/?highlight=psa_crypto_init#_CPPv417mbedtls_ssl_setupP19mbedtls_ssl_contextPK18mbedtls_ssl_config)? If that's the problem, `psa_generate_key` returns `PSA_ERROR_BAD_STATE` (-137).

**Comment by Tuxist** [comment]
thanks that was the problem :-)
