### ISSUE TITLE
UBSan gives runtime error with PSA Multipart AEAD (Gcm) / Buffer sharing

### ISSUE THREAD

**Issue by paul-elliott-arm** [Mbed-TLS/mbedtls#9064]
### Summary

During the multipart tests we often call  `psa_aead_update_ad()` with a valid pointer but with zero length (to test the multipart functionality we break down all parts into bits).

Unfortunately, the buffer sharing fixes will turn this into a NULL pointer with zero length, which will then trigger undefined behaviour in `mbedtls_gcm_update_ad()`, when the zero length is added to a NULL pointer.

I'm entirely not sure of the best way to fix this. Is it ok to just return `PSA_SUCCESS` if `psa_aead_update_ad()` gets called with zero length? There is, after all, nothing to be done, and I'm not keen on altering the gcm code for no apparent reason.

I have *no* idea why this was not found on the CI before, perhaps this is because I am running newer compilers. You may be pleased to know that after making a quick fix for this, I couldn't find any more.

**Comment by gilles-peskine-arm** [comment]
> Is it ok to just return PSA_SUCCESS if psa_aead_update_ad() gets called with zero length?

Yes. This has come up before with other algorithms, and the solution tends to be to skip early after determining that there's nothing to do.

> I have no idea why this was not found on the CI before, perhaps this is because I am running newer compilers.

Yes, that's because we do UBSan (“Asan”, but we always activate UBSan and ASan together) runs on the CI only with older compilers. Modern UBSan detects more incorrect uses of null pointers. The task to update our test scripts is https://github.com/Mbed-TLS/mbedtls/issues/6610. I even started work on a [fix](https://github.com/Mbed-TLS/mbedtls/pull/6614), but it's probably bitrotted heavily by now.
