### ISSUE TITLE
Why doesn't Mbed-TLS consider supporting DSA?

### ISSUE THREAD

**Issue by jchx-c** [Mbed-TLS/mbedtls#9318]
### Justification

Mbed TLS needs this because

**Comment by gilles-peskine-arm** [comment]
Finite-field DSA pretty much died when the key ECC patents expired or were opened up and everyone started moving to ECDSA. It's been over a decade now. We will not support finite-field DSA in Mbed TLS because so far the only demand we've had for it is for projects that wanted to completely implement some standard where DSA is an alternative, but in practice end users would have used RSA or ECDSA anyway.

I'm surprised this is coming up in 2024. Why do you want DSA?
