### ISSUE TITLE
Complex initializers to zero in crypto_struct.h

### ISSUE THREAD

**Issue by irwir** [Mbed-TLS/mbedtls#9466]
https://github.com/Mbed-TLS/mbedtls/blob/aacbc622a45177e75963600053b44cb277a6e315/tf-psa-crypto/include/psa/crypto_struct.h#L84-L88

There is a number of special initializer macros like the quoted above.
While the goal is only to fill structure with zeros, the same result could be achieved without conditional directives, necessity of counting commas and placing braces according to structure declarations.
According to C standards, trivial `{ 0 }` should clear structures equally well.
Is there a reason to keep things the way it is?

**Comment by gilles-peskine-arm** [comment]
Because [gcc < 4.7](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1AB9U8lJL6yAngGVG6AMKpaAVxYMQAJi%2BkHAGTwGTAA5dwAjTGI9AAdUBUJbBmc3D29fOISbAUDgsJZI6K4LTCtshiECJmICFPdPHxKypMrqglzQiKi9BSqaurTG3raO/MKJAEoLVFdiZHYOXuJXawBqAFIAdgAhIIJV1XWAZm3VvdWAT2PtrYARVYUNo/ut7Y076/WNAEEOKdpOABWXiebi8VCcRwPGZzTAbLxHHikAiaP5TADW3kB%2Bk4khBqNIEI4vAUIA0yNRUzgsCQaBYMToUXIlDpDPo0WQwEkADZpDRaAQoqSIOECeEgtULpwkeLmMQLgB5cLaTDWaW8OlsQQKhi0KUcLSkLDhVzARxiWiksFGzAsQzAcQG3j4YiqmwAN0wVsNmFUqtcgvV5EEpQJtDw4WIkucWAJBGIeBYQc9xHC8Uwt1t9vDRkpfAMwAUADU8JgAO4KmKMAn8QQiMTsKQyQSKFTqJ2kXTFAy50zGczh8KkyBTVAxcpWgC0AHULasZ7740xwSmE1hhxAppY3Ul7AwnC56noAkFOgVusVMokBANPJf4teGKMukUmjuBK1%2Boe0sVt9YWn07SnmMF4WIBt49IBz7nkUW4wvMkw4hwwKkKChpEgcAAc3KTryqzAMgyCrJIAB03IkZIqwQLghAkPCiITLwKJOhMGJYkheKoQSRIkmSFIsaQ1KICAMwEDEAbMhArKMsQISsAsqjYbhlEEURXBHCRXi8Jg%2BBEGuei1sIojiE2hmtmoBJdqQZZRjE6r/EC%2BIdkSCoBuJ%2ByoFQWE4XhqnEWRFFUc49IyfRXCMfxWisaQmJeKRACciVJclyXchxTnoZwvHksxUWCTAwlUAWCiSdJ7IAGLFZwM5zguqhLhqqAheyclsJwik%2BSphGrFImnabpJB4OgBmyPWJl8rI5ntoaVnxpgmBDWSDnIRl4KcJmVSMugqzBWyUSrJVTCFt5yn4d1pHkZR1EDcQYWkDtTV7bd6wIuFTGUmxXjYgCHCcWha3EhYfG5WiSFaVxzlZZFoMpgkdiSEAA) and [clang < 6](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1AB9U8lJL6yAngGVG6AMKpaAVxYMQAJi%2BkHAGTwGTAA5dwAjTGI9AAdUBUJbBmc3D29fOISbAUDgsJZI6K4LTCtshiECJmICFPdPHxKypMrqglzQiKi9BSqaurTG3raO/MKJAEoLVFdiZHYOXuJXawBqAFIAdgAhIIJV1XWAZm3VvdWAT2PtrYARVYUNo/ut7Y076/WNAEEOKdpOABWXiebi8VCcRwPGZzTAbLxHHikAiaP5TADW3kB%2Bk4khBqNIEI4vAUIA0yNRUzgsCQaBYMToUXIlDpDPo0WQyAMRkBGl8NFoBCipIg4QJ4SC1QunCREuYxAuAHlwtpMNYZbw6WxBIqGLRpRwtKQsOFXMBHGJaKSwcbMCxDMBxIbePhiGqbAA3TDWo2YVRq1xCjXkQSlAm0PDhYhS5xYAkEYh4FjBr3EcLxTC3O0OiNGSl8AzABQANTwmAA7oqYowCfxBCIxOwpDJBIoVOpnaRdMVuSYzPpI6TIFNUDFytaALQAdUtq2nfoTTHBqcTWCHECmlndSXsDCcLnqegCQU6BW6xUyiQEA08F/iV4Yoy6RSa24ErX6B7SxS31hafXaE8xnPCwAJvHoAKfM8ik3GF5kmHEOGBUhQSNIkDgADgANgnLDJFWLkHVWQEADoNBIrxVggXBCBIeFEQmXgUWdCYMSxRC8RQgkiRJMkKRY0hqUQEAZgIGJA2ZCBWUZYgQlYBZVGw3D8OATlVi4I4KN4TB8CIVc9DrYRRHEZtDLbNQCW7Uhy2jGINX%2BIF8U7IlFUDcT9lQKhMJwvCCN7YiyIoqjnHpGT6K4Rj%2BK0VjSExLxJBIgBOZKUtS1KsI4py0M4XjyWY6LBJgYSqELBRJOk9kADFSs4adZ3nVRF01VBQvZOS2E4RSfJUtSEqwkjOJ02j9OKQyGxM6QzKUCzOyshNMEwPB0DJBykKy8FOCzKpGXQVYQrZKJVmqpgi285S/KI0jyMo6jdLo9YEWKPaWoO4hwsi/K0Vi9iAQ4TjUI24kLD4z6Yt%2Brx1sJHKoq%2B1MEjsSQgA%3D%3D%3D) complaint about a missing initializer with `-Wall -Wextra`. Those were still recent versions when we started defining the API. It's less important today, but the maintenance burden on having the correct number of `{0}` is small, so we've kept the habit.

(On the other hand, in hindsight, the `_init` functions don't really serve any purpose, and we'll probably remove them in version 2 of the PSA Crypto API.)

**Comment by irwir** [comment]
> maintenance burden on having the correct number of `{0}` is smal

The code looks too verbose, and at least an extra commit had to be added just to handle the "missing initializer" non-issue.
Sooner or later this warning would go away with  dropped support of obsolete compiler features.
Visual C is limited to relatively recent 2017, 2019 and 2022 versions, while the current gcc is 14.2 and Clang - 18.1.8.

**Comment by gilles-peskine-arm** [comment]
The age of compilers in years isn't everything. If we dropped all compiler-specific hacks due to incomplete C99 support (i.e. the code doesn't compile/work, not just warnings), I think we'd have to require VS 2019 (currently we officially support VS 2017), whereas GCC 5.x and Clang 3.6 are fine (even GCC 4.x if invoked in C99 mode).

**Comment by irwir** [comment]
No wonder it would be `fine` with sufficient amount of additinal code, conditional compilation and pragmas - this issue and PR #8515 as examples.
Maybe this kind of warnings should be just silenced where appropriate, but this is up to maintainers.
Thanks for the discussion.
