### ISSUE TITLE
Add better error message for people who download the GitHub archives

### ISSUE THREAD

**Issue by davidhorstmann-arm** [Mbed-TLS/mbedtls#9538]
GitHub auto-creates release archives for new releases that do not include the contents of the submodules.

Our current submodule-not-found errors in the `Makefile`s and `CMakeLists.txt` tell the user to run `git submodule update --init` but this does not work in the release archive as it is not a git repository.

In the place where we check for the presence of the submodule, do the following things:
* Check if there is a `.git` directory present.
* If there is, print the current message about `git submodule update --init`.
* If there isn't print a message suggesting that they may have downloaded the wrong archive files from GitHub.

**Comment by mpg** [comment]
Context: have a look at https://github.com/Mbed-TLS/mbedtls/releases/tag/mbedtls-3.6.2 - the two files "Source code (zip/tar.gz)" in the assets list at the end are the wrong ones, and the right one is mbedtls-3.6.2.tar.bz2, as per the note above.

The goal of this issue is make the error message more helpful to people who've accidentally picked the wrong archive.

Cc @Harry-Ramsey
