### ISSUE TITLE
Getting PSA multiple definition error with TFM and MBEDTLS

### ISSUE THREAD

**Issue by vikasshah1991** [Mbed-TLS/mbedtls#9550]
### Summary
Using MBEDTLS version 3.4.0 and MBEDTLS_PSA_CRYPTO_C flag is enabled since using TLS 1.3. At the same time have TFM as well. Since both MBEDTLS and TFM has PSA implementation it results into multiple definition error. 

### System information

Mbed TLS version (number or commit id):  3.4.0
Operating system and version: 
Configuration (if not default, please attach `mbedtls_config.h`): 
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): 
Additional environment information: 

### Expected behavior
Should not have any build errors and link with TFM PSA implementation

### Actual behavior
Multiple definition error

**Comment by gilles-peskine-arm** [comment]
If you're getting the cryptography implementation via TF-M, you need to compile Mbed TLS with compatible options:

* Disable `MBEDTLS_PSA_CRYPTO_C` and enable `MBEDTLS_PSA_CRYPTO_CLIENT` since cryptography isn't implemented through local functions, but through TF-M's remote procedure calls.
* In the non-secure world, declare the same cryptographic mechanisms as the secure world. Enable `MBEDTLS_PSA_CRYPTO_CONFIG`, and enable the same `psa/crypto_config.h` (defining `PSA_WANT_xxx` symbols) as the secure world.
* Enable `MBEDTLS_USE_PSA_CRYPTO` since TLS code needs to call PSA functions for cryptography, not legacy functions.
* Don't enable legacy cryptography algorithms (`MBEDTLS_RSA_C`, `MBEDTLS_AES_C`, etc.) since they would use local code, not TF-M calls.

Please note that Mbed TLS 3.4 has known security holes. You should upgrade to the latest minor release (3.6.1) immediately. We've also fixed many bugs in builds using TF-M since 3.4.

**Comment by gilles-peskine-arm** [comment]
I'm closing this issue because it seems to be a support request, not a bug report or a feature request. Please use the [mailing list](https://lists.trustedfirmware.org/mailman3/lists/mbed-tls.lists.trustedfirmware.org/) for support requests and discussions of Mbed TLS integration.

**Comment by vikasshah1991** [comment]
okay. Thanks for response.
Since there are PSA driver wrapper file available to modify for the PSA crypto driver. Can we hook in the renamed crypto implementation of TFM APIs there. Will this work? if we dont want to disable MBEDTLS_PSA_CRYPTO_C since it is mandatory for TLS1.3

psa_crypto_driver_wrapper.c
psa_driver_wrapper_sign_hash
{
      /* if TFM is enabled */
      tfm_psa_sign_hash()
}
