### ISSUE TITLE
Intermittent failure of the slowest ssl-opt test case with MSan

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#9742]
In `component_test_memsan`, we've observed an intermittent failure of the `ssl-opt.sh` test case `TLS 1.3 m->G: AES_128_GCM_SHA256,ffdhe8192,rsa_pss_rsae_sha256`, only on the Internal CI (OpenCI passed), on two successive runs of the merge queue on https://github.com/Mbed-TLS/mbedtls/pull/9738. That pull request does not affect the test case in question, so it's probably just due to chance that it happened there.

The root cause of the failure if not clear to me at this point, but I think a timeout is involved, even though no message indicates a timeout. Here's the [console log with timings](https://jenkins-mbedtls.oss.arm.com/blue/rest/organizations/jenkins/pipelines/mbed-tls-pr-head/branches/gh-readonly-queue%252Fdevelopment%252Fpr-9738-69868299a843d1925f4799de6f43b1b31a4e9357/runs/1/nodes/685/steps/5295/log/?start=0). (The timestamp is when the line was printed, so the run time for a test case is its timestamp minus the previous timestamp.)

```
[2024-10-30T15:21:52.218Z] TLS 1.2: Check rsa_pss_rsae compatibility issue, m->O .................. PASS
[2024-10-30T15:21:53.144Z] TLS 1.2: Check rsa_pss_rsae compatibility issue, m->G .................. PASS
[2024-10-30T15:21:55.664Z] TLS 1.3 G->m: AES_128_GCM_SHA256,ffdhe3072,rsa_pss_rsae_sha256 ......... PASS
[2024-10-30T15:21:57.558Z] TLS 1.3 m->G: AES_128_GCM_SHA256,ffdhe3072,rsa_pss_rsae_sha256 ......... PASS
[2024-10-30T15:22:02.027Z] TLS 1.3 G->m: AES_128_GCM_SHA256,ffdhe4096,rsa_pss_rsae_sha256 ......... PASS
[2024-10-30T15:22:05.294Z] TLS 1.3 m->G: AES_128_GCM_SHA256,ffdhe4096,rsa_pss_rsae_sha256 ......... PASS
[2024-10-30T15:22:17.491Z] TLS 1.3 G->m: AES_128_GCM_SHA256,ffdhe6144,rsa_pss_rsae_sha256 ......... PASS
[2024-10-30T15:22:32.385Z] TLS 1.3 m->G: AES_128_GCM_SHA256,ffdhe6144,rsa_pss_rsae_sha256 ......... PASS
[2024-10-30T15:23:11.216Z] TLS 1.3 G->m: AES_128_GCM_SHA256,ffdhe8192,rsa_pss_rsae_sha256 ......... PASS
[2024-10-30T15:23:57.935Z] TLS 1.3 m->G: AES_128_GCM_SHA256,ffdhe8192,rsa_pss_rsae_sha256 ......... FAIL
[2024-10-30T15:23:57.935Z]   ! pattern 'HTTP/1.0 200 OK' MUST be present in the Client output
[2024-10-30T15:23:57.935Z]   ! outputs saved to o-XXX-1941.log
[2024-10-30T15:23:58.946Z] TLS 1.3: no HRR in case of PSK key exchange mode ....................... PASS
```

Client and server logs:
[all_u16-test_memsan-o-cli-1941.log.txt](https://github.com/user-attachments/files/17577458/all_u16-test_memsan-o-cli-1941.log.txt)
[all_u16-test_memsan-o-srv-1941.log.txt](https://github.com/user-attachments/files/17577468/all_u16-test_memsan-o-srv-1941.log.txt)

**Comment by mpg** [comment]
From the logs it really doesn't look like the client was killed by a timeout: it received a `close_notify` alert and got the time to send one itself before freeing everything and returning one. Notice the reason the test is marked as failed is that the string `HTTP/1.0 200 OK` was not found in the client's output.

So the question would be, why is the server sending a `close_notify` immediately, as opposed to reading the HTTP request from the socket and sending its HTTP response first? I'd say a partial answer can be found in the server's log:
```
Scheduling inactive connection for close
```
Apparently the connection is deemed inactive by the server, so it choses to send a `close_notify` alert and close the socket. 

Possible reasons I can imagine:
1. The server starts a timer when receiving the ClientHello (or even TCP SYN) and if no ApplicationData has been received X seconds after that event (as opposed to after the handshake is completed), then the connection is deemed inactive and closed. Since the handshake takes such a long time with the large parameter + sanitizer, by the time it completes, the connection is inactive before the server had a chance to receive any ApplicationData.
2. The server's timer starts when the handshake is completed, but for some reason related to the worker's load, the client's ApplicationData record is delayed in the networking stack, or the server isn't scheduled for a long time, in any case by the time the server could read the ApplicationData, the inactivity delay has already kicked in. (Seems less likely to me.)

**Comment by mpg** [comment]
I'm not seeing any obvious command-line option to configure the delay in `gnutls-serv`, but a quick fix could be to stop requiring that `HTTP/1.0 200 OK` must be present. Just asserting the that client exited 0 and its logs contains `Protocol is TLSv1.3` or whatever should be enough to ensure the handshake completed successfully.

**Comment by mpg** [comment]
I'm running out of time to track how the timer is managed by the server but here's a starting point in case someone else feels like it: https://github.com/rockdaboot/gnutls/blob/master/src/serv.c#L1568

**Comment by gilles-peskine-arm** [comment]
@mpg Thank you very much for the analysis! That explains where the timeout comes from.

> apparently the timeout value is a compile-time option defaulting to 30s

It is _now_, but until [recently](https://github.com/rockdaboot/gnutls/commit/b133511328c6a66e8c8b83e50caabee066753308) 30 was hard-coded. Even `GNUTLS_NEXT` is older than that.

I've filed https://github.com/Mbed-TLS/mbedtls/issues/9745 to potentially upgrade GnuTLS, which is more effort and risk than I want to spend now. (In fact I'm not sure increasing the timeout is so important: we don't get a lot of complaints from MSan. The risk that ASan is happy with all FFDH sizes, and MSan is happy with FFDH-4096, but there is a bug with FFDH-8192 that MSan would catch, is pretty low.)

In the meantime, I've pushed https://github.com/Mbed-TLS/mbedtls/pull/9746 to skip the offending test case (and the corresponding client one, and the 6k-bit test cases to have a safety margin).
