### ISSUE TITLE
CRL checks for Certificates received in TLS Server Hello

### ISSUE THREAD

**Issue by mithilRokdey** [Mbed-TLS/mbedtls#9779]
### Suggested enhancement
Hello, 

This is more of a question, but can become an enhancement request if the feature is not available. 

We are using MbedTLS library for our crypto and  TLS operations in 1 of our product. Here while establishing TLS with our cloud, we receive cloud's Leaf Certificate and  its ICA certificate. And we validate the cert chain as usual against our ROOT CA. 

In our PKI infrastructure, we maintain 2 different CRLs here - 1 CRL for Leaf cert and another for ICA. And both the CRLs are stored in our device (and are updated periodically). 

Now i need an input on how to use MBedTLS APIs to make sure i validate the Leaf Cert's presence in the Leaf  CRL ONLY and  similarly ICA's cert in ICA CRL itself. I could not find an approrpiate API in embedTLS library. 

May be i am missing something here, but can someone guide me on how to use the MbedTLS library to validate both of these certs in their respective CRLs. 

Any input or direction would be highly appreciated. 

### Justification

Mbed TLS needs this because this is a common methodology used for TLS in many products.

**Comment by tom-daubney-arm** [comment]
Hi, since this is a support request I would like to direct you to the mailing list, which is where we handle requests of this nature. You should get some replies on there which will hopefully provide the assistance you need.

[The mailing list.](https://lists.trustedfirmware.org/mailman3/lists/mbed-tls.lists.trustedfirmware.org)
